scylla/src/frame/response/result.rs
scylla/src/frame/types.rs

It's not necessary to use read_raw_bytes because we already check the
length of the buffer before converting to IPv4 or IPv6.

result.rs: streamline parsing of inet data type

---

examples/basic.rs
examples/cqlsh-rs.rs
examples/parallel.rs
scylla/src/transport/connection.rs
scylla/src/transport/session.rs
scylla/src/transport/session_test.rs

We now use `lookup_host` to perform a DNS resolution, and attempt to
find an IPv4 among the returned addresses.
Connection, however, was modified to take a concrete SocketAddr.
This will be useful later when we implement shard awareness.

session: bring back ToSocketAddrs

---

examples/Cargo.toml
examples/parallel-prepared.rs

Interestingly, this one is much slower than the standard `parallel` example.
May be because we need to query the Ring.

examples: parallel execution of prepared statements

---

examples/compare-tokens.rs
scylla/Cargo.toml
scylla/src/routing.rs
scylla/src/transport/session_test.rs

In order to be compatible with Cassandra, we can't use an implementation
from a library. The original implementation of murmur hash in Cassandra
was bugged, and we need to replicate those bugs.
Extends the compare-token example with pks that gave incorrect tokens in
the previous implementation.

Fix (or break?) murmur hash implementation

---

.github/workflows/rust.yml
scylla/src/frame/mod.rs
scylla/src/frame/response/result.rs
scylla/src/routing.rs
scylla/src/transport/connection.rs
scylla/src/transport/session.rs
scylla/src/transport/topology.rs

Currently running `cargo clippy` produces 12 warnings which makes it hard to notice tips for newly written code.
This PR applies clippy's suggestions to remove the warnings.
Clippy is buggy and might show no output when ran on already build project
Running `touch $(find ./scylla) && cargo clippy` allows to refresh the build and clippy works ok

Remove cargo clippy warnings

---

Cargo.toml
examples/Cargo.toml
examples/basic.rs
examples/select-paging.rs
scylla-macros/Cargo.toml
scylla-macros/src/lib.rs
scylla/Cargo.toml
scylla/src/frame/response/cql_to_rust.rs
scylla/src/frame/response/mod.rs
scylla/src/frame/response/result.rs
scylla/src/lib.rs
scylla/src/macros.rs
scylla/src/transport/iterator.rs
scylla/src/transport/session.rs

This PR implements a way to parse rows returned by Session::query as strongly typed tuples or custom types.
For example:
```rust
// Rows can be parsed as tuples
if let Some(rows) = session.query("SELECT a, b, c FROM ks.t", &[]).await? {
for (a, b, c) in rows.into_typed::<(i32, i32, String)>() {
println!("a, b, c: {}, {}, {}", a, b, c);
}
}
// Or as custom structs that derive FromRow
#[derive(Debug, FromRow)]
struct RowData {
a: i32,
b: Option<i32>,
c: String,
}
if let Some(rows) = session.query("SELECT a, b, c FROM ks.t", &[]).await? {
for row_data in rows.into_typed::<RowData>() {
println!("row_data: {:?}", row_data);
}
}
```
API proposed in #99 turned out very verbose because each `SELECT` required specifying returned row type (Rust has no default generic arguments) and there were some …

Strongly typed query rows (Fixes #99)

---

scylla/src/frame/request/batch.rs
scylla/src/frame/request/mod.rs
scylla/src/frame/request/query.rs
scylla/src/frame/types.rs
scylla/src/lib.rs
scylla/src/statement/batch.rs
scylla/src/statement/mod.rs
scylla/src/transport/connection.rs
scylla/src/transport/session.rs
scylla/src/transport/session_test.rs

This PR implements basic support for sending multiple statements at once using the BATCH request (issue [#74 ](https://github.com/scylladb/scylla-rust-driver/issues/74)). Prepared statements might not work properly (because prepared statement ids are local to a node).
Usage preview:
```rust
use crate::batch::Batch;
let mut batch: Batch = Default::default();
batch.append_statement("INSERT INTO ks.t (a, b, c) VALUES (?, ?, ?)");
batch.append_statement("INSERT INTO ks.t (a, b, c) VALUES (7, 11, '')");
batch.append_statement(prepared_statement);
let values = [
values!(1_i32, 2_i32, "abc"),
Vec::new(),
values!(1_i32, 4_i32, "hello"),
];
session.batch(&batch, &values).await.unwrap();
```

Support batches (Fixes: #74)

---

README.md

Since we're now able to properly type returned rows,
let's also present that in the README.

README: change the example to typed code

---

examples/Cargo.toml
examples/user-defined-type.rs
scylla-macros/src/from_row.rs
scylla-macros/src/from_user_type.rs
scylla-macros/src/into_user_type.rs
scylla-macros/src/lib.rs
scylla/src/frame/request/batch.rs
scylla/src/frame/request/query.rs
scylla/src/frame/response/result.rs
scylla/src/frame/types.rs
scylla/src/frame/value.rs
scylla/src/macros.rs
scylla/src/transport/session_test.rs

This PR implements support for using User Defined Types that can be used like this:
```rust
// CREATE TYPE IF NOT EXISTS ks.my_type (int_val int, text_val text)
// Define custom struct that matches User Defined Type created earlier
// wrapping field in Option will gracefully handle null field values
#[derive(Debug, IntoUserType, FromUserType)]
struct MyType {
int_val: i32,
text_val: Option<String>,
}
let to_insert = MyType {
int_val: 17,
text_val: Some("Some string".to_string()),
};
// It can be inserted like a normal value
session
.query(
"INSERT INTO ks.udt_tab (k, my) VALUES (5, ?)",
&(try_values!(to_insert)?),
)
.await?;
// And read like any normal value
if let Some(rows) = session.query("SELECT my FROM ks.udt_tab", &[]).await? {
for row in rows.into_typed::<(MyType,)>() {
let …
```

Add support for User Defined Types (Issue #98, #105)

---

scylla/src/transport/connection.rs
scylla/src/transport/topology.rs

With the driver name explicitly passed, scylla-rust-driver connections can be easily recognized via CQL:
```cql
cassandra@cqlsh> select address, port, client_type, driver_name from system.clients ;
address   | port  | client_type | driver_name
-----------+-------+-------------+---------------------------------------
127.0.0.1 | 43376 |         cql |                                  null
127.0.0.1 | 43378 |         cql |                                  null
127.0.0.1 | 44072 |         cql |                    scylla-rust-driver
127.0.0.1 | 44074 |         cql | scylla-rust-driver:control-connection
```

Allow passing driver name via CQL startup message

---

scylla/src/frame/request/prepare.rs
scylla/src/transport/connection.rs
scylla/src/transport/session.rs
scylla/src/transport/transport_errors.rs

This pull request implements #106 by sending PREPARE via all available connections.

Run PREPARE on all nodes (Issue #106)

---

scylla/Cargo.toml
scylla/src/frame/frame_errors.rs
scylla/src/frame/mod.rs
scylla/src/transport/connection.rs

Currently, we are using the "snappy" crate for compression/decompression
of frames. This crate is just a binding to the C++ snappy library, and
therefore requires it to already be installed when building the crate.
This commit removes "snappy" crate as a dependency; now, the "snap"
crate is used, which is a pure Rust implementation of the snappy
algorithm with performance comparable to the C++ library. Now, the C++
library doesn't have to be installed when compiling the driver.
This change makes the driver compile and pass all units test on my
Windows installation.
Fixes #129

Switch to using "snap" crate instead of "snappy"

---

.github/workflows/rust.yml
examples/basic.rs
examples/compare-tokens.rs
examples/cqlsh-rs.rs
examples/parallel-prepared.rs
examples/parallel.rs
examples/select-paging.rs
examples/user-defined-type.rs
scylla/src/frame/types.rs
scylla/src/transport/connection.rs
scylla/src/transport/session_test.rs

* Add `--examples` and `--tests` flags to `cargo clippy` to make it check examples and tests
* Add `--examples` to `cargo build` to also build examples
Before these changes it was possible to submit an example that doesn't compile and CI would pass

Add more checks to CI

---

scylla/src/transport/session_test.rs

Currently all tests in `session_test.rs` connect to `127.0.0.1:9042`
This PR adds an option to specify a different uri using an environment variable, like in the examples.
Tests can then be run like this:
```bash
SCYLLA_URI=172.17.0.3:9042 cargo test -- --ignored
```

Add SCYLLA_URI parameter to session tests

---

examples/basic.rs
examples/compare-tokens.rs
examples/select-paging.rs
examples/user-defined-type.rs

`Session::connect()` now does `refresh_topology()` on startup so we call it twice in examples, which is not needed.

Remove needless refresh_topology()

---

examples/Cargo.toml
examples/parallel-prepared.rs
examples/parallel.rs
examples/select-paging.rs

The examples used a different version of Tokio than the driver itself - this PR upgrades Tokio in examples, too. Additionally, name of one of the examples was changed (parallel-prep -> parallel-prepared).

Upgrade Tokio in examples so that they compile and run

---

scylla/src/transport/connection.rs
scylla/src/transport/session.rs
scylla/src/transport/session_builder.rs

This pull requests abstracts the connection options to a separate structure and adds a way of configuring `nodelay` parameter. It also makes the default to `true`, under the assumption that users expect low latency and are not interested in delaying the outgoing packets with Nagle's algorithm.

Add nodelay param

---

.github/pull_request_template.md
CONTRIBUTING.md

Adds two documents which should help contributors make sure that their
changes meet basic quality standards before they are submitted as a PR
for review:
- CONTRIBUTING.md contains a pre-review checklist which should be
followed by contributors before submitting PRs. It also contains some
information about current maintainers, static checks and testing.
- .github/pull_request_template.md contains a list of pre-review checks,
similar to the one in CONTRIBUTING.md. The list will show up before
trying to send a PR, therefore it will be seen also by people who
didn't look at CONTRIBUTING.md.

Add CONTRIBUTING.md and PR template

---

scylla/src/transport/connection.rs
scylla/src/transport/topology.rs

DataStax (nodejs driver) claims that you shouldn't use system.local's rpc_address unless the client specifies SNI in the options. For now I have omitted that and will use rpc_address which is meant for clients to receive. DataStax defaults to using the initial connections address for the control connection (Which we could expose from conn) but I've left a comment explaining for now.
Also cleaned up parsing of ipv6 in the connection with port function.

Local control connection should be using rpc_address instead of listen address

---

scylla/src/transport/cluster.rs
scylla/src/transport/load_balancing.rs
scylla/src/transport/mod.rs
scylla/src/transport/node.rs
scylla/src/transport/session.rs
scylla/src/transport/session_builder.rs

This pull request adds configurable load balancing.
There are 3 composable policies:
- Round robin (`RoundRobinPolicy`) Fixes #122
- DC aware round robin (`DCAwareRoundRobinPolicy`) Fixes #123
- Token aware (`TokenAwarePolicy`, wraps another policy) Fixes #124
All policies implement trait `LoadBalancingPolicy`. Session constructor accepts optional specification of load balancing policy (by passing `Option<Box<dyn LoadBalancingPolicy>>`). Session's default policy is token aware round robin. Fixes #121
Each policy has a method `plan(statement_info, &cluster)`, which inspects statement info, and returns an iterator designating the order of nodes in a query plan.
In order to support being a child policy, `RoundRobinPolicy` &  `DCAwareRoundRobinPolicy` also implement trait …

Load balancing (Issue #121, #122, #123, #124)

---

scylla/src/transport/session.rs

When generating docs, a warning showed that one of the refs
was outdated, so it's hereby updated.

session: fix a doc reference

---

README.md

cdrs is reportedly unmaintained, so the link is changed to point
to its maintained successor.
Fixes #165

README: update "Other drivers" tab

---

scylla/src/transport/connection.rs
scylla/src/transport/topology.rs

When fetching topology information from the cluster we used to query `rpc_address` from `system.local` to find local node's address.
This was a mistake - unless SNI is enabled we should just use the existing connection's address.
In #154 it was mentioned that this is what DataStax driver does.
Probably #171, but I have a hard time recreating the exact setup in which the bug occured
- ~[ ] I added relevant tests for new features and bug fixes.~ I'm not sure how to test this but I looked manually at the address we connect to

Use connection address instead of rpc_address in system.local

---

scylla/src/frame/response/result.rs
scylla/src/transport/cluster.rs
scylla/src/transport/connection.rs
scylla/src/transport/connection_keeper.rs
scylla/src/transport/errors.rs
scylla/src/transport/load_balancing.rs
scylla/src/transport/node.rs
scylla/src/transport/session.rs
scylla/src/transport/session_builder.rs
scylla/src/transport/session_test.rs
scylla/src/transport/topology.rs

This PR allows to perform `USE keyspace_name` queries on the database.
Like this:
```rust
session.use_keyspace("my_keyspace").await?;
```
Or during session creation:
```rust
let session: Session = SessionBuilder::new()
.known_node("127.0.0.1:9042")
.use_keyspace("use_ks_test")
.build()
.await?;
```
New keyspace to use is being sent using channels to `ClusterWorker` and then to `NodeWorker`.
Those workers do an async `select` on their work and use keyspace requests.
This ensures that no new `Nodes`/`ConnectionKeepers` are created when keyspace is changed.
Each worker keeps `used_keyspace` and later passes it when creating `Nodes`/`ConnectionKeepers`.
I used channels because they were much easier to reason about than mutexes. Mutexes could easily have race conditions when creating new …

Support USE statement

---

scylla/src/transport/session_test.rs

I forgot to remove `#[ignore]` from keyspace tests in the original PR.
They should be removed because we now run all tests in CI.

Remove #[ignore] from keyspace tests

---

scylla/src/transport/session_test.rs

The test case indicates that we support enough CQL types to parse
schema keyspace information. The test used to fail before the latest merge of almost all CQL types.

session_test: add a test for fetching keyspace info

---

scylla/src/routing.rs
scylla/src/transport/connection.rs
scylla/src/transport/connection_keeper.rs
scylla/src/transport/errors.rs
scylla/src/transport/node.rs

This PR makes `ConnectionKeeper` detect when the connection breaks and reopen it in a loop.
Reopening is on an 8 second cooldown to not spam the network with reconnects.
Additionally `ConnectionKeeper` is now able to detect that a source port collision has occured and will retry on a different port.
First a random port is chosen, then we add `nr_shards` and wrap around until we check all possible ports (just like piodul described in #149).
Fixes: #149

Make ConnectionKeeper keep the connection open

---

examples/Cargo.toml
examples/logging.rs
scylla/Cargo.toml
scylla/src/transport/connection.rs
scylla/src/transport/session.rs

This pull request adds integration with logging library [tracing](https://crates.io/crates/tracing) (actual logging is abstracted, consumer of our driver can choose a suitable logging implementation).
Calls to `eprintln!` have been replaced with `warn!` event emission. I think It's a good idea to log more events in the future, but as for now, only warnings that existed before are logged (except for stream allocation failure warning in connection.rs, that's new).
I have also added new example, that uses `tracing-subscriber` to log events to stdout.
Fixes: #158

Integration with logging library

---

.github/workflows/cassandra.yml

Adds a workflow in which all tests are run using a Cassandra instance to ensure full compatibility.
I am not sure if the flag `--test-threads=1` is really needed, all tests are written in a way that allows to run them in parallel.
I made a test in #192 but there was no real time gained by removing it, majority of time is spent compiling the project, tests take only a small amount of time. I left it in, doesn't really hurt and is consistent with `rust.yml`.

Run all tests on Cassandra in CI

---

scylla/src/frame/response/error.rs
scylla/src/frame/types.rs
scylla/src/statement/batch.rs
scylla/src/statement/prepared_statement.rs
scylla/src/statement/query.rs
scylla/src/transport/connection.rs
scylla/src/transport/errors.rs
scylla/src/transport/iterator.rs
scylla/src/transport/load_balancing/dc_aware_round_robin.rs
scylla/src/transport/load_balancing/mod.rs
scylla/src/transport/load_balancing/round_robin.rs
scylla/src/transport/load_balancing/token_aware.rs
scylla/src/transport/metrics.rs
scylla/src/transport/mod.rs
scylla/src/transport/node.rs
scylla/src/transport/retry_policy.rs
scylla/src/transport/session.rs
scylla/src/transport/session_builder.rs
scylla/src/transport/session_test.rs

This PR adds support for `RetryPolicy` - when a query fails this `RetryPolicy` decides whether we should retry on this node, next node or don't retry at all.
All `RetryPolicies` implement the trait `RetryPolicy`:
```rust
pub trait RetryPolicy {
fn decide_should_retry(&mut self, query_info: QueryInfo) -> RetryDecision;
// Reset before using for the next query
fn reset(&mut self);
fn clone_boxed(&self) -> Box<dyn RetryPolicy + Send + Sync>;
}
/// Information about a failed query
pub struct QueryInfo<'a> {
/// The error with which the query failed
pub error: &'a QueryError,
/// A query is idempotent if it can be applied multiple times without changing the result of the initial application  
/// If set to `true` we can be sure that it is idempotent  
/// If set to `false` it is unknown …
```

Retry Policy

---

examples/cql-time-types.rs
examples/cqlsh-rs.rs
examples/user-defined-type.rs
scylla-macros/src/from_row.rs
scylla-macros/src/from_user_type.rs
scylla/src/frame/cql_types_test.rs
scylla/src/frame/frame_errors.rs
scylla/src/frame/mod.rs
scylla/src/frame/response/cql_to_rust.rs
scylla/src/frame/response/error.rs
scylla/src/frame/response/result.rs
scylla/src/frame/types.rs
scylla/src/transport/cluster.rs
scylla/src/transport/connection.rs
scylla/src/transport/connection_keeper.rs
scylla/src/transport/errors.rs
scylla/src/transport/load_balancing/dc_aware_round_robin.rs
scylla/src/transport/load_balancing/mod.rs
scylla/src/transport/load_balancing/token_aware.rs
scylla/src/transport/mod.rs
scylla/src/transport/node.rs
scylla/src/transport/retry_policy.rs
scylla/src/transport/session_builder.rs
scylla/src/transport/session_test.rs

After update to Rust 1.51 cargo clippy shows more suggestions.
We need to apply them in order to pass the CI.
* All abbreviations changed so that only the first letter is uppercase (`LZ4` -> `Lz4`, `CQL` -> `Cql`, etc...)
* Removed some redundant slicings (`&slice[..]` -> `slice`)
* `Vec::new(); vec.push()` changed to `vec![]`
* Changed `Into` to `From`
* Removed redundant `;`

Apply suggestions from clippy 1.51

---

scylla/src/frame/cql_types_test.rs
scylla/src/frame/response/cql_to_rust.rs
scylla/src/frame/response/result.rs
scylla/src/frame/value.rs

There were missing implementations for `IpAddr` and `Vec<u8>` which didn't allow to send/receive them in queries properly.
Added:
* `impl Value for IpAddr`
* `impl FromCQLVal for Vec<u8>`
* Tests for `Inet` and `Blob`
Fixes: #201

Fix sending/receiving Inet and Blob in queries

---

README.md
examples/Cargo.toml
examples/basic.rs
examples/compare-tokens.rs
examples/cql-time-types.rs
examples/tls.rs
examples/tracing.rs
examples/user-defined-type.rs
scylla/src/frame/cql_collections_test.rs
scylla/src/frame/cql_types_test.rs
scylla/src/frame/mod.rs
scylla/src/lib.rs
scylla/src/statement/batch.rs
scylla/src/statement/prepared_statement.rs
scylla/src/statement/query.rs
scylla/src/tracing.rs
scylla/src/transport/connection.rs
scylla/src/transport/iterator.rs
scylla/src/transport/session.rs
scylla/src/transport/session_test.rs
scylla/src/transport/topology.rs

This PR adds support for CQL tracing.
Tracing can be used like this:
```rust
// Create a simple query and enable tracing for it
let mut query: Query = Query::new("SELECT peer from system.peers".to_string());
query.set_tracing(true);
// QueryResult will contain a tracing_id which can be used to query tracing information
let query_result: QueryResult = session.query(query.clone(), &[]).await?;
let query_tracing_id: Uuid = query_result
.tracing_id
.ok_or_else(|| anyhow!("Tracing id is None!"))?;
// Get tracing information for this query and print it
let tracing_info: TracingInfo = session.get_tracing_info(&query_tracing_id).await?;
println!("Query tracing info: {:#?}\n", tracing_info);
```
Queries that support tracing are:
* `Session::query()`
* `Session::prepare()`
* `Session::execute()`
* …

CQL Tracing

---

README.md

The driver is not officially supported, but it's already stable enough
for people to give it a go. Let's make the README bit less scary.

Make README less scary

---

book/src/connecting/authentication.md
book/src/connecting/tls.md
book/src/load-balancing/load-balancing.md
book/src/queries/batch.md
book/src/queries/prepared.md
book/src/queries/simple.md
book/src/quickstart/create-project.md
book/src/title-page.md

After release to crates.io the book needs some updates:
* Changed github links in Cargo.toml to crates.io crate
* Added links to API documentation on docs.rs
* Added chapter about authenticatoin
* Improved load balancing section
I already updated the hosted html to make sure that no one mistakenly adds the gitihub link in their Cargo.toml

Update documentation book after release 0.1.0

---

.github/workflows/authenticate_test.yml
.github/workflows/book.yml
.github/workflows/tls.yml

Now that the driver is officially released, the temporary docker images are moved to the official account.

workflows: migrate to official scylladb docker images

---

scylla/src/frame/mod.rs
scylla/src/frame/request/mod.rs
scylla/src/frame/request/register.rs
scylla/src/frame/response/event.rs
scylla/src/frame/response/mod.rs
scylla/src/frame/server_event_type.rs
scylla/src/frame/types.rs
scylla/src/transport/cluster.rs
scylla/src/transport/connection.rs
scylla/src/transport/connection_keeper.rs
scylla/src/transport/node.rs
scylla/src/transport/session.rs
scylla/src/transport/topology.rs

- Reduced control connection count to 1
- Added `Register` and `Event` frames
- Modified connection to allow sending `REGISTER` message
- Added mechanism to receive events and propagate them to cluster module
- Made cluster react to `TOPOLOGY_CHANGE` and `STATUS_CHANGE` events (and trigger topology metadata refresh Fixes: #85) 
`TopologyReader` creates control connections using special `ConnectionConfig` in which a sender half of mpsc channel is embedded. Control connection sends `REGISTER` message to a server and pushes every received event into its mpsc sender. `ClusterWorker` holds other half of this channel and processes events pushed by connection (triggers topology info refresh or deletes down nodes from associated `ClusterData`).

Receive server events

---

book/src/SUMMARY.md
book/src/queries/schema_agreement.md
examples/Cargo.toml
examples/schema_agreement.rs
scylla/src/transport/connection.rs
scylla/src/transport/session.rs
scylla/src/transport/session_builder.rs
scylla/src/transport/session_test.rs

Fixes: https://github.com/scylladb/scylla-rust-driver/issues/83
Created waiting for schema agreement mechanism for `Session` and setting the interval of that check in `SessionBuilder`.
User can now check local schema version and await for schema agreement with timeout or with endless timeout.
New methods: `Session::fetch_schema_version`, `Session::await_schema_agreement`, `Session::await_timed_schema_agreement`, `SessionBuilder::schema_agreement_interval`.
I'm not really sure what kind of tests should I provide to test that feature, so I'm asking now if adding line that awaits schema agreement in existing test is satisfactory? @psarna // solved

Schema agreement

---

docs/source/queries/paged.md
examples/select-paging.rs
scylla/src/frame/response/result.rs
scylla/src/statement/prepared_statement.rs
scylla/src/statement/query.rs
scylla/src/transport/connection.rs
scylla/src/transport/session.rs
scylla/src/transport/session_test.rs

This draft adds a way of resuming queries from previously received paging state. The paging state can be extracted from query results and passed to new queries to let them resume execution from where the previous query left off. It's an alternative way of querying to the existing `query_iter` mechanism.
This series is marked as a draft because of the following TODO list:
Fixes #219

Add resuming paging

---

examples/cqlsh-rs.rs

While the tool is still far away from cqlsh's friendliness,
the following issues are fixed:
- errors are printed in a human-redable fashion
- errors do not crash the process
- return values of SELECT statements are printed (in a semi-raw form,
but still readable)
- Ctrl+C does not terminate the program, Ctrl+D does
The TODO list for this tool to be really usable is still huge.
Issues include:
- no column names are printed, because there's no schema information
to take them from
- results are printed in a debug form, along with their type
- no support for paging
- no auth support
- etc.

examples: make cqlsh-rs more user-friendly

---

docs/source/conf.py

Fixes #221
Do not build docs for ``0.1.0`` since the tag does not contain a docs folder nor Sphinx.

Fixes: Base url throws a 404 error

---

.github/workflows/rust.yml
scylla/src/transport/connection.rs

The driver doesn't compile when the ssl feature is not enabled because we use `config` after move:
```rust
// connection.rs:594  
#[cfg(not(feature = "ssl"))]
async fn run_router(
config: ConnectionConfig,
stream: TcpStream,
receiver: mpsc::Receiver<Task>,
error_sender: tokio::sync::oneshot::Sender<QueryError>,
) -> Result<RemoteHandle<()>, std::io::Error> {
let _config = config;
Ok(Self::run_router_spawner(
stream,
receiver,
error_sender,
config,
))
}
```
This PR fixes the error and adds a check in the CI to ensure this doesn't happen again.

Fix compilation without ssl feature

---

.github/workflows/book.yml
CONTRIBUTING.md
docs/build_book.py

Documentation is now compatible with Sphinx which means that it contains Sphinx-specific fragments like:
````
```eval_rst
something
```
````
To build mdbook without them a script is needed.
This script removes Sphinx-specific parts and builds clean mdbook HTML

Add a script to build clean documentation book

---

.github/workflows/rust.yml

Recent clippy warnings do not really help maintain good coding
habits, but instead just keep breaking builds with overly opinionated
warnings. In order to reduce the noise, tests are no longer
checked with clippy.

workflows: do not run clippy for tests

---

scylla/src/transport/connection.rs
scylla/src/transport/connection_keeper.rs
scylla/src/transport/session.rs
scylla/src/transport/session_builder.rs

Scylla is generally assumed to be used for latency-sensitive
workloads, in which case it always makes sense to turn off
Nagle's algorithm. Thus, tcp_nodelay parameter is now true
by default and can be turned off manually when building
a new session.

treewide: make tcp_nodelay default to true

---

scylla/Cargo.toml
scylla/src/transport/cluster.rs

Recent benchmarks showed, that a significant amount of time is being spent waiting on Cluster's rw-lock protecting ClusterData structure. Thanks to the fact that we already use the rcu mechanism to update ClusterData, it was possible to remove RwLock and replace it with ArcSwap from arc-swap crate.
I also run few benchmarks and noticed ~1% performance  improvement (it can be bigger on machines more efficient than my pc).

Remove locking in Cluster

---

scylla/src/transport/connection_keeper.rs
scylla/src/transport/errors.rs

Currently, when connecting to a particular shard on the shard-aware
port, we need to choose a source port whose number equals the shard ID
modulo the shard count. We draw a random source port in range
49152-65535 which satisfies the conditions and try to bind to it. If
binding fails due to the address being in use, we try the next suitable
port in the range, possibly wrapping around if the end of the range is
reached. If binding/connecting fails due to other errors, we consider
the connection attempt a failure and the ConnectionKeeper retries
connecting after a delay.
However, it appears that there is another bind error which we didn't
consider but should be handled in a similar way as the "address in use
case": some ports/addresses might be reserved either by the OS or
processes with …

connection_keeper: try another source port on permission denied error

---

examples/Cargo.toml
examples/clone.rs
scylla/src/transport/retry_policy.rs
scylla/src/transport/session.rs
scylla/src/transport/session_builder.rs

This commit changes SessionBuilder::build(), so that it can be called multiple times and produce a valid session with given configuration each time it's called. The target use case is to prepare the configuration once and then spawn multiple sessions in order to do work in parallel.
Tested with the included example.
Refs #216

Allow creating multiple sessions with a single SessionBuilder

---

scylla/src/transport/connection.rs

Currently, during authentication, the "ERROR" frame is treated as
unexpected and an error with the following message is returned to the
user:
Unexpected response to Authenticate Response message
This commit causes the error from the "ERROR" frame to be propagated to
the user in case of authentication failure. For example, if bad
username/password combination is provided, Scylla will return the
following message:
Username and/or password are incorrect
which is much more helpful.
Fixes #257

connection: propagate authentication failure error to user

---

docs/source/queries/batch.md
docs/source/queries/prepared.md
docs/source/queries/simple.md
docs/source/quickstart/create-project.md

Documentation book still contains refrences to the driver in version `0.1.0`
I changed all `0.1.0` to `0.2.0`
I already uploaded this updated version to the github page

Update the book to 0.2.0

---

docs/_utils/deploy.sh
docs/_utils/drop_hashes.py

Sphinx, the framework used for publishing docs on
rust-driver.docs.scylladb.com, can't handle mdbook's comments
starting with '#', which results in broken docs pages.
A simple heuristics for removing incorrectly generated snippets
is added to the deploy script - it will work as long as sphinx
generates HTML the same way, so it may need to be revamped
in the future.

docs: remove stray hashes from rust-driver.docs.scylladb.com

---

scylla/src/transport/topology.rs

Currently, the TopologyReader is responsible for maintaining the control
connection. When the control connection breaks, it attempts to
re-establish by trying nodes from the `known_peers` list in random
order.
The `known_peers` list is modified only in two situations:
- It is initialized from the known nodes list from the session's
configuration,
- When topology refresh is requested, current control connection breaks
and is successfully reconnected, the `known_peers` list is
reinitialized from fetched topology info.
However, this is not enough. If only known node is provided in the
session configuration and the node is removed from the cluster, the
TopologyReader won't be able to reconnect the control connection because
the only node from the `known_peers` list has just been removed.
The …

topology: always update known_peers on refresh

---

examples/Cargo.toml
examples/auth.rs
scylla/src/frame/request/auth_response.rs
scylla/src/frame/response/authenticate.rs
scylla/src/transport/connection.rs

This PR fixes a small number of bugs in password authentication logic, mostly related to frame (de)serialization. Despite those bugs, authentication in Scylla worked - however, Cassandra behaves a little differently and incorrectly read/written frames prevent the authentication flow from working.
Refs: #272

Fix authentication for Cassandra

---

scylla/src/frame/frame_errors.rs
scylla/src/frame/request/auth_response.rs
scylla/src/transport/errors.rs

This series reworks error messages in order to avoid losing their context and improve their readability. It was tested manually based on the authentication error case described in #243 - where failing to provide username or password in the session builde resulted in a very cryptic (and incorrect) message:
```
Error parsing message frame
```
After the series is applied, the same scenario returns the following:
```
Invalid message: Frame error: Could not serialize frame: Bad credentials: username or password missing. You can use SessionBuilder::user("user", "pass") to provide credentials.
```
Fixes #244 
Refs #272

Make error message propagation more robust

---

examples/Cargo.toml
examples/get_by_name.rs
scylla/src/frame/response/result.rs
scylla/src/transport/connection.rs
scylla/src/transport/session_test.rs

This series is a first baby step towards solving #271 - which is about enabling users to get column values from result rows by name instead of by index.

Add getting column specification by name

---

scylla/src/frame/cql_types_test.rs
scylla/src/frame/response/result.rs

When you create an User Defined Type, then insert a frozen udt into a table, then add a field to this UDT (on both Scylla schema and Rust code) the driver will fail to parse the UDT with the error: "Invalid message: Error parsing message: failed to fill whole buffer".
This is because the driver tries to read the new field from the buffer but it reached the end of it.
This fix simply stop parsing UDT fields when buffer is empty.
Fixes: Stop parsing UDT fields when buffer is empty.

Stop parsing UDT fields when buffer is empty.

---

docs/source/conf.py

Fix https://github.com/scylladb/scylla-rust-driver/issues/289

fix link from top menu

---

scylla-macros/src/from_row.rs
scylla/src/frame/response/cql_to_rust.rs

`FromRowError::BadCqlVal` was made more useful by adding a related column index.
Also, error messages were changed from "Bad CQL Value" to something like "Value is null in the column with index 2".
Fixes: #287

Add more information to `FromRowError`

---

scylla/src/statement/batch.rs
scylla/src/statement/prepared_statement.rs
scylla/src/statement/query.rs

This pull request fixes some copy-paste errors in the statement module's getter/setter doc comments.

Fix misleading getter/setter doc comments in the statement module

---

docs/source/queries/values.md
examples/Cargo.toml
examples/value_list.rs
scylla-macros/Cargo.toml
scylla-macros/src/lib.rs
scylla-macros/src/value_list.rs
scylla/Cargo.toml
scylla/src/macros.rs
scylla/src/transport/session_test.rs

This commit adds a `ValueList` derive macro, which allows passing structs as value lists for queries. Each field in the struct will be used as a value, in the same order as the struct's definition. Example usage:
```rust
#[derive(scylla::ValueList)]
struct MyType {
k: i32,
my: Option<String>,
}
let to_insert = MyType {
k: 17,
my: Some("Some string".to_string()),
};
session
.query("INSERT INTO ks.my_type (k, my) VALUES (?, ?)", to_insert)
.await
.unwrap();
```
Fixes https://github.com/scylladb/scylla-rust-driver/issues/231

Add ValueList derive macro

---

scylla/src/frame/request/batch.rs
scylla/src/frame/request/query.rs
scylla/src/statement/batch.rs
scylla/src/statement/mod.rs
scylla/src/statement/prepared_statement.rs
scylla/src/statement/query.rs
scylla/src/transport/connection.rs
scylla/src/transport/session_test.rs

This pull request adds support for specifying client-side timestamps for a given query.
```rust
let mut regular_query = Query::new(query_str.to_string());
regular_query.set_timestamp(Some(42));
session.query(regular_query, (,)).await?;
```
Refs: #262 (not saying fixes, because issue is resolved partially - there are no generators implemented, only programmatically setting the timestamp for queries)

Client-side timestamps

---

scylla/src/frame/cql_collections_test.rs
scylla/src/frame/response/cql_to_rust.rs
scylla/src/frame/response/result.rs

It turnes out, that Scylla/Cassandra allows for `NULL` values as tuple elements. Our declaration of `CqlValue` (`Vec<CqlValue>`) lacks support for this, so any attempts to parse a response that contains tuple with `NULL` element result in error.
This PR changes tuple's representation to `Vec<Option<CqlValue>>`.
Fixes: #321

Fix `CqlValue`'s tuple representation

---

examples/auth.rs

This PR is just to remove redudant import from crate:: when use:scylla is already present in auth.rs.

remove crate:: when use is already present

---

docs/source/SUMMARY.md
docs/source/queries/lwt.md
docs/source/queries/queries.md
examples/tracing.rs
scylla/src/frame/request/batch.rs
scylla/src/frame/request/query.rs
scylla/src/frame/types.rs
scylla/src/statement/batch.rs
scylla/src/statement/mod.rs
scylla/src/statement/prepared_statement.rs
scylla/src/statement/query.rs
scylla/src/transport/session.rs

This series adds a default serial consistency level for queries - `LocalSerial`. The decision is based on the fact that `LocalSerial` is the one that provides acceptable performance. Users interested in strong, cross-dc consistency - which could also cause prohibitive latencies - should override to `Local`.
The series also comes with a doc entry which briefly explains LWT queries (they weren't mentioned at all so far), as well as an extra validation layer which would prevent users from setting a wrong consistency level, without introducing any backward incompatible changes.
This series introduces a breaking change - serial consistency is now defined as a separate enum. Fixing the existing aplications is trivial and consists of replacing all occurrences of `Consistency::LocalSerial` to …

Add a default value for serial consistency: LocalSerial

---

.github/workflows/cassandra.yml
scylla/src/frame/cql_types_test.rs

This series amends the test to work with Cassandra 4 and drops the workaround in our continuous integration, which used Cassandra 3.11 until the issues were resolved.
Fixes #280

Restore using latest cassandra image for CI

---

scylla/src/transport/topology.rs

this patch handles shorter topology names, otherwise the
strategy is considered as `Other` and the default behavior in this case with
a TokenAwarePolicy is to override RF to 1.
see https://github.com/scylladb/scylla-rust-driver/blob/main/scylla/src/transport/load_balancing/token_aware.rs#L128-L132 and https://docs.scylladb.com/getting-started/ddl/#create-keyspace-statement

scylla/transport/topology: accept shorter topology names

---

scylla/Cargo.toml
scylla/src/transport/topology.rs

At the time when the logic responsible for querying keyspace metadata
was implemented, there was no support for map datatypes, which was
needed to parse the `replication` parameters of a keyspace. To work
around that, the `toJson` function was used so that Scylla returns the
parameters encoded as a JSON string. The serde_json library was added to
dependencies solely for the purpose of parsing the encoded json map.
Support for direct deserialization of map types has been merged some
time ago, so there is no need to involve JSON as an intermediate step.
This commit removes the logic responsible for parsing the `replication`
map from JSON representation and now the map is parsed directly from its
CQL representation. Additionally, the serde_json crate is removed from
dependencies.

topology: drop the serde_json dependency

---

docs/source/queries/batch.md
docs/source/queries/paged.md
docs/source/queries/prepared.md
docs/source/queries/simple.md
docs/source/retry-policy/default.md
docs/source/retry-policy/fallthrough.md
docs/source/retry-policy/retry-policy.md
docs/source/tracing/paged.md
docs/source/tracing/prepare.md
docs/source/tracing/simple-prepared.md
examples/select-paging.rs
examples/tracing.rs
scylla/src/statement/query.rs
scylla/src/transport/connection.rs
scylla/src/transport/session.rs
scylla/src/transport/session_test.rs
scylla/src/transport/topology.rs

This PR adds new methods: `query_all` and `execute_all`.  
They use multiple paged queries to fetch results, and then merge all those results into one.  
`page_size` must be set on the query that is passed to those methods.
Currently we use a single unpaged query to fetch data, but this might cause stalls (#298).
It's better to use many smaller queries and merge results locally.
```rust
Connection::query_all(
&self,
query: &Query,
values: impl ValueList,
) -> Result<QueryResult, QueryError>;
Connection::execute_all(
&self,
prepared_statement: &PreparedStatement,
values: impl ValueList,
) -> Result<QueryResult, QueryError>;
```
Fixes: #298

Add a method to query data using multiple paged queries

---

scylla/Cargo.toml
scylla/src/transport/connection.rs

This pull request combines a couple of changes made in order to measure their impact on overall performance in various environments. The changes include:
* increasing the internal channel size in the connection router
* adding a buffering layer to reads
* adding a buffering layer to writes
NOTICE: write buffering is done via `BufWriter`
due to the fact that Tokio does not yet expose write_all_vectored,
and its implementation of write_vectored does not fit our needs,
because it basically just sends one buffer at a time anyway.
Once write_all_vectored is solved, write buffering can be
simplified, and memory copying can be elided.
Experiments show the following improvements:
* local write workload to Apache Cassandra 4.0 is able to achieve 200kops for a single connection, compared to 70kops …

Improve I/O performance via buffering

---

scylla/src/statement/prepared_statement.rs
scylla/src/transport/connection.rs
scylla/src/transport/session_test.rs

When preparing a statement based on a Query instance, we should
preserve the whole configuration. It's especially important
for CachingSession users, because prepare() happens implicitly
in this case, so there's no other way to customize the configuration
for a particular query.
Fixes #340

statement: preserve query configuration during prepare()

---

scylla/src/frame/types.rs
scylla/src/transport/session.rs

Originally the default consistency level was QUORUM,
but it might be detrimental to performance on multi-dc clusters.
Let's switch the default to LOCAL_QUORUM, which also has an additional
benefit of making the driver work out-of-the-box for Amazon Keyspaces,
which does not allow QUORUM consistency level.

frame,transport: change default consistency to LocalQuorum

---

docs/source/queries/prepared.md

PR #347 accidentally removed some newlines from the documentation.
Add them back to make the documentation look nicer.
Before:
After:

docs: Add back newlines that were removed in PR #347

---

docs/source/connecting/tls.md
docs/source/queries/batch.md
docs/source/queries/lwt.md
docs/source/queries/simple.md
docs/source/quickstart/create-project.md

Documentation book referenced scylla in version 0.2.0, but 0.3.1 is already out.
Changed all references from 0.2.0 to 0.3.1.
Fixes: #345

book: Update scylla version to 0.3.1

---

docs/source/data-types/collections.md
scylla/src/frame/cql_collections_test.rs
scylla/src/frame/response/cql_to_rust.rs
scylla/src/frame/value.rs

This PR adds full support for using `HashSet`, `BTreeSet` and `BTreeMap` with the driver.
`HashSet` already had a `FromCqlVal` implementation, but it didn't have `Value`.
I rewrote `cql_collections_test` a bit to cover all these added types.
Fixes: #344

Support more collection types

---

.github/workflows/cassandra.yml
scylla/Cargo.toml
scylla/src/transport/cluster.rs
scylla/src/transport/load_balancing/mod.rs
scylla/src/transport/load_balancing/token_aware.rs
scylla/src/transport/mod.rs
scylla/src/transport/session.rs
scylla/src/transport/session_builder.rs
scylla/src/transport/session_test.rs
scylla/src/transport/topology.rs

This pull request introduces an insight into the schema of the cluster. From now on it is possible to access keyspace elements such as tables, their columns, types, kinds (regular, static, clustering, partition_key), ordering of partition key and clustering columns, UDTs, partitioner which are stored in `Metadata` structure (former `TopologyInfo`). The client has a way to disable this feature using a proper flag in `SessionConfig`.
This pull request introduces new external dependency namely strum.
Fixes: #346

Expose schema metadata

---

examples/tracing.rs

Tracing info used to be printed in its debug form,
which isn't very human readable. The new format shows
the output as a table:
```
Tracing command QUERY performed by Some(127.0.0.1), which took 375ms total
│  UUID   │ Elapsed  │ Command
├─────────┼──────────┼──────────────────
│6caa2aa9 │      0ms │ Parsing a statement
│6caa2f0a │    112ms │ Processing a statement
│6caa30f2 │    161ms │ read_data: querying locally
│6caa3136 │    168ms │ Start querying token range (-inf, {minimum token, end}]
│6caa322c │    193ms │ Creating shard reader on shard: 0
│6caa32ce │    209ms │ Scanning cache for range (-inf, {minimum token, end}] and slice {(-inf, +inf)}
│6caa341b │    242ms │ Page stats: 0 partition(s), 0 static row(s) (0 live, 0 dead), 0 clustering row(s) (0 live, 0 dead) and 0 range …
```

examples: make tracing info human-readable

---

scylla/src/frame/response/error.rs
scylla/src/frame/types.rs
scylla/src/transport/errors.rs
scylla/src/transport/iterator.rs
scylla/src/transport/retry_policy.rs
scylla/src/transport/session.rs

Commit bff127f introduced a regression while splitting consistency
enum into Consistency and SerialConsistency. Namely, our driver
lost the ability to parse SerialConsistency returned as an error
from CQL. The ability is now restored by wrapping the result
in an enum - LegacyConsistency, capable of representing both regular
and serial consistency values.
Fixes #369

Allow SerialConsistency to be parsed from CQL errors

---

scylla/src/transport/mod.rs
scylla/src/transport/topology.rs

Schema metadata exposed in #349 was not public, so the structures defined there couldn't be used outside of the crate. Now all structures representing metadata are public, except for the `MetadataReader`.

Make Topology module public.

---

scylla/src/frame/response/error.rs
scylla/src/frame/types.rs
scylla/src/transport/caching_session.rs
scylla/src/transport/connection.rs
scylla/src/transport/errors.rs
scylla/src/transport/retry_policy.rs
scylla/src/transport/session_test.rs

This PR does 2 things: 
1. Changes the `DbError::Unprepared` enum to include the statement ID that was found to not be prepared. 
2. In the `batch` execution function, if a prepared statement comes back as unprepared, it reprepares that query. This happens in a loop so that if multiple queries are not prepared, it will reprepare all of them. Theoretically you could end up in an infinite loop if for some reason the prepared query get immediately evicted before the query is executed again; however this is roughly the same behavior the [gocql](https://github.com/gocql/gocql) driver would have if that Scylla server acted maliciously. 
*WRT Tests*: I'm not sure how to write this test; as it would somehow involve evicted the prepared query in the Scylla database.
Fixes #342

Repreprare evicted statements in batch queries.

---

.github/workflows/rust.yml
scylla/src/transport/caching_session.rs
scylla/src/transport/session_test.rs

This miniseries restores clippy checks for our tests.
Tests were excluded from clippy checks a while ago due to
ridiculous warnings, but these seem to be gone now with a new
clippy version. Hence, let's restore the additional checks.

Restore clippy tests

---

docs/source/queries/values.md
scylla/src/frame/request/query.rs
scylla/src/frame/types.rs
scylla/src/frame/value.rs
scylla/src/transport/session_test.rs

This commit adds support for CQL named bind markers,
i.e. markers in a form of ":name_here" instead of customary "?".
Named markers are not recommended due to the fact that they induce
more overhead than unnamed ones, but it's still part of the CQL
protocol, so we should support them.
Fixes #360

Add support for named bind markers

---

.github/workflows/rust.yml
scylla/src/frame/cql_collections_test.rs
scylla/src/frame/cql_types_test.rs
scylla/src/frame/value_tests.rs
scylla/src/transport/authenticate_test.rs
scylla/src/transport/caching_session.rs
scylla/src/transport/connection.rs
scylla/src/transport/mod.rs
scylla/src/transport/session_builder.rs
scylla/src/transport/session_test.rs

By providing unique keyspace names, the test suite is now capable
of running with multiple threads. In other words, one no longer
has to pass `-- --test-threads 1` for the tests to pass.
This series also removes the now unneeded `-- --test-threads 1` from our CI workflow.

Allow multithreaded tests

---

scylla/src/frame/frame_errors.rs

Shadowing the actual error message with a static string is harmful,
let's just show the full original error instead.
Fixes #392

frame: make StdIoError transparent

---

README.md
docs/source/connecting/connecting.md
docs/source/metrics/metrics.md
docs/source/queries/prepared.md
docs/source/queries/queries.md
docs/source/queries/schema_agreement.md
docs/source/queries/simple.md
examples/basic.rs
examples/tls.rs
scylla/src/frame/value.rs
scylla/src/frame/value_tests.rs
scylla/src/lib.rs
scylla/src/routing.rs
scylla/src/transport/connection.rs
scylla/src/transport/errors.rs
scylla/src/transport/iterator.rs
scylla/src/transport/metrics.rs
scylla/src/transport/session.rs
scylla/src/transport/session_builder.rs
test/tls/scylla.yaml

Documentation, code comments and user reported messages contain some spelling typos to be fixed.

Fix spelling typos

---

.github/workflows/book.yml

The "Book" workflow uses a prebuilt Docker image "scylla-mdbook" which,
in addition to the usual Rust compilation tools, contains a `cargo
mdbook` command installed. The problem with this approach is that the
container should be rebuilt regularly in order to update the Rust
version within - however, nobody remembers to do that and after 10
months the compiler became so outdated that it no longer recognises some
of the newly introduced changes to the language.
This commit changes the "Book" workflow so that it bases on
`ubuntu-latest` which is updated regularly, and the `cargo mdbook` tool
is installed as the first step. Although this is extra work on each CI
run compared to the previous approach, it requires less maintenance and
is less likely to break in the future.

CI: don't use a prebuilt container in the "Book" workflow

---

scylla/src/frame/cql_types_test.rs
scylla/src/frame/response/result.rs
scylla/src/frame/value.rs

Serialization of CqlValue::Empty was implemented improperly. Instead of
writing a 4-byte zero integer, nothing was being written, as if the
empty value wasn't present at all in the value list. Now, it is
serialized as it should.

value: fix serialization of CqlValue::Empty

---

scylla/src/frame/value.rs

Adds the ability to serialize slices of `T: Value`. Used to prevent having to use `Vec<T>` and saves allocations.

Implement `Value` for `slice[T]`

---

README.md

Updated Rust Driver Docs link to https://rust-driver.docs.scylladb.com/stable/index.html

Update Rust Driver Docs link

---

scylla/src/transport/load_balancing/dc_aware_round_robin.rs
scylla/src/transport/load_balancing/mod.rs
scylla/src/transport/load_balancing/round_robin.rs
scylla/src/transport/load_balancing/token_aware.rs

This PR adds a load balancing fallback mechanism.
Fallback policies have to implement `FallbackPolicy` trait. They are very similar to load balancing policies, in fact every `LoadBalancingPolicy` implements `FallbackPolicy` implicitly.
Query plans produced by fallback policies are lazily chained to primary load balancing plans.
Fixes: #161

Load balancing fallback

---

scylla/src/lib.rs
scylla/src/transport/load_balancing/mod.rs
scylla/src/transport/session.rs

All occurrences of the old scyllabook link now point to official
driver docs.

treewide: replace all book links in the comments with rust driver docs links

---

scylla/src/frame/response/cql_to_rust.rs
scylla/src/frame/response/result.rs

Timestamps can already be serialized with an i64, so it's only
natural to allow deserializing them as an integer as well.
Fixes #419

frame: allow deserializing timestamps into i64

---

scylla/src/frame/response/cql_to_rust.rs

It's particularly useful in IntoUserType and FromUserType macros
to be able to express that a column has CQL Time type.
For that we need a wrapper, and a perfect candidate for that
is scylla::frame::value::Time, which is already a thin wrapper over
chrono::Duration. This patch simply implements FromCqlVal for this
struct, which will allow using it for serialization and deserialization.
Fixes #421

frame: allow using Time struct as CqlValue

---

examples/cql-time-types.rs
scylla/src/frame/cql_types_test.rs
scylla/src/frame/response/cql_to_rust.rs
scylla/src/frame/response/result.rs
scylla/src/frame/value.rs
scylla/src/frame/value_tests.rs
scylla/src/transport/session.rs

Methods such as `i64::max_value()` will get deprecated so we may as well get rid of them now - my IDE will be happier and `i64::MAX` is shorter anyway.

Refactor: change deprecating const methods ::max_value() and ::min_value() into type constants ::MAX and ::MIN respectively

---

.github/workflows/docs-links.yaml
.github/workflows/docs-pages.yaml
.github/workflows/docs-pr.yaml
docs/Makefile
docs/pyproject.toml
docs/source/conf.py

Related issue https://github.com/scylladb/sphinx-scylladb-theme/issues/395
ScyllaDB Sphinx Theme 1.2 is now released 🥳 
We’ve added automatic checks for broken links and introduced numerous UI updates.
You can read more about all notable changes [here](https://sphinx-theme.scylladb.com/stable/upgrade/CHANGELOG.html#march-2022).
1. Clone this PR. For more information, see [Cloning pull requests locally](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally).
2. Enter the docs folder, and run:
```
make preview
````
4. Open http://127.0.0.1:5500/ with your favorite browser. The doc should render without errors, and the version should be Sphinx Theme version (see the footer) must be ``1.2.x``:

docs: update theme 1.2

---

scylla/src/frame/response/cql_to_rust.rs

FromCqlVal implementation has been added to frame::value::Time in #422,
but frame::value::Timestamp should have been included too.

frame: allow using Timestamp struct as CqlValue

---

examples/Cargo.toml
examples/tower.rs

This commit provides a simple example on how to wrap a Scylla session
into a tower::Service, which gives such a session all the benefits
of tower - composability, universal API, etc.
The example provides a very trivial service which is only capable
of sending unprepared, parameterless queries, but it's educational
nonetheless. By implementing a service on top of CachingSession
wrapped with a list of parameters, a full-fledged service can be
easily implemented.
Refs #425

examples: add example tower::Service trait implementation

---

scylla/src/lib.rs
scylla/src/transport/topology.rs
scylla/src/utils/mod.rs
scylla/src/utils/parse.rs

The current cql type parser has some problems parsing more complex types - notably, nested maps. This PR rewrites the implementation into a recursive-descent parser which properly handles more complex cases.
Fixes: #437

topology: rewrite the cql type parser in the recursive-descent style

---

examples/Cargo.toml
scylla/Cargo.toml

What it says on the cover.
- Bumps `uuid` version to 1.0.0 (which may break downstream code due to mismatching versions, but doesn't break the API).
- Bumps `dashmap` for relevant speedups.

Bump `uuid` and `dashmap` dependencies.

---

scylla/Cargo.toml
scylla/src/frame/response/result.rs
scylla/src/statement/prepared_statement.rs

In PreparedMetadata initialization, PK indexes are associated to their
sequence number, and then sorted by the index value. It allows iterating on
bounded_values in order, because indexes can then be reordered thanks to
sequence number.
Also, buf size is computed during iteration in order to be reserved before
writing to it, preventing buffer reallocation at each write.
Last but not least, an array is used instead of a vector when the size of
pk_indexes is not too big, saving the allocation cost.
Quick benchmark using `complex_pk` table of `test_prepared_statement` shows a
performance improvement from 200ns to at 130ns.
- [ x] I have split my patch into logically separate commits.
- [ x] All commit messages clearly explain what they change and why.
- [ x] I added relevant tests for new …

Optimize PreparedStatement::compute_partition_key

---

.github/workflows/rust.yml

As we are about to declare 1.59 as our minimum supported rust version,
this commit introduces a CI check that will help us enforce it. It runs
the `cargo check` command using the MSRV toolchain and verifies that it
passes with and without features enabled.
The check was inspired by tokio's CI configuration.
Refs: #444

CI: check compilation with MSRV

---

scylla/src/statement/prepared_statement.rs

After preparing a statement the database returns a bunch of metadata information that is kept in `PreparedStatement`.
This data isn't normally used by users of the driver so it's private.
While it might not be useful to regular users I was just debugging a problem with Scylla and needed to access it.
Let's make it accessible from outside to make life easier for database developers who use this driver.

Allow to access PreparedMetadata

---

docs/book.toml
examples/Cargo.toml
scylla-macros/Cargo.toml
scylla/Cargo.toml

Rust edition 2021 has some nice features, for example arrays got an `into_iter()` implementation, which means that we can do things like:
```rust
let my_set: BTreeSet<String> = [
"doggie".to_string(),
"doge".to_string(),
"doggo".to_string(),
]
.into_iter()
.collect();
```
Updating to 2021 shouldn't cause any issues. According to the documentation crates with edition 2018 can still use our crate, even if it's in edition 2021:
https://doc.rust-lang.org/nightly/edition-guide/editions/index.html
> This ensures that the decision to migrate to a newer edition is a "private one" that the crate can make without affecting others.

Switch to Rust edition 2021

---

scylla/src/statement/prepared_statement.rs
scylla/src/transport/iterator.rs
scylla/src/transport/session.rs

Not all prepared statements can be routed in a token-aware manner.
Sometimes the token cannot be computed by the driver based on the bound
query values - if this is the case, PREPARE will return metadata with
empty pk_index (which tells the driver how to compute the token).
However, the driver interprets empty pk_index as valid information and
computes a dummy token which is then used to route the statement to the
same node/shard every time.
This commit changes the execute logic so that it detects when the
prepared statement has empty pk_index and routes it in the same way as
unprepared queries.
Tested by modifying the `parallel-prepared` test so that it does not have bind markers in partition key, running it and observing the request distribution in metrics.
Fixes: #453

session: route prepared queries without pk index like unprepared queries

---

examples/Cargo.toml
examples/allocations.rs

The new example program, allocations.rs, counts how many
allocations, reallocations and frees were submitted
per request during our write path and read path, based on
prepared statements.
This example can be used to track potential performance regressions.
Example output:
```
[sarna@localhost scylla-rust-driver]$ cargo run --release --example allocations
Finished release [optimized] target(s) in 0.07s
Running `target/release/examples/allocations`
Args { mode: All, node: "127.0.0.1:9042", parallelism: 256, requests: 100000 }
Connecting to 127.0.0.1:9042 ...
Sending 100000 inserts, hold tight ..........
----------
Inserts:
----------
allocs/req:                15.01
reallocs/req:               9.00
frees/req:                 15.01
bytes allocated/req:     3496.39
bytes reallocated/req: …
```

examples: add an example with allocation stats

---

scylla/src/transport/connection.rs
scylla/src/transport/session.rs
scylla/src/transport/session_builder.rs

Now, the session automatically waits for schema agreement after
executing a statement which modifies the schema. The rationale for this
change is that, previously, it was the user's responsibility to wait for
schema agreement and it was easy to forget about this check.
The automatic wait for schema agreement is never a bug, although it can
slow down some programs which do a lot of schema changes in a short
succession. Those applications can opt-out of this feature by disabling
the feature in the configuration and can still wait for schema agreement
manually.
The session will wait for schema agreement for a configured amount of
time, and then - if the agreement is not reached - it will return
a TimeoutError.
Fixes: #459

session: automatically wait for schema agreement

---

scylla/Cargo.toml
scylla/src/transport/caching_session.rs
scylla/src/transport/connection.rs
scylla/src/transport/session_test.rs

Sometimes the prepared statement cache gets cleared and we need to prepare a `PreparedStatement` again.
This happens e.g. after `ALTER TABLE` where a column might change its name.
In such cases `Session` automatically reprepares the `PreparedStatement` under the hood. This happens in `Connection::execute` and `Connection::batch`.
`CachingSession` should also handle such cases automatically. It has some code that is supposed to handle them, but it isn't actually needed. Even if it weren't there `Session` would handle repreparing everything,
This PR first adds tests which ensure that repreparation works correctly in `Session` and `CachingSession`, and then removes repreparation code from `CachingSession`. After removal the tests still pass.
This affects #469, implementing …

Remove reprepare code from CachingSession, add reprepare tests

---

scylla/Cargo.toml
scylla/src/transport/cluster.rs
scylla/src/transport/load_balancing/dc_aware_round_robin.rs
scylla/src/transport/load_balancing/mod.rs
scylla/src/transport/load_balancing/round_robin.rs
scylla/src/transport/load_balancing/token_aware.rs
scylla/src/transport/node.rs
scylla/src/transport/session.rs
scylla/src/transport/session_builder.rs
scylla/src/transport/topology.rs

Added AddressTranslator trait and an ability to provide a struct
implementing it to the session builder. When done so, every address
fetched as cluster metadata will be translated using the rules defined
by the trait implementor.
The reasons are described in the related issue.
Reverts: #173
Fixes #470

Optional address translation added

---

scylla/src/transport/topology.rs

When fetching node addresses from system tables, `peer` column
is not the right choice - the address available for clients
is generally stored in `rpc_address` column.
Technically, a full solution should also fetch `broadcast_rpc_address`
and use it if `rpc_address` is incorrect or set to 0.0.0.0,
but this quick fix is enough to work for most configurations.

topology: use rpc_address instead of peer when fetching addrs

---

.github/workflows/rust.yml
test/docker-compose.yml

As it enables testing more sophisticated scenarios such as retries
and speculative executions, we made the cluster in CI consist
of 3 nodes. The existing tests pass seamlessly on such cluster.

Enhanced CI cluster: now 3-node instead of 1-node

---

scylla/benches/benchmark.rs

One value was not unwrapped, and the compiler has been warning
about unused result while checking target benchmarks.

Removed warning in benchmarks

---

scylla-cql/src/frame/frame_errors.rs
scylla-cql/src/frame/request/auth_response.rs
scylla-cql/src/frame/response/event.rs
scylla-cql/src/frame/response/result.rs
scylla-cql/src/frame/server_event_type.rs
scylla-cql/src/frame/types.rs

As described in the related issue, serialization and deserialization
error were both covered by one ParseError variant, which caused
misleading messages. Now, there are separate variants for both cases.
Fixes:  #478

Splitted "BadData" into ser/deser separately

---

.github/workflows/rust.yml
Cargo.toml
scylla-cql/Cargo.toml

Contrary to previous assumptions, tokio feature "io-util" is required
for `scylla-cql` crate to build. Moreover, I added the new crate
to Cargo workspace.

Fixed missing tokio feature in scylla-cql

---

scylla/Cargo.toml
scylla/src/lib.rs

By default docs.rs builds crates with all features disabled, this results in the ssl methods not being included in places such as: https://docs.rs/scylla/latest/scylla/transport/session_builder/struct.SessionBuilder.html
To resolve this we set docs.rs metadata as documented here: https://docs.rs/about/metadata
Additionally we use `#![cfg_attr(docsrs, feature(doc_auto_cfg))]` to make use of https://doc.rust-lang.org/beta/unstable-book/language-features/doc-auto-cfg.html which is what gives us the nice "only available on..." badge underneath:
You can use the command: `RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features` to test the changes locally.

Include ssl functions on docs.rs

---

scylla/src/statement/prepared_statement.rs

As cloning a vector of tracing ids while cloning a `PreparedStatement` is redundant and conflicts with the general rule that cloning should be cheap, we drop it.
Fixes: #504

Made PreparedStatement drop tracing ids on clone

---

.github/workflows/cassandra.yml
scylla/src/transport/load_balancing/token_aware.rs
scylla/src/transport/session_test.rs
scylla/src/transport/topology.rs

In order to keep information about materialized views too,
system_schema.views system table is queried, instead of fetching
the info only from system_schema.tables.
Fixes #506

Pull materialized view information when fetching schema

---

examples/custom_load_balancing_policy.rs
scylla/src/transport/caching_session.rs
scylla/src/transport/cluster.rs
scylla/src/transport/connection_pool.rs
scylla/src/transport/load_balancing/dc_aware_round_robin.rs
scylla/src/transport/load_balancing/mod.rs
scylla/src/transport/load_balancing/round_robin.rs
scylla/src/transport/load_balancing/token_aware.rs
scylla/src/transport/node.rs
scylla/src/transport/session.rs

Deriving Debug trait for Session may be useful in debugging. Cluster is omitted in the stringified Session, because it add lots of clutter and little useful information.
Fixes: #502

Made Session debuggable

---

scylla-cql/src/frame/response/mod.rs
scylla/src/transport/connection.rs
scylla/src/transport/session.rs

This is an alternative to #510.
`run_query` takes as a paramter a closure used to run a single query ona connection.
Result of such a query is `Result<ResT, QueryResult>`.
In Case of Result::Err the retry policy decides whether to retry the query based on the error type.
There was a bug - in a few cases `ResT` was of type `QueryResponse`, which has an `Error` variant. Such errors weren't detected by `RetryPolicy` and were never retried.
This PR fixes the bug by making the closure return `NonErrorQueryResponse`. All errors will be collected in a single `QueryResult` and detected by `RetryPolicy`.
Additionally to prevent such mistakes from happening a new trait is introduced that defines which types can be used as `ResT` in `run_query`:
```rust
pub trait AllowedRunQueryResTType {}
impl …
```

Fix RetryPolicy not retrying on Response::Error

---

scylla/src/tracing.rs
scylla/src/transport/session_test.rs

Adds a simple getter which allows to get the list of nodes involved in a traced query.

tracing: Get list of nodes from  TracingInfo

---

.github/workflows/authenticate_test.yml
scylla-cql/Cargo.toml
scylla-cql/src/errors.rs
scylla/Cargo.toml
scylla/src/statement/mod.rs
scylla/src/statement/prepared_statement.rs
scylla/src/statement/query.rs
scylla/src/transport/session.rs
scylla/src/transport/session_builder.rs
scylla/src/transport/session_test.rs

Two levels of client-side timeouts were added: per Session and per Statement (PreparedStatement and Query). If no timeout is specified for a statement, a global per-session one is used. Once a timeout elapses, an `RequestTimeout` error is returned.
Fixes: #304

Implemented client-side per-session and per-statement configurable timeouts

---

docs/source/SUMMARY.md
docs/source/retry-policy/downgrading_consistency.md
docs/source/retry-policy/retry-policy.md
examples/Cargo.toml
scylla-cql/src/errors.rs
scylla/src/transport/connection.rs
scylla/src/transport/downgrading_consistency_retry_policy.rs
scylla/src/transport/iterator.rs
scylla/src/transport/mod.rs
scylla/src/transport/retry_policy.rs
scylla/src/transport/session.rs

`RetryPolicy` was extended to enable specifying consistency level with which the retry attempt is to be performed.
Then, the `DowngradingConsistencyPolicy` was added, and checked with new unit tests.
Fixes #503

Added DowngradingConsistencyPolicy

---

examples/compare-tokens.rs
scylla/src/transport/load_balancing/token_aware.rs
scylla/src/transport/session.rs

This commit allows users to make an educated guess on which replicas are going to take part in processing the query, assuming that the query in question has a well defined token. This information can be used for analytical and observability purposes. `estimate_replicas_for_query` simply returns a vector of nodes suspected of owning the data in question.

Allow estimating replicas for a query

---

scylla/src/transport/session_test.rs
scylla/src/transport/topology.rs

Added MaterlizedView struct to store base table name for a view.
This will allow to find all materialized views for a given table name, or find the base table metadata for a certain view.

Add separate struct for view metadata to store more info

---

scylla/src/transport/connection.rs

As reprepare logic was duplicated (in prepared statements and in
batches), I've extracted it as a separate function.

connection: Extracted repreparing as a method

---

docs/source/queries/batch.md
scylla/src/transport/caching_session.rs
scylla/src/transport/session.rs
scylla/src/transport/session_test.rs

This PR adds a `batch` method on `CachingSession` which allows it to execute batches.
The batch is taken by reference to stay consistent with `Session` and to make it possible not to copy batches that are already prepared.
Apart from that I also added a `prepare_batch` method to both `Session` and `CachingSession`. It's more convenient to create a batch and then prepare all statements within that it's to prepare each of them one by one. Both changes are in one PR because the code is very similar and it's easier to review both at once.
Fixes: #469, thanks to [colin-grapl](https://github.com/colin-grapl) for the initial code

Add batch support to CachingSession, Add Session::prepare_batch

---

scylla/Cargo.toml
scylla/src/transport/cluster.rs
scylla/src/transport/load_balancing/mod.rs
scylla/src/transport/load_balancing/token_aware.rs
scylla/src/transport/session.rs
scylla/src/transport/session_builder.rs
scylla/src/transport/topology.rs

To be consistent with other drivers' behaviour, as well as to mitigate the _possibly empty rpc_address_ problem, we turned off address translation for hosts that serve as metadata providers on current control connection. 
This re-reverts #471 and provides necessary fixes not to cause #487.
Fixes: #490 #487 #470

Address translation with exception for hosts on current control connection

---

scylla/src/transport/session.rs
scylla/src/transport/session_builder.rs
scylla/src/transport/session_test.rs

Fixes: #544 
Added refreshing schema metadata after reaching schema agreement after a
schema-changing query.

Session: refresh metadata on schema change 

---

scylla-cql/src/errors.rs
scylla-cql/src/frame/mod.rs
scylla-cql/src/frame/protocol_features.rs
scylla-cql/src/frame/response/error.rs
scylla-cql/src/frame/response/mod.rs
scylla/src/transport/connection.rs
scylla/src/transport/session_test.rs
scylla/src/utils/test_utils.rs

This PR adds support for a new Scylla-specific type of error returned from the database: RateLimitExceeded. It was introduced as a part of the _per-partition rate limit_ feature, upcoming in Scylla 5.1 (PR in Scylla: https://github.com/scylladb/scylladb/pull/9810). The RateLimitExceeded error is sent when Scylla detects that the per-partition rate limit is exceeded.
In order for Scylla to be able to send this error, the driver must tell the database during connection handshake that it is able to interpret it (otherwise Scylla falls back to the Config_error error). This PR adds support for Scylla-specific protocol extensions, negotiates the `SCYLLA_RATE_LIMIT_ERROR` during handshake and adds support for the RateLimitExceeded error deserialization.

Add support for rate limit exceeded exception

---

scylla/src/transport/load_balancing/mod.rs

The newest version of clippy complains that a lifetime can be elided in the `slice_rotated_left` function. This commit removes the explicit lifetime and lets rustc infer it automatically.

transport/load_balancing: appease clippy

---

scylla-cql/src/frame/request/batch.rs
scylla-cql/src/frame/value.rs
scylla-cql/src/frame/value_tests.rs
scylla/src/transport/session.rs

Fixes: #448
Helps #468
To achieve this, it was useful to rework the BatchValues trait.
With this rework, it's also possible to pretty easily provide cloneable `Iterator`s over `ValueList` as `BatchValues` (through `BatchValuesFromIterator`) - so #499 may get closed if this gets merged (or this PR will require update if #499 gets merged before).

Pick connections based on batch first statement's shard

---

scylla-cql/src/frame/request/batch.rs
scylla-cql/src/frame/value.rs
scylla-cql/src/frame/value_tests.rs
scylla/src/transport/session.rs
scylla/src/transport/session_test.rs

The new code, and in particualr the fancy GAT workaroound, cause problems when trying to pass batch values by reference, as described in #568.
Fixes: #568
Unfixes: #448
This reverts commit 24ee9545774291607f591e2a4ad2ba1bbe7ab96e.

Revert "Pick connections based on batch first statement's shard"

---

scylla/src/lib.rs
scylla/src/transport/cluster.rs
scylla/src/transport/host_filter.rs
scylla/src/transport/load_balancing/mod.rs
scylla/src/transport/load_balancing/token_aware.rs
scylla/src/transport/mod.rs
scylla/src/transport/node.rs
scylla/src/transport/session.rs
scylla/src/transport/session_builder.rs
scylla/src/transport/topology.rs

This PR adds host filters. With host filters, it is possible to prevent some nodes from establishing connections to the cluster at all. For example, the set of nodes for which connections are allowed can be restricted to the local DC.
Tested manually with cql-stress and a 3 node cluster - applied an allowlist of nodes and observed in metrics that forbidden nodes do not have additional connections and do not receive any requests.
Fixes: https://github.com/scylladb/scylla-rust-driver/issues/561

Host filter

---

scylla/Cargo.toml
scylla/src/transport/caching_session.rs

This is a minimal version of a PR I had tried to push through a while back. It's very small and straightforward, and avoids some of the additional APIs I had provided in the last PR. In short, the `CachingSession` now has a 3rd type parameter, `S`, which will be used to customize the hash algorithm used by DashMap.
There are lots of benchmarks for other hash algorithms, such as these:
https://github.com/rust-lang/hashbrown#performance
https://github.com/tkaitchuck/aHash/blob/master/compare/readme.md#why-use-ahash-over-x
As you can see from those benchmarks there are significantly faster algorithms than what rust provides by default.
I don't think there are any "Fixes" annotations to apply here.

Minimal implementation of custom hasher for CachingSession

---

scylla/src/transport/iterator.rs
scylla/src/transport/load_balancing/dc_aware_round_robin.rs
scylla/src/transport/load_balancing/latency_aware.rs
scylla/src/transport/load_balancing/mod.rs
scylla/src/transport/load_balancing/round_robin.rs
scylla/src/transport/load_balancing/token_aware.rs
scylla/src/transport/node.rs
scylla/src/transport/session.rs

A LatencyAware load balancing policy, similar to what other drivers deliver, was added. Its goal is to avoid slow nodes as coordinators.
If a policy requests that latency statistics be collected, then an exponential moving average of latencies will be updated for a node upon query completion with that node serving as coordinator.
Fixes: #515 #505 #260

Latency aware policy

---

scylla/src/history.rs
scylla/src/transport/downgrading_consistency_retry_policy.rs
scylla/src/transport/iterator.rs
scylla/src/transport/retry_policy.rs
scylla/src/transport/session.rs

RetryDecision contains Option<Consistency> now instead of Consistency. None conveys meaning of "retry with the same CL as before", which is especially suitable when the previous consistency was Serial (even though such a case seems to be impossible in the code ATM). Moreover, covered one special case of LWT Unavailable error in DowngradingConsistencyPolicy, mirroring Java driver's behaviour.
Fixes: #527

retry_policy: Added support for SerialConsistency

---

scylla/src/transport/connection.rs

The CQL protocol allows the database to return some warnings along with the response and the driver prints them using the tracing::warn! macro. Those warnings, when reported by tracing, may be confused with a driver-side error, so this commit attempts to make it more clear that the warning was generated on the db-side.

connection: clearly mark db-side warnings as such

---

scylla-cql/src/frame/value.rs
scylla/src/transport/session_test.rs

The new test demonstrates the new types that are now possible to provide.
Supporting `Vec<&dyn Value>` and `Vec<Box<dyn Value>>` here is very rarely useful but I ran into a case where I needed it for abstracting across multiple cassandra drivers in order to easily test my cassandra proxy implementation across multiple drivers.

Implement Value for Vec<&dyn Value> and Vec<Box<dyn Value>>

---

examples/value_list.rs
scylla-macros/src/from_row.rs
scylla-macros/src/from_user_type.rs
scylla-macros/src/into_user_type.rs
scylla-macros/src/parser.rs
scylla-macros/src/value_list.rs

Derives were written without using the dedicated [`item.generics.split_for_impl()`](https://docs.rs/syn/latest/syn/struct.Generics.html#method.split_for_impl) which resulted in them not working as soon as the struct contained generics. Notably, it was impossible to derive `ValueList` on a struct that contained an `&str`, forcing the user to reallocate.

Fix derives so that they work with generics

---

docs/source/data-types/date.md
examples/cql-time-types.rs
scylla-cql/src/frame/response/cql_to_rust.rs
scylla-cql/src/frame/response/result.rs
scylla-cql/src/frame/value.rs
scylla-cql/src/frame/value_tests.rs
scylla/src/history.rs
scylla/src/transport/cql_types_test.rs

The functions `NaiveData::from_ymd` and `from_hms` have been deprecated. This causes the CI to fail
during clippy check.
(see https://github.com/scylladb/scylla-rust-driver/actions/runs/3462054587/jobs/5780445658)
Change all occurences of `from_ymd` and `from_hms` to `from_ymd_opt` and `from_hms_opt`.
The `_opt` variant requires adding an `unwrap()`, but this doesn't decrease safety.
In all cases where there is an `unwrap()` the old code would've panicked.

Remove uses of deprecated NaiveData::from_ymd/hms

---

Makefile

Running `make build` is too verbose to use it as a convenient `cargo build` replacement. Removing `--verbose` flag helps a lot - the terminal is not flooded with messages about which compiler flags are being used etc.

make: do not use --verbose flag with cargo build

---

scylla-cql/src/errors.rs
scylla-cql/src/frame/request/batch.rs
scylla-cql/src/frame/value.rs
scylla-cql/src/frame/value_tests.rs
scylla/src/transport/connection.rs
scylla/src/transport/downgrading_consistency_retry_policy.rs
scylla/src/transport/retry_policy.rs
scylla/src/transport/session.rs

Fixes #448 
Follow-up on #508 being reverted in #569 because of #568 - first commit reintroduces #508, while second commit fixes #568.
-> This re-fixes #448, without reintroducing #568.
#568 is effectively fixed by using default generic argument on the `BatchValuesGatWorkaround` trait which will generate an implicit  `where Self: 'r` bound in `for<'r> BatchValuesGatWorkaround<'r>` (becoming in effect `for<'r where Self: 'r> BatchValuesGatWorkaround<'r>`). This trick is explained in more detail at https://sabrinajewson.org/blog/the-better-alternative-to-lifetime-gats.
We also get rid of lending iteration in `BatchValuesIterator`, giving more flexibility for future shard-pick heuristic improvements (this is also unlocked by that same implicit bound).
--
Update: c7f7640 now also moves to the …

Pick connections based on batch first statement's shard - v2

---

scylla/src/statement/prepared_statement.rs
scylla/src/transport/caching_session.rs
scylla/src/transport/session.rs

Currently, the CachingSession keeps full PreparedStatement objects in its cache. When calling CachingSession::execute etc., a full Query object is provided. If the query is not in the cache, then Session::prepare is called and the resulting query - which inherits parameters like paging size, consistency etc. - is inserted into the cache. If the query is already in the cache, then the original PreparedStatement which was inserted into the cache is returned - and that prepared statement may have different parameters than the Query passed as a parameter.
This PR modifies the CachingSession so that it only keeps essential information necessary to create a PreparedStatement from a Query, i.e. ID of the query and prepared statement metadata. All other parameters are inherited from the Query …

caching_session: always inherit params from provided Query object 

---

scylla/src/transport/caching_session.rs
scylla/src/transport/session_test.rs

Running clippy 0.1.60 on our code results in a set of warnings about our `sort` usage:
```
error: used `sort` on primitive type `tuple`
--> scylla/src/transport/caching_session.rs:564:9
|
564 |         rows.sort();
|         ^^^^^^^^^^^ help: try: `rows.sort_unstable()`
|
= note: `-D clippy::stable-sort-primitive` implied by `-D warnings`
= note: an unstable sort would perform faster without any observable difference for this data type
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#stable_sort_primitive
...
```
This pull request applies the above suggestions .

transport: fix clippy warnings

---

.github/workflows/cassandra.yml
scylla-proxy/src/actions.rs
scylla-proxy/src/frame.rs
scylla-proxy/src/proxy.rs
scylla/src/transport/connection.rs
scylla/src/transport/cql_types_test.rs
scylla/src/transport/session_test.rs
scylla/tests/retries.rs
test/cluster/cassandra/docker-compose.yml

I've made our CI Cassandra cluster consist of 3 nodes (instead of only 1). This will let us test freely on both C* and Scylla in case that the test assumes 3 nodes present; we will no longer have to opt those tests out for C*.
Moveover, I've made several improvements to proxy:
- rule changing is no longer async
- Reaction prettier printing
- Support frames can be conveniently forged
- ShardAwareness::QueryNode falls back to Unaware in case of shard info not present at node

Cassandra 3 nodes CI & proxy features enhancements

---

.github/workflows/authenticate_test.yml
docs/source/connecting/authentication.md
scylla-cql/Cargo.toml
scylla-cql/src/frame/mod.rs
scylla-cql/src/frame/request/auth_response.rs
scylla-cql/src/frame/types.rs
scylla/src/authentication/mod.rs
scylla/src/lib.rs
scylla/src/transport/authenticate_test.rs
scylla/src/transport/connection.rs
scylla/src/transport/session.rs
scylla/src/transport/session_builder.rs

Added AuthenticatorProvider and AuthenticatorSession traits. AuthenticatorProvider serves as a factory to create a new AuthenticatorSession instance for each session.
AuthenticatorSession trait has 3 methods to be implemented by a user:
* initial_response: to initiate a request to begin an authentication exchange. Resources required for this specific exchange can be stored in the struct implementing AuthenticatorSession trait.
* evaluate_challenge: to handle an authentication challenge initiated by the server. The information contained in the token parameter is authentication protocol specific. It may be NULL or empty.
* success: to handle the success phase of exchange. The token parameters contain information that may be used to finalize the request.
Fixes #562

Add support for custom authentication

---

examples/compare-tokens.rs
scylla-cql/src/frame/protocol_features.rs
scylla-cql/src/frame/response/result.rs
scylla/src/lib.rs
scylla/src/statement/prepared_statement.rs
scylla/src/transport/caching_session.rs
scylla/src/transport/connection.rs
scylla/src/transport/iterator.rs
scylla/src/transport/load_balancing/latency_aware.rs
scylla/src/transport/load_balancing/mod.rs
scylla/src/transport/load_balancing/token_aware.rs
scylla/src/transport/session.rs
scylla/src/utils/mod.rs
scylla/src/utils/test_utils.rs
scylla/tests/lwt_optimisation.rs
scylla/tests/retries.rs
scylla/tests/utils/mod.rs

This enables optimisation of LWT queries routing. If the cluster supports the LWT mark protocol extension, then it will be negotiated and henceforth prepared statements which contain an LWT will be routed to the replicas only.
Fixes: #100

LWT routing optimisation

---

scylla/src/transport/connection.rs

When sending a `STARTUP` message while establishing the connection, this change properly populates the `DRIVER_VERSION` field.
Before this change, `SELECT * FROM system.clients` would allow a user to see that Scylla Rust Driver has connected to the cluster, but the version number was `null`.
The version number is fetched compile-time by invoking option_env! and reading a standard `CARGO_PKG_VERSION` environment variable.
Example contents of system.clients after change:
```
>> `select driver_name, driver_version from system.clients;`
| Text("scylla-rust-driver")| Text("0.6.1")   |
| Text("scylla-rust-driver")| Text("0.6.1")   |
```
Fixes #610

connection: send DRIVER_VERSION in STARTUP message

---

examples/Cargo.toml
examples/custom_deserialization.rs
scylla-cql/src/frame/response/cql_to_rust.rs
scylla-cql/src/macros.rs

This commit exposes the existing `impl_from_cql_val` macro as `impl_from_cql_value_from_method` macro. It was originally used to define implementations of the FromCqlValue macro based on CqlValue's existing methods, but it can be useful outside the crate itself too - namely, users can define more methods for CqlValue via extension traits.

cql_to_rust: expose impl_from_cql_value_from_method macro

---

scylla-cql/Cargo.toml
scylla-cql/src/frame/response/cql_to_rust.rs
scylla-cql/src/frame/value.rs
scylla-cql/src/frame/value_tests.rs

Implement FromCqlVal and Value for DateTime<Utc> and secrecy::Secret.

Add serialize and deserialize support for DateTime<Utc> and secret

---

.github/workflows/rust.yml
README.md

Bumping MSRV due to those reasons:
- The newest version of tokio (1.24.1) doesn't seem to compile with Rust 1.59 and `-D warnings`. Fortunately, 1.65 doesn't seem to be affected.
- #596 needs GATs, which were introduced in 1.65
- #614 would like to use the new `dep:` syntax for optional features.
The version 1.65 is also not the newest, released about 2.5 months ago since the time this commit message was written. Although our MSRV policy allows us to bump MSRV in major releases - and I understand going from 0.x to 0.(x+1) as such a change - choosing an older version has the benefit that, at the time of release of the next driver version, some of the users will probably already have migrated to a Rust version supported by the driver.

CI: bump MSRV to 1.65

---

scylla-cql/src/frame/response/cql_to_rust.rs
scylla-cql/src/frame/value.rs
scylla-proxy/src/actions.rs
scylla/src/transport/load_balancing/token_aware.rs

The new version of cargo doc started complaining about unescaped `<` and `>` signs because they looked like html tags. This commit gets rid of this complaint either by putting them into `backticks` if they are a part of some rust code mentioned in a docstring, or escaping them with a backslash in other cases.
Also contains a bonus commit that fixes one missed clippy lint.

treewide: appease cargo doc

---

test/cluster/cassandra/docker-compose.yml

The cassandra tests were run on the latest version of Cassandra 4.1.0 and most probably the version contains some bugs as some tests were flaky. This PR pins version 4.0.7 for creating a 3-node Cassandra cluster, which solves the flakiness problem, however, the root cause of the problem is still unknown.
Additionally, memory flags `HEAP_NEWSIZE=512M` and `MAX_HEAP_SIZE=2048M` are added for each node creation as the GitHub Actions Linux virtual machine has a RAM limit of 7GB.
Fixes: #620

Downgrade Cassandra version for CI

---

scylla-proxy/src/lib.rs
scylla-proxy/src/proxy.rs
scylla/src/transport/connection.rs
scylla/tests/lwt_optimisation.rs
scylla/tests/retries.rs
scylla/tests/utils/mod.rs

As tests are run concurrently on a single process, so addresses for proxy instances used in them can be assigned automatically in a non-colliding way. To this end, one atomic suffices.
Fixes: #586

Automated proxy addresses in tests

---

docs/source/SUMMARY.md
docs/source/data-types/data-types.md
docs/source/data-types/duration.md
scylla-cql/src/frame/response/cql_to_rust.rs

CqlDuration has de facto already been the Rust type mapping for the CQL type `duration`, but was missing a `from_cql` impl. This patch adds the missing impl and adds the type mapping to the documentation.
~~- [ ] I added appropriate `Fixes:` annotations to PR description.~~

data-types: add CqlDuration as the Rust equivalent of CQL Duration

---

scylla/Cargo.toml
scylla/src/transport/cluster.rs
scylla/src/transport/load_balancing/mod.rs
scylla/src/transport/load_balancing/token_aware.rs
scylla/src/transport/node.rs
scylla/src/transport/session.rs
scylla/src/transport/topology.rs

As a corresponding change has been merged into Scylla itself, we should adjust as well.
Moreover, for Serverless Cloud host IDs are the only valid way of identifying nodes.

Identify nodes by host id instead of IPs

---

scylla/Cargo.toml
scylla/src/transport/caching_session.rs

Currently, we are importing the `ahash` crate for only one reason: to test that CachingSession works with custom hasher implementations. The custom hasher quality doesn't matter at all in this test, so it's very easy to write own implementation for testing purposes, rendering the dependency on `ahash` obsolete.
The change was prompted by a report from one of our users which use a fork of the driver and managed to trigger a bug in cargo - most likely this one: https://github.com/rust-lang/cargo/issues/7463 . The most likely cause was that the project specified a different, non-compatible version of ahash in the dependencies than the one in scylla's dev-dependencies. While it doesn't fix the cargo bug and it can still happen with other dev-dependencies, the bug should no longer happen with …

caching_session: use custom hasher instead of ahash in tests

---

scylla-cql/src/frame/response/result.rs

In some cases (in particular, Scylla UDFs), the cql values are passed in a serialized form without the context of a row.
The current implementation of deser_cql_value function is already able to parse these values, so it can be just made public to be usable in those cases.
~- [ ] I added relevant tests for new features and bug fixes.~
~- [ ] I added appropriate `Fixes:` annotations to PR description.~

deserialization: make deser_cql_value public

---

.github/workflows/rust.yml
scylla-cql/Cargo.toml
scylla/Cargo.toml

First, secrecy is now built as `scylla-cql` dependency only if the corresponding feature is requested. Secondly, the corresponding feature that turns on the secrecy-related serialization has been added to scylla crate.

secrecy: Features and dependencies cleanup

---

examples/user-defined-type.rs
scylla-cql/src/lib.rs
scylla-macros/Cargo.toml
scylla-macros/src/from_row.rs
scylla-macros/src/from_user_type.rs
scylla-macros/src/into_user_type.rs
scylla-macros/src/lib.rs
scylla-macros/src/parser.rs
scylla-macros/src/value_list.rs
scylla/src/lib.rs
scylla/tests/hygiene.rs

While trying to make my macros at https://github.com/wmitros/scylla-rust-udf/pull/1 more hygienic, I noticed that I also need the macros here to be more hygienic.
I'm posting this mostly to find out if I'm heading in the right direction with the changes, although this patch does pass tests if it turns out being close to a state ready for merging
~~- [ ] I added appropriate `Fixes:` annotations to PR description.~~

scylla-macros: increase hygiene

---

.github/workflows/rust.yml
Makefile

New version of clippy introduced the `uninlined_format_args` lint which recommends putting variable names directly into format strings, like this:
let what = "world";
println!("Hello, {what}!");
// Instead of:
println!("Hello, {}!", what);
The problem with this feature is that rust-analyzer does not support renaming variables inside format strings yet. The lint has been downgraded to pedantic level and will most likely appear as such in the next release.
This commit disables the new lint in the CI and local Makefile. We can turn it on again after this feature gets better support from rust-analyzer.

CI/Makefile: disable `uninlined_format_args` clippy lint

---

scylla-cql/src/frame/response/cql_to_rust.rs

The driver supports serializing and deserializing between the `date` CQL type and the `chrono::NaiveDate` type. However, the `NaiveDate` type is not always sufficient as it can't represent the whole range of values the `date` CQL type can. For that purpose, we provide a `Date` type that is able to represent all CQL values of `date` type.
Until now, it was only possible to serialize `Date`. This commit adds a missing FromCqlValue impl necessary for deserialization.

cql_to_rust: impl FromCqlValue for Date

---

.github/workflows/cassandra.yml
.github/workflows/rust.yml

Some test failures may be caused due to issues in Cassandra or Scylla and it is hard to identify them if they are silent during the whole CI run.
This PR modifies our CI jobs that use docker-compose so that the logs from the cluster are always printed.

CI: print logs from the cluster as a build step

---

test/cluster/docker-compose.yml

Up until now, our docker-compose file that sets up Scylla cluster was starting up all nodes in parallel. This is not something that is supported in Scylla and it can sometimes fail. We didn't see those failures until now because we didn't print the cluster logs. This commit makes sure that nodes are booted up in order.
In addition to this, now nodes start with a fixed number of shards (2 each) and memory (1GB each). I'm not sure a more powerful cluster is really needed, and - by default - the shard count is equal to the number of cores of the host machine. A large number of shards can quickly eat up the /proc/sys/fs/aio-nr resource in the system, so the cluster wasn't really usable on machines with a large number of cores.

docker-compose.yml: improve settings and the boot order

---

scylla/src/transport/connection.rs
scylla/src/transport/iterator.rs
scylla/src/transport/query_result.rs
scylla/src/transport/topology.rs

For internal queries that can return a large number of rows (topology info, schema) we use currently use `Connection::query_all` to perform them. That method fetches results of the query in multiple pages and then returns it as a single combined `QueryResult`. This PR replaces it with a new `Connection::query_iter` method which has semantics more similar to the iterator-based query methods from the public interface (`Session::query_iter`, `Session::execute_iter`).
The motivations for this change are as follows:
- Although the new methods will use slightly more memory if the query returns only one page (because of the need to spawn a new task/channels/etc.), it should consume less memory if multiple pages are fetched because rows are processed on-line as new pages appear and only 1-2 pages …

Replace Connection::query_all with Connection::query_iter

---

scylla-cql/src/frame/response/result.rs
scylla/src/transport/session_test.rs
scylla/src/transport/topology.rs

It has been requested by a customer to make `CqlType::UserDefinedType` hold a complete definition of the type. 
Before, the definition was distributed among multiple code locations: the type name was present inside the mentioned variant, the keyspace name was to be deduced from the context, and the fields definitions were only stored in a hash map in each `Keyspace`.
This PR:
- introduces `UserDefinedType` struct as a complete UDT definition,
- makes the `Keyspace` hold the hash map from UDT name to  `Arc<UserDefinedType>`,
- makes `CqlType::UserDefinedType` store a complete definition of a UDT (`Result<Arc<UserDefinedType>, MissingUserDefinedType>`, the `Err` variant is used in case when an unknown UDT is defined as a field of another UDT),
- introduces `UdtRow` struct to represent a row …

topology: UDTs hold complete definition of themselves

---

scylla/src/transport/iterator.rs
scylla/src/transport/session.rs
scylla/src/transport/topology.rs

Fixes #655
This would have a significant perf impact (see #655) and be unidiomatic (see https://docs.rs/tracing/0.1.37/tracing/#recording-fields)

Don't early-allocate trace arguments (significant perf impact somehow)

---

scylla-cql/src/frame/types.rs
scylla/src/transport/partitioner.rs

The usual: clippy have been updated in GitHub's CI runner image that we use and it has new lints that our codebase doesn't currently pass.
This time, clippy complains about some `impl Default`s being unnecessarily hand-written where they could be easily implemented with an automatic derive. This commit removes the problematic impl for PartitionerName and replaces it with a derive, but the impl for Consistency is left as is and marked with an "allow" annotation. Unfortunately, implementing Default with a derive requires adding a #[default] annotation in the enum body which incorrectly interacts with num_enum::TryFromPrimitive macro.

treewide: appease clippy

---

scylla/src/transport/session.rs

Helps (or arguably fixes) #468
For smarter batch constitution (following up on #448), it is required to have access to the token a particular statement would be directed to. However, that is pretty difficult to do without access to calculate_token.
That was initially put in #508, but planned to put in a separate PR to keep it minimal
(https://github.com/scylladb/scylla-rust-driver/pull/508#discussion_r949399700)
It seems I had forgotten to open that separate PR, and I end up getting bitten by that now that I want to constitute my batches in a smarter way. ^^'
So here it is.
I'm only putting "helps" above because I think we may want to also expose query planning (
`session.plan(prepared_statement, serialized_values) -> impl Iterator<Item = (Arc<Node>, ShardID)>` ) as that may make it …

Expose calculate_token

---

scylla-cql/src/frame/response/cql_to_rust.rs
scylla-cql/src/frame/response/error.rs
scylla/src/routing.rs
scylla/src/statement/prepared_statement.rs
scylla/src/transport/query_result.rs

For convenience, adds a `#[derive(Clone)]` for those error types for which it was currently possible. Some error types currently have fields that cannot be cloned (mostly std::io::Error), notably:
- ParseError, FrameError - extensively used in deserialization, but don't seem to appear in the main API.
- CloudConfigError - only used when creating a session that connects to Scylla Cloud.

treewide: implement Clone for most error types

---

examples/compare-tokens.rs
scylla-cql/src/frame/response/result.rs
scylla-cql/src/frame/value.rs
scylla/src/transport/cluster.rs
scylla/src/transport/connection.rs
scylla/src/transport/connection_pool.rs
scylla/src/transport/iterator.rs
scylla/src/transport/load_balancing/default.rs
scylla/src/transport/partitioner.rs
scylla/src/transport/query_result.rs
scylla/src/transport/session.rs
scylla/src/transport/session_test.rs
scylla/src/utils/mod.rs
scylla/src/utils/pretty.rs

Provides more information in trace spans emitted for unprepared query, prepared query and batch requests.
The following information is provided:
- `kind`: type of operation (`unprepared`, `prepared`, `batch`),
- `contents` - the query string (applicable only to unprepared queries),
- `routing_key`: routing key of the request (if known, i.e. applies only to prepared queries),
- `token`: partition token relevant to the request (if known, i.e. applies only to prepared queries),
- `request_size`: serialized size of query parameters (not implemented for batches),
- `result_size`: serialized size of rows returned in response,
- `result_rows`: number of rows returned in response,
- `shard`: ID of the shard the request was served on,
- `speculative_executions` - the number of times this request …

Extended request spans

---

docs/_utils/prepare_sphinx_source.py

The `prepare_sphinx_source.py` script goes over snippets of Rust code in the docs and removes the lines that start with a pound sign (#). This is done to simulate the mdbook behavior: the snippets are supposed to be valid Rust code that compiles, however making them compile may require adding some boilerplate lines of code that shouldn't be displayed in the final documentation. Sphinx, used to generate the official documentation, doesn't understand that so we need a script to pre-process.
However, the current behavior of the script is not entirely correct. Not every line that starts with a pound sign should be removed - for example, `derive` attributes like this are currently stripped but shouldn't:
#[derive(Debug)]
struct Foo {
bar: i32,
}
In order to fix this, the code is adjusted to …

docs: don't strip Rust attributes

---

docs/source/load-balancing/default-policy.md
scylla/src/transport/load_balancing/default.rs

Added rack-awareness option to prefer replicas in local rack while picking a coordinator. It will allow to create a top-level tier with local datacenter and local rack replicas in the fallback plan.
Fixes: #604

Add rack-awareness to default LBP

---

scylla-cql/src/frame/response/cql_to_rust.rs
scylla-cql/src/frame/value.rs
scylla-cql/src/frame/value_tests.rs

Right now the driver supports Vec<u8>. This PR adds serialize/deserialize support for [u8; N]
@piodul for review

Add serialize/deserialize support for [u8; N]

---

docs/source/retry-policy/default.md
scylla/src/statement/batch.rs
scylla/src/statement/prepared_statement.rs
scylla/src/statement/query.rs
scylla/src/transport/caching_session.rs
scylla/src/transport/connection.rs
scylla/src/transport/iterator.rs
scylla/src/transport/session.rs

The `set_retry_policy` and `get_retry_policy` methods of `Query`, `PreparedStatement` and `Batch` were removed #592, but are re-added here due to user request and because they will be useful for cpp-rust-driver.
One important difference with the old `{set,get}_retry_policy` is that the new methods take and `Arc<dyn RetryPolicy>` instead of `Box<dyn RetryPolicy>`. This was done in order not to introduce additional allocations when a query/statement/batch is cloned.
The retry_policy field was added directly to
`Batch`/`Query`/`PreparedStatement` instead of `StatementConfig`. Unfortunately, `StatementConfig` is public along with all of its fields, so adding more fields to it will be a breaking change. This should be fixed during/after #701.
Fixes: #692

statement/transport: re-add per-statement setters for retry policy

---

docs/source/queries/batch.md

This commit clarifies the doc page about batches and performs two changes:
- Occurrences of "query" have been changed to "statement". Batches do not support putting queries into them, only data-modifying statements. The driver documentation interchangeably uses "query" and "statement" which is not really correct but is especially confusing in this page.
- The first paragraph now also lists `DELETE` as a possible operation for batch in addition to `INSERT` and `UPDATE`.
As a bonus, a single backslash that was unnecessarily rendered at the end of a line was removed.

docs/batch: clarify the wording around what can be put in batches

---

examples/logging.rs

The executed request no longer produces any warnings. This was changed in 2af7800c: `session: improve use keyspace queries detection`, since when `USE KEYSPACE ` statement is no longer parsed by the driver. As since then the parsing is delegated to the database (and therefore considered stable), the warning about sending raw `USE KEYSPACE` being experimental is no longer relevant.
Fixes: #589 
- ~~[ ] I have split my patch into logically separate commits.~~

examples: logging: removed obsolete comment

---

scylla/src/transport/load_balancing/default.rs

The test bearing an undeniably attractive name: `latency_aware_default_policy_stops_penalising_after_min_average_increases_enough_only_after_update_rate_elapses` has shown to be flaky. I suspect it is due to the fact that it relies on timing to be valid, and execution in CI is often extremely slow. The problem, most probably, lies in minimum average updates done periodically: the test code assumes that an update has not yet been triggered at some point, which in CI happens to not be true.
To combat that:
- min avg update logic is extracted into `MinAvgUpdater` struct
- it is made configurable upon LA creation whether updates are to be scheduled to be periodically issued (as before, used in real cases) _or_ triggered manually by calls on `MinAvgUpdater`, 
- the affected tests (those that …

latency_awareness: Combat tests flakiness by not relying on timing

---

docs/source/load-balancing/default-policy.md
scylla/src/transport/load_balancing/default.rs
scylla/src/transport/load_balancing/mod.rs
scylla/src/transport/load_balancing/plan.rs
scylla/src/transport/locator/mod.rs
scylla/src/transport/locator/precomputed_replicas.rs
scylla/src/transport/locator/replication_info.rs
scylla/src/transport/locator/token_ring.rs
scylla/src/transport/node.rs
scylla/tests/integration/lwt_optimisation.rs

While routing statements that are confirmed LWTs, replicas are never shuffled but instead attempted in the ring order. This is done according to https://github.com/scylladb/gocql/issues/40.
In case of Network Topology Strategy, the replica iterator we obtain from the `ReplicaLocator` (`ReplicaSetIterator`) does not yield replicas in the ring order.
To support that, `ReplicasOrdered` struct is added and constructible from `ReplicaSet`. It is also convertible into `ReplicasOrderedIterator`, which does yield replicas in the ring order.
The first call to `next()` on `ReplicasOrderedIterator` is cheap, because the primary replica can be computed cheaply, and this suits the `pick()` method.
The second call to `next()` is expensive, because all the replicas are materialised in a vector (there is …

LWT routing optimisation: plan contains replicas in ring order

---

scylla/src/transport/execution_profile.rs

Contrary to what is stated in documentation, the default SerialConsistency was None, which resulted in SerialConsistency not being set in the CQL frames. This led to ProtocolError in case of LWT statements. As it is better to always include SerialConsistency (even for statements for which it is not relevant), the previous default is reverted.
Ref: https://github.com/scylladb/scylla-enterprise/issues/2970

exec_profile: Default to SerialConsistency::LocalSerial

---

scylla/Cargo.toml
scylla/src/transport/connection.rs
scylla/src/transport/session.rs
scylla/src/transport/session_builder.rs

Similarly to other drivers, support for TCP-layer keepalives is added. This is possible, because tokio::net::TcpStream finally implements `AsFd`. This enables creating `socket2::SockRef`, which in turn allows for configuring the underlying socket.
Fixes: #132 

connection: Add configurable TCP keepalives

---

scylla/src/transport/connection.rs
scylla/src/transport/session.rs
scylla/src/transport/session_builder.rs

Each connection is managed by a tokio task that reads from and writes to a single socket. The task (called internally as "router") polls, amongst others, a future that collects write requests from a channel and pushes them to the socket. It currently has a heuristic that is meant to be a throughput optimization: if there are no more write requests on the channel, the future yields, hoping to give an opportunity for more write requests to arrive on the channel. This improves efficiency as it allows more requests to be batched together into a single write and reduces the number of syscalls issued.
The described optimization was implemented in:
e1c0b6f3b48eac2f60c043c05fc0b806189788c4
However, this optimization obviously can cause worse latency in some scenarios. For example, if there aren't …

connection: make it possible to switch off write coalescing

---

scylla-proxy/src/proxy.rs
scylla/src/transport/connection.rs
scylla/src/transport/connection_pool.rs
scylla/src/transport/session.rs
scylla/src/transport/session_builder.rs

This PR aims to add a feature that has been supported in other drivers: closing connections when not receiving responses to keepalives. To do so:
- `SessionBuilder`, `SessionConfig` and `ConnectionConfig` get new parameter: `keepalive_timeout`,
- `Keepaliver` is refactored so that it no longer resides in the connection pool layer, but...
- ...it is moved into `Connection` layer, more specifically into `router`. This enables clean closing connection when the keepalive timeout elapses without receiving a response,
- a test is added for the new feature.
Fixes: #718

Close connections on no response to keepalives 

---

.github/workflows/authenticate_test.yml
.github/workflows/book.yml
.github/workflows/cassandra.yml
.github/workflows/docs-pages.yaml
.github/workflows/docs-pr.yaml
.github/workflows/rust.yml
.github/workflows/serverless.yaml
.github/workflows/tls.yml

As it may happen that a pushed PR triggers a nonterminating test, it is desirable to automatically timeout such CI runs. This commit adds timeouts that have been empirically tested to suffice (by past experience with CI execution time).
Fixes: #721

CI: Bound all workflows with a timeout

---

.github/workflows/serverless.yaml

ccm requries Python 2 when creating a serverless cluster. Installing Python 2 with actions/setup-python@v2 is now deprecated, so we solve it by explicitly using ubuntu-20.04 runners, which have it installed.
Closes #751

CI: use ubuntu-20.04 in serverless workflow

---

scylla/src/transport/session_builder.rs

For serverless clusters, the secure connection bundle should specify the contact points and the SSL context, so setting SSL context for `CloudSessionBuilder` should not be allowed.
Fixes #695

Allow ssl-context only for non-cloud session builder

---

scylla/src/cloud/config.rs
scylla/src/transport/session.rs

Allows to construct `CloudConfig` and manually set it in `SessionConfig`. It will also help to add serverless support in C++ bindings.

Make `CloudConfig` public

---

scylla/src/transport/load_balancing/default.rs

The parameter was omited accidentally while porting.
To the best of my understanding of the previous version of the code, the scale that was implicitly used before was equal to **1 second**. The new default value is, in line with other drivers, **100 milliseconds**. This implies that this is an API-breaking change.
Fixes: #650

Latency awareness: add `scale` parameter

---

docs/source/quickstart/create-project.md
scylla/Cargo.toml

The #668 PR introduced changes that require new features from the `tracing` crate. Bump the depdendency to `0.1.36` which supports all required features.
Additionally, the dependency is also updated in the quickstart guide.
Fixes: #754

scylla/Cargo.toml: bump the tracing dependency to 0.1.36

---

scylla/src/statement/prepared_statement.rs
scylla/src/transport/session.rs
scylla/src/transport/session_test.rs

The function `Session::calculate_token_for_partition_key()` is added and tested. It enables computing the token without prior preparing, straight from a given partitioner and a serialized partition key.
Fixes: #746

Calculate token without preparing

---

scylla-cql/src/errors.rs
scylla/src/transport/session.rs
scylla/tests/integration/main.rs
scylla/tests/integration/new_session.rs

A user encountered a following problem:
> Rust Driver wasn't able to start if one of the configured nodes was not available
This was found to be caused by the hostname resolution logic, which considered failure in resolving any hostname to be a critical error.
As it makes more sense to fail only when we end up with no contact points with known resolved addresses, in that case, a new variant is returned: `NewSessionError::FailedToResolveAnyHostname`, else initialisation continues successfully.
The new behaviour is automatically tested.

Proceed on unresolvable hostname

---

.github/workflows/authenticate_test.yml
.github/workflows/book.yml
.github/workflows/cassandra.yml
.github/workflows/rust.yml
.github/workflows/serverless.yaml
.github/workflows/tls.yml

Before this PR, GitHub Actions would warn that `actions/checkout@v2` and `actions-rs/toolchain@v1` use deprecated functionality:
> The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, actions-rs/toolchain@v1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Those warnings are fixed in this PR by:
- Updating the version of `actions/checkout` action (from `@v2` to `@v3`)
- Removing use of `actions-rs/toolchain@v1` …

Fix GitHub Actions warnings in CI

---

scylla-cql/src/frame/mod.rs

Reduce visibility of several functions and constants which are only used internally within `frame` and don't have to be exposed publicly. In this patch only the most obvious ones are tackled (ones that require a change solely in `scylla-cql`). This change is a part of our effort to stabilize the API.
Refs #660

frame: reduce visibility of several funcs/consts

---

scylla/src/transport/connection.rs

Remove re-export of `QueryResult` (from `scylla::transport::query_result::QueryResult` to `scylla::transport::connection::QueryResult`). The motivation for this change is to reduce the number of re-exports in the codebase (some of them don't make sense and are there for legacy reasons), as a part of our effort of stabilizing the API.
It probably makes sense to follow this up with moving `QueryResult` from `transport/` module to a more appropriate module (`query/` module?).
Refs #660

connection: remove re-export of QueryResult

---

scylla/src/routing.rs

Remove struct `scylla::routing::Node` from `routing.rs`. This structure was introduced in 2020 in 1c8df890d6419e4612fbdbb4aef1fb68c35ffb88 and it is unused in our current code (and it looks like the original commit didn't even use it at all). 
Moreover, this struct clashes with `scylla::transport::Node` making it error-prone to find the wrong `Node` struct for a user of the driver. The deleted `Node` structure also relied solely on `SocketAddr`, while we  want to identify the nodes by `host_id` (as in `scylla::transport::Node`).
Refs #660

routing: remove Node struct

---

scylla/src/statement/batch.rs

Remove re-export of consistency enums in batch.rs:
- `scylla:statement::batch::Consistency`
- `scylla:statement::batch::SerialConsistency`
A user of the driver should instead use:
- `scylla:statement::Consistency`
- `scylla:statement::SerialConsistency`
This change is a part of our effort to stabilize the API and reduce the number of pub exports.
Refs #660

batch: remove re-export of consistency enums

---

scylla/src/statement/prepared_statement.rs
scylla/src/transport/iterator.rs
scylla/src/transport/session.rs
scylla/src/utils/pretty.rs

This PR changes the format used by `RequestSpan` to represent the partition key for a given query. Previously, it was the same representation that the driver creates before applying MurmurHash3 to it, encoded in base64 - the format is documented so technically users can decode it themselves, but it's quite inconvenient. Now, the driver decodes the contents of the partition key and represents it in a human-readable form, similar to the CQL syntax.
For example, given the schema
```cql
create table ks.t (pk1 int, pk2 time, pk3 frozen<set<text>>, primary key(pk1, pk2, pk3));
```
and the request
```rust
session
.execute(
&prepared,
(
6622i32,
Time(chrono::Duration::seconds(12323)),
vec!["quick", "brown", "fox"],
),
)
.await
.unwrap();
```
previously, the encoded key would look like this:
``` …
```

session: include partition key in RequestSpan in human readable form

---

scylla-cql/Cargo.toml
scylla-cql/src/frame/types.rs
scylla/Cargo.toml

As the [awaited issue](https://github.com/illicitonion/num_enum/issues/75) in `num_enum` crate has been resolved in its 0.6 release, it is now possible to derive Default for Consistency automatically.

scylla_cql: autoderive Default for Consistency

---

examples/compare-tokens.rs
examples/tracing.rs
scylla/src/tracing.rs
scylla/src/transport/session.rs
scylla/src/transport/session_builder.rs
scylla/src/transport/session_test.rs
scylla/src/utils/test_utils.rs

This PR removes two public functions from `Session`: `estimate_replicas_for_query` and `get_tracing_info_custom`.
Those changes are a part of our effort to stabilize the API and reduce the number of pub functions.
Refs https://github.com/scylladb/scylla-rust-driver/issues/660
Remove `estimate_replicas_for_query` from Session. A user of this function can switch to using `get_token_endpoints()` from `ClusterData` directly.
It did not make sense for `estimate_replicas_for_query()` to be in `Session`, as this is too much low-level function for `Session` and doesn't fit the abstraction of `Session`.
Remove `Session::get_tracing_info_custom` - a variant of `Session::get_tracing_info` that allows for additional customization of the fetch process (number of attempts, interval between attempts, …

session: remove estimate_replicas_for_query, get_tracing_info_custom

---

scylla-cql/benches/benchmark.rs
scylla-cql/src/frame/mod.rs
scylla-cql/src/frame/request/auth_response.rs
scylla-cql/src/frame/request/batch.rs
scylla-cql/src/frame/request/execute.rs
scylla-cql/src/frame/request/mod.rs
scylla-cql/src/frame/request/options.rs
scylla-cql/src/frame/request/prepare.rs
scylla-cql/src/frame/request/query.rs
scylla-cql/src/frame/request/register.rs
scylla-cql/src/frame/request/startup.rs
scylla-cql/src/frame/value.rs
scylla-proxy/src/frame.rs
scylla/src/statement/batch.rs
scylla/src/transport/connection.rs
scylla/src/transport/iterator.rs
scylla/src/transport/session.rs
scylla/tests/integration/consistency.rs
scylla/tests/integration/main.rs

A bug has been found that put wrong `Consistency` and `SerialConsistency` into `RoutingInfo`. In order to:
- be sure that it's fully fixed,
- prevent regressions,
- check consistencies in other contexts,
the following is done:
- proxy acquires deserialization capabilities for request frames; it understands `Query`, `Execute` and `Batch` frames,
- a test is added to check that request frames contains consistencies that match the specified ones,
- a test is added to check that `RoutingInfo` for `LoadBalancingPolicy` contains the specified consistencies,
- as the latter test confirms the bug in `Session`, the affected methods are fixed,
- minor refactor is done in `Session` to make fiddling with consistency clearer,
- bonus: utilities for single-node dry-mode cluster are added, based on the …

Fix RoutingInfo consistency

---

scylla/src/transport/session_builder.rs

When added, `write_coalescing()` method was mistakenly put on `SessionBuilder` instead of `GenericSessionBuilder`. It is moved there, as there is nothing against using it in Cloud.

session_builder: move `write_coalescing()` to generic builder

---

scylla/src/statement/batch.rs
scylla/src/statement/mod.rs
scylla/src/statement/prepared_statement.rs
scylla/src/statement/query.rs
scylla/src/transport/caching_session.rs
scylla/src/transport/connection.rs
scylla/src/transport/session.rs

`StatementConfig` is only used internally and does not appear in any public API.
- It is made `pub(crate)` together with its fields so that we have more flexibility in changing it without introducing a breaking change.
- After that, `retry_policy` field is moved from `Query`, `PreparedStatement` and `Batch` into `StatementConfig`, as it suits there best.
Refs: #660
Fixes: #701 

statement: unpub StatementConfig

---

docs/source/load-balancing/default-policy.md
scylla/src/transport/load_balancing/default.rs

This is an API restriction continuing of what has already been done in bb09756a1d97da4a870f87f00c5b2c081e8079b2: as the case of providing preferred rack without specifying the preferred datacenter is invalid, in spirit of the principle _“Make illegal states unrepresentable”_, `DefaultBuilder`'s API is changed accordingly to disallow creating such configuration.

default_policy: Builder: forbid preferring rack without specifing datacenter

---

scylla/src/transport/caching_session.rs
scylla/src/transport/cluster.rs
scylla/src/transport/connection.rs
scylla/src/transport/connection_pool.rs
scylla/src/transport/iterator.rs
scylla/src/transport/node.rs
scylla/src/transport/topology.rs
scylla/src/utils/parse.rs
scylla/src/utils/pretty.rs

In spirit of the referenced issue, `scylla` crate is saved from the hazardous siege of `pub` qualifiers. This PR collects the changes that I believe to be non-breaking, so that they can be merged immediately.
Refs: #660 

codewide: Decrease excessive visibility from `pub` - nonbreaking changes

---

scylla/src/transport/session_builder.rs

It has happened several times that a configuration option (a method) for `GenericSessionBuilder` was implemented on `SessionBuilder` only, even though it suited `CloudSessionBuilder` as well. To protect against such mistakes:
- all three `impl` blocks (both specific ones and the generic one) are guarded with comments,
- `impl SessionBuilder` block is renamed to `impl GenericSessionBuilder<DefaultMode>` to highlight that this is a specific implementation only.

session_builder: Stress that new options should go to proper mode

---

scylla-macros/Cargo.toml
scylla-macros/src/parser.rs

The way attributes are handled was changed a lot in syn `2.0`.
For our usage here the changes arent too complex though:
* Attribute now has `path` as a method instead of a field
* Attribute now has `meta` as a field instead of a method
* NameValue now has the value as an expression from which we must extract the literal instead of just holding a literal directly.

Update syn to 2.0

---

docs/source/load-balancing/default-policy.md
scylla/src/transport/load_balancing/default.rs
scylla/src/transport/locator/mod.rs

Until now, the default policy respected rack preference only when it came to replicas.
Considering non-token-aware queries (e.g. unprepared statements), they would never prioritize the preferred rack.
Now, local rack nodes are always preferred before other nodes, both in `pick()` and in `fallback()`.
Existing tests adjusted for new behaviour.
The PR contains breaking changes, as it slightly changes signature of `ReplicaSet::choose_filtered()` (note the reference added).

default policy: Rack awareness without token awareness

---

docs/source/conf.py

Currently, the Rust Driver documentation shows the docs for the branch "main".
This commit enables publishing the docs for the latest Rust Driver version and sets it as the latest STABLE version.

doc: enable publishing docs for tag v0.9.0

---

docs/Makefile

In some setups, documentation won't build if python3 is used in the "python3 _utils/prepare_sphinx_source.py _source" command.
This commit replaces python3 with python to make it work.

doc: replace python3 with python in Makefile

---

scylla/src/routing.rs
scylla/src/transport/connection.rs
scylla/src/transport/locator/mod.rs
scylla/src/transport/session.rs
scylla/src/transport/speculative_execution.rs
scylla/src/transport/topology.rs

In spirit of the referenced issue, `scylla` crate is saved from the hazardous siege of `pub` qualifiers. This PR collects the changes that I believe to be API-breaking. These changes, however, seem to be relatively benign.
Refs: #660 

codewide: Decrease excessive visibility from `pub` - breaking changes

---

scylla-cql/src/frame/value.rs
scylla-cql/src/frame/value_tests.rs

Implement `Value` for `u8` slices to allow deriving `ValueList` for structs with `&[u8]` fields.

value: implement serialize for u8 slices

---

scylla/src/statement/prepared_statement.rs

When PartitionKeyDeserializer wants to deserialize i-th column of the partition key, it needs to know the type of that column. It has access to PreparedMetadata of the prepared query the partition key was constructed from, which has a mapping between bind markers and types. Hence, it needs to learn to which bind marker the i-th pk column corresponds to.
The `self.pk_indexes` of type `Vec<PartitionKeyIndex>` is supposed to help with that. The PartitionKeyIndex structure looks like this:
pub struct PartitionKeyIndex {
/// index in the serialized values
pub index: u16,
/// sequence number in partition key
pub sequence: u16,
}
So, we need to find an entry `pki` with `pki.sequence == i` and `pki.index` will be the desired bind marker index.
Currently, we naively look at the …

prepared_statement: fix deserialization of compound partition keys

---

examples/compare-tokens.rs
scylla-cql/src/frame/response/result.rs
scylla/benches/benchmark.rs
scylla/src/statement/prepared_statement.rs
scylla/src/transport/cluster.rs
scylla/src/transport/iterator.rs
scylla/src/transport/partitioner.rs
scylla/src/transport/session.rs
scylla/src/transport/session_test.rs
scylla/src/utils/mod.rs

Currently, partitioners require the whole input to be passed in a single contiguous slice, which often forces an allocation that could else be avoided.
1. **Partitioners' API is refactored** so it resembles `std::hash` API:
- `Partitioner` corresponds to `BuildHasher` as it becomes kind of a factory,
- `PartitionerHasher` is introduced and corresponds to `Hasher`. It contains the hashing state, which enables feeding it with multiple chunks of data separately.
A **test** is added that **ensures consistent hashing result** no matter how the partition key is partitioned into chunks.
2. After the partitioners gain ability to partition by chunks, the codebase is modified so that **all needless allocations of partition key are avoided**, i.e., allocations that only served the purpose of …

Stateful partitioners

---

scylla/src/transport/cluster.rs
scylla/src/transport/session.rs
scylla/src/transport/topology.rs

This is a bunch of performance-related small optimisation of the `cluster` module, mainly focused on avoiding cloning where possible.

cluster: small performance optimisations

---

docs/source/queries/schema-agreement.md
examples/schema_agreement.rs
scylla/src/transport/session.rs
scylla/src/transport/session_builder.rs
scylla/src/transport/session_test.rs

Schema agreement API is another place in the driver's code that can be polished towards API stability.
1. `fetch_schema_version() ` is removed. 
It can be a nasty source of race bugs when schema version is fetched without awaiting for schema agreement. It is especially risky when one awaits schema agreement and subsequently fetches schema version, because the schema version can change in the meantime and schema may no longer be in agreement. To cope with the problem, `await_schema_agreement()` now returns the agreed schema version, and  `fetch_schema_version()` is removed alltogether.
2. `await_schema_agreement()` gets implicit timeout.
Similarly to
- what Java driver 3 does in regard to awaiting schema agreement's API,
- what was recently done in Rust driver in regard to tracing info's …

Slim down schema agreement API

---

scylla-cql/src/errors.rs
scylla-cql/src/frame/request/batch.rs
scylla-cql/src/frame/request/mod.rs
scylla-cql/src/frame/request/query.rs
scylla-cql/src/frame/response/error.rs
scylla-cql/src/frame/types.rs
scylla-proxy/src/actions.rs
scylla-proxy/src/frame.rs
scylla/src/history.rs
scylla/src/transport/downgrading_consistency_retry_policy.rs
scylla/src/transport/iterator.rs
scylla/src/transport/retry_policy.rs
scylla/src/transport/session.rs
scylla/tests/integration/consistency.rs
scylla/tests/integration/execution_profiles.rs

See #736.
- `Consistency` is extended with `Serial` and `LocalSerial` to support reading using Paxos (SELECT statements),
- `LegacyConsistency` is removed altogether,
- a test is added that performs such a Paxos read.
Fixes: #736

codewide: Allow setting Serial,LocalSerial for Consistency

---

scylla/src/transport/session.rs

Both `AddressTranslator` trait and `address_translator` `pub` field in `SessionConfig` were missing docstrings. They were added. The docstring for the trait is adapted from Java driver 3.

session: add docstrings for AddressTranslator

---

docs/source/connecting/connecting.md
scylla/src/transport/cluster.rs
scylla/src/transport/session.rs
scylla/src/transport/session_builder.rs

This pull requests a configurable way to topology refresh duration. Two files session.rs and cluster.rs have been modified to set the session configuration and consume the duration configuration respectively.
Note: I am not sure if we need any test cases in this case as the duration is still provided from where its called. 
Fixes: #232

configurable topology refresh duration

---

scylla-proxy/src/actions.rs
scylla-proxy/src/lib.rs
scylla-proxy/src/proxy.rs
scylla/src/transport/connection.rs
scylla/tests/integration/consistency.rs
scylla/tests/integration/lwt_optimisation.rs
scylla/tests/integration/main.rs
scylla/tests/integration/shards.rs

It appears (e.g. in #738) that our proxy lacks ability to inform which shard was queried. This is because it is represented in a per-node, not per-shard way.
- proxy workers are made aware of the shard they are connected to. This, of course, requires that a shards count is known, either by `ShardAwareness::FixedNum` or by querying a node;
- proxy logs are enriched with info about target shard;
- the optional feedback (triggered by a frame matching the specified criteria) is extended: previously it sent a frame through a channel, now it sends a pair (frame, shard number).
- while using proxy manually, it is easier to trace what shard is queried;
- it is possible now to write automated tests asserting that a particular shard is queried. 
- ~~[ ] I have provided docstrings for the public …

proxy: send shard number as feedback along with the frame 

---

scylla-cql/Cargo.toml
scylla/Cargo.toml

The `criterion` library, since version 0.5, depends on `clap` v4 or higher. Recently, `clap` 4.4.0 has been released which has bumped its required MSRV to 1.70.0. Our MSRV is still 1.65.0. Apparently, the cargo resolver isn't smart enough to choose an older version of `clap` which still supports 1.65.0, so this breaks our MSRV build in CI (see rust-lang/cargo#9930).
In order to unblock the CI without checking in Cargo.toml - which would be annoying - the `criterion` dependency is downgraded to 0.4. This library is only used for benchmarks and is a dev-dependency, so it's not a big deal. No changes in the code are necessary.
In the future, if we decide to bump MSRV to 1.70.0 or further, we can update the dependency.

dev-deps: downgrade criterion to 0.4

---

scylla-cql/src/frame/response/cql_to_rust.rs
scylla-cql/src/frame/types.rs
scylla-cql/src/frame/value_tests.rs
scylla/src/history.rs
scylla/src/transport/session_test.rs

This time, we've got a double whammy:
- `clippy` version has been bumped up in GitHub's CI runner, which introduced new lints that are failing for our codebase,
- New version of `chrono` has been released which deprecates `DateTime::from_utc`.
This PR addresses both of the issues, making the CI green again.

treewide: appease clippy and the deprecation warnings

---

RELEASE.md

This commit updates the release procedure to include a step to publish the docs for the new driver version.

doc: document releasing Rust Driver documentation

---

scylla/src/transport/connection.rs
scylla/tests/integration/main.rs
scylla/tests/integration/retries.rs
scylla/tests/integration/silent_prepare_query.rs

See the referenced issue (#800)
Information about the types of the bind markers is necessary to make the serialization API safe (i.e. so that the user data won't be misinterpreted when sending it to the database). The problem with unprepared statements is that the driver doesn't have a good way to determine column names and types of the bind markers.
Now before sending an unprepared statement, it is quietly prepared on one connection to obtain the information about the bind markers. If the list of values to be bound is empty, we just send it as an unprepared query.
Integration tests are added.
Refs: #800

Quietly prepare unprepared query

---

scylla-cql/Cargo.toml

In scylla-cql/src/frame/response/cql_to_rust.rs we use `DateTime::<Utc>::from_naive_utc_and_offset` but it was introduced in chrono 0.4.27. This PR bumps this dependency to correct version.

Bump verrsion of chrono dependency

---

scylla-cql/src/frame/response/cql_to_rust.rs
scylla-cql/src/frame/value.rs

Hello. The library is super great, but I noticed one problem. Custom hashers are not supported. 
I introduced some new generics that allow you to serialize HashMaps and HashSets with custom hashers.
I wanted to speedup my code and have chosen [ahash](https://docs.rs/ahash/latest/ahash/) as custom hasher for my hashmaps. But found out that I need to convert hashmap back to default hasher in order to serialize it to valueslist.

Added custom hashers support for HashSet and HashMap.

---

scylla-cql/src/frame/value.rs

It seems that currently the argument provided to this function is being treated as the _number_ of items that we expect to serialize. Normally that would make sense because the argument is passed along to `Vec::with_capacity` which provisions space for the inner `serialized_values` field. However, that field is a `Vec<u8>` so really the argument corresponds to the total _size_ of the serialized values in bytes.
This commit tries to be smarter about reserving space by taking into account the actual size in memory of the values to be serialized. It's not perfect (e.g., `String`s will always reserve the same amount of space, regardless of how long their actual contents are) but hopefully it will still result in fewer re-allocations.

Improve calculation for `SerializedValues::with_capacity`

---

scylla/src/transport/connection.rs
scylla/src/transport/mod.rs
scylla/src/transport/silent_prepare_batch_test.rs

See the referenced issue (#800)
Information about the types of the bind markers is necessary to make the serialization API safe (i.e. so that the user data won't be misinterpreted when sending it to the database). The problem with unprepared statements in batch is that the driver doesn't have a good way to determine column names and types of the bind markers.
Now before sending a batch, every unprepared statement is quietly prepared on one connection to obtain the information about the bind markers. If the list of values to be bound to the statement is empty, we just send it as an unprepared query.
Fixes: #800

Quietly prepare unprepared queries in batches

---

scylla-cql/src/lib.rs
scylla-cql/src/types/mod.rs
scylla-cql/src/types/serialize/mod.rs
scylla-cql/src/types/serialize/row.rs
scylla-cql/src/types/serialize/value.rs

This commit adds experimental version of new serialization traits. Blanket implementation are provided to support older traits.
For now there are no comments / other implementations with real type checking as the purpose of this PR is to unblock the work on macros
and other parts of refactor.

Add serialization traits

---

scylla-macros/src/from_row.rs
scylla-macros/src/from_user_type.rs
scylla-macros/src/into_user_type.rs
scylla-macros/src/lib.rs
scylla-macros/src/parser.rs
scylla-macros/src/value_list.rs

Our current procedural macros handle errors by panicking. This leads to compilation errors which inform the user about that fact first, and then explain the real issue in the "help" part:
```
error: proc-macro derive panicked
--> examples/user-defined-type.rs:6:10
|
6 | #[derive(FromUserType)]
|          ^^^^^^^^^^^^
|
= help: message: derive(FromUserType) works only on structs!
```
This commit gets rid of `.expect()` and `panic()` calls. Instead, errors are now propagated via `Result<T, syn::Error>` and properly converted to a compilation error at the end. This approach results in nicer error messages and allows to attach the message to a particular part of the original code that could cause the problem.
After the changes, error messages look like this:
```
error: derive(FromUserType) …
```

scylla-macros: report errors as compile errors, not panics

---

examples/parallel-prepared.rs
examples/parallel.rs

Rust 1.73 got released very recently and introduced a new version of clippy, with new lints. The `parallel` and `parallel-prepared` examples contain code which redefines a local variable:
```
for i in 0..100_000usize {
// ...
tokio::task::spawn(async move {
let i = i;
// ...
});
}
```
This is completely unnecesary and can be removed, as per clippy's suggestion:
```
error: redundant redefinition of a binding
--> examples/parallel-prepared.rs:36:9
|
36 |     for i in 0..100_000usize {
|         ^
...
44 |             let i = i;
|             ^^^^^^^^^^
|
= help: remove the redefinition of `i`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_locals
= note: `#[deny(clippy::redundant_locals)]` on by default
```

examples: fix clippy's complaints about redundant_locals

---

scylla/Cargo.toml
scylla/src/transport/load_balancing/default.rs

When Instant::now() returns the same value during 2 calls of
TimestampedAverage::compute_next, division by 0 occurs,
and Duration::from_secs_f64 panics because of NaN input.
This PR fixes the issue, adds additional logs in case another conversion problem
occurs in this code and adds regression test for the issue.

Fix crash when Instant::now() returns the same value twice

---

scylla/Cargo.toml

scylla: Use Tokio test-utils only in tests

---

Cargo.toml

Running `cargo check` using `rust 1.73` prints the following warning message:
```
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
Finished dev [unoptimized + debuginfo] target(s) in 0.05s
```
Documentation about resolver versions can be found here: https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions
Let's use the newer resolver in the whole workspace. The newer resolver is the default that Rust uses since edition 2021.
It also gets rid of the annoying warning.
- ~[ ] I added …

workspace: set resolver = 2 in the root Cargo.toml manifest

---

scylla/src/transport/locator/mod.rs

I encountered a compile error when updating from `0.7.0` to `0.10.1`:
```rs
error[E0277]: can't compare `Option<&str>` with `Option<&&str>`
--> /Users/oeb25/.cargo/registry/src/index.crates.io-6f17d22bba15001f/scylla-0.10.1/src/transport/locator/mod.rs:278:59
|
278 |                 .filter(|node| node.datacenter.as_deref() == Some(datacenter))
|                                                           ^^ no implementation for `Option<&str> == Option<&&str>`
|
= help: the trait `PartialEq<Option<&&str>>` is not implemented for `Option<&str>`
= help: the following other types implement trait `PartialEq<Rhs>`:
<Option<Box<U>> as PartialEq<rkyv::niche::option_box::ArchivedOptionBox<T>>>
<Option<T> as PartialEq>
<Option<U> as PartialEq<rkyv::option::ArchivedOption<T>>>
```
<details> …

Dereference `datacenter` of type `&&str` when comparing with `&str`

---

examples/execution_profile.rs

The example in `execution_profile.rs` tried to send a read request using consistency `EACH_QUORUM`.
This doesn't work, the query failed with the following message:
```
Error: Database returned an error: The query is syntactically correct but invalid, Error message: EACH_QUORUM ConsistencyLevel is only supported for writes
```
Examples shouldn't fail. Let's fix it by changing `EachQuorum` to `LocalQuorum` which can be used in SELECTs.
After this change the example doesn't fail.
It still demonstrates how to create an execution profile with a custom consistency level, it doesn't matter what consistency level is used.
Fixes: https://github.com/scylladb/scylla-rust-driver/issues/835

examples/execution_profile: fix usage of illegal consistency

---

scylla/src/lib.rs
scylla/src/statement/batch.rs
scylla/src/statement/prepared_statement.rs
scylla/src/statement/query.rs
scylla/src/transport/host_filter.rs
scylla/src/transport/session.rs

API doc build job errors on redundant explicit target.
This removes the redundant explicit target, and passes CI doc build.
```
error: redundant explicit link target
--> scylla/src/lib.rs:16:55
|
16 | //! All driver activity revolves around the [Session](crate::Session)\
|                                                                          -------  ^^^^^^^^^^^^^^ explicit target is redundant
|                                                                          |
|                                                                          because label contains path that resolves to same destination
|
= note: when a link's destination is not specified,
the label is used to resolve intra-doc links
= note: `-D rustdoc::redundant-explicit-links` implied by `-D warnings`
help: remove …
```

fixes doc linting error: redundant explicit link target

---

examples/user-defined-type.rs

Previously there was some discrepancy between the examples, specifically how to parse a row into a custom type and and the [docs](https://rust-driver.docs.scylladb.com/stable/data-types/udt.html) about UDT.
Now it is updated.
Fixes: #829

examples: update UDT parsing example to be in line with docs

---

scylla/src/transport/connection.rs

`test_coalescing` spawns a lot of tokio tasks, each of which runs a query on the database.
If a query fails, the task will panic because of the `unwrap()`.
The problem is that all of the tasks are joined using `join_all`, which doesn't check for errors in the joined tasks.
For example, this piece of code prints "Ok!" and the program finishes successfuly:
```rust
let mut tasks = Vec::new();
for _i in 0..4 {
tasks.push(tokio::spawn(async { panic!("Panic!") }));
}
futures::future::join_all(tasks).await;
println!("Ok!");
```
There are some error messages in the output, but the important thig is that they don't stop the control flow.
To fix it, let's use `try_join_all` instead of `join_all`. `try_join_all` will check whether the task panicked or not, and return an error if there was a panic.
I …

test_coalescing: improve error handling

---

.github/workflows/rust.yml
scylla/benches/benchmark.rs

The recent fix that changed the `types::write_short` function to use u16 instead of i16 broke one of our benchmarks - it tried to call that function with a negative number. The benchmarks aren't compiled in our CI, so it didn't catch it.
In order to prevent it from happening in the future, the `rust` workflow now uses the `--all-targets` flag to build and clippy-check the benchmarks as well.

benchmarks/CI: make benchmarks compile and build them in CI

---

test/cluster/cassandra/docker-compose.yml

In January the tests started failing on Cassandra `4.1`, so we pinned the cassandra version to `4.0.7`, which didn't have these problems. `4.0.7` is the version that we've been using in the CI since then.
In the meantime there were new releases of Cassandra, at the moment the latest is `4.1.3`. Let's try to go back to the latest version, maybe the problems fixed themselves during the last nine months.
Refs: https://github.com/scylladb/scylla-rust-driver/issues/620
Refs: https://github.com/scylladb/scylla-rust-driver/pull/629
Fixes: https://github.com/scylladb/scylla-rust-driver/issues/633

cassandra/docker-compose: go back to using the latest cassandra version

---

.github/workflows/cassandra.yml
.github/workflows/rust.yml
Cargo.lock.msrv
docs/source/data-types/data-types.md
docs/source/data-types/date.md
docs/source/data-types/time.md
docs/source/data-types/timestamp.md
examples/Cargo.toml
examples/cql-time-types.rs
scylla-cql/Cargo.toml
scylla-cql/src/frame/response/cql_to_rust.rs
scylla-cql/src/frame/response/result.rs
scylla-cql/src/frame/value.rs
scylla-cql/src/frame/value_tests.rs
scylla/Cargo.toml
scylla/src/tracing.rs
scylla/src/transport/cql_types_test.rs
scylla/src/utils/pretty.rs

Fixes: #741
Goal of this MR is to improve the support of common time crates.
Breaking changes were introduced and a major version bump would be required.
* Reworked `scylla::frame::value` date and time types:
* Align structs with internal CQL representation;
* Rename to add `Cql`- prefix to explicitly show direct relation to CQL types;
* Moved `chrono` dependency of `scylla-cql` behind `scylla-cql/chrono` feature;
* Added optional `time` dependency with full serialization support;
* Implemented traits to convert between chrono/time types and CQL types;
* Removed implementation of `FromCqlValue<CqlValue>` for `chrono::Duration` as it may be misleading. `CqlTime` and `CqlTimestamp` structs are no longer a `chrono::Duration` wrappers;
* `CqlValue::as_date` function signature changed to …

Improve common time and date crates support

---

scylla-cql/src/frame/value_tests.rs

A new clippy lint started complaining about the `check_ref_tuple` test: its inner `assert_has_batch_values`, supposedly, needlessly borrows its argument.
As it looks like one of the points of the test is to verify that batch values taken by reference still implement batch values, the clippy lint seems incorrect. Silence the lint by explicitly specifying that the type of the generic argument for `assert_has_batch_values` is a reference.

value_tests: fix clippy's new complaint about needless_borrows_for_generic_args

---

scylla-proxy/Cargo.toml
scylla-proxy/src/actions.rs
scylla-proxy/src/proxy.rs
scylla/tests/integration/consistency.rs
scylla/tests/integration/shards.rs

Proxy does not allow filtering of control connection messages. Right now this is not a problem, as all queries performed by driver are not prepared, so tests can filter them out by checking query content.
The ongoing serialization refactor changes that and prepares some queries performed automatically by driver, which breaks some tests, as they are not able to differentiate test's queries from internal driver queries.
This PR adds a mechanism to filter out control connection messages by ignoring messages on connections that had any event registered. Control connection is the only one in rust driver that does it, so this should by a reliable heuristic.

scylla-proxy: Add option to filter out control connection messages

---

scylla-cql/src/frame/types.rs
scylla-cql/src/frame/value.rs
scylla-cql/src/frame/value_tests.rs
scylla-cql/src/types/serialize/mod.rs
scylla-cql/src/types/serialize/row.rs
scylla-cql/src/types/serialize/value.rs
scylla-cql/src/types/serialize/writers.rs
scylla/src/statement/prepared_statement.rs
scylla/src/transport/partitioner.rs

Currently, `SerializeRow` and `SerializeCql` traits are just given a mutable reference to a Vec<u8> and asked to append their CQL representation to the end. While simple, there are some issues with the interface:
- The serialize method has access to the serialized representation of the values that were appended before it. It's not necessary for a correct implementation to have access to it.
- Implementors technically can append any byte sequence to the end, but actually are expected to produce a CQL [value] containing the serialized value.
While the `SerializeRow` and `SerializeCql` traits are not generally meant to be manually implemented by the users, we can make the interface easier to use and harder to misuse by making it append-only, restricting what the users are allowed to append …

types: serialize: constrain the new serialization traits to make them easier and safer to use

---

scylla-cql/src/types/serialize/mod.rs
scylla-cql/src/types/serialize/row.rs
scylla-cql/src/types/serialize/value.rs

This PR consists of first 2 commits of https://github.com/scylladb/scylla-rust-driver/pull/858
It was split out in order to merge it before #858, so that #862 and #851 can be rebased on top of it.
There are 2 changes made here:
- changing `dyn Any` to `dyn Error` in SerializationError - it also supports downcasting, but is more useful interface
- Making SerializationError a newtype instead of type alias. This prevents making conversion implementations too generic, like `impl From<SerializationError> for QueryError`, which after desugaring is `impl From<Arc<dyn Error + Send + Sync>> for QueryError` - and writing such implementations doesn't seem like a good idea.

Make SerializationError a newtype

---

scylla-cql/src/frame/response/result.rs
scylla-cql/src/frame/value.rs
scylla-cql/src/frame/value_tests.rs
scylla-cql/src/types/serialize/mod.rs
scylla-cql/src/types/serialize/row.rs
scylla-cql/src/types/serialize/value.rs
scylla-cql/src/types/serialize/writers.rs

The new `SerializeCql` and `SerializeRow` traits are supposed to eventually replace `Value` and `ValueList`. Currently, the new traits are implemented with a blanket implementation based on the old traits - this was just done in order to parallelize work on adapting the whole codebase to the new traits; the blanket implementations are inefficient and not type safe. This PR gets rid of them and, for each type for which we implement `Value` or `ValueList`, introduces proper implementations of `SerializeCql` and `SerializeRow`.
All types now check whether the CQL type serialized to matches, and most of them serialize exactly the same as they used to with the old traits. However, some slight differences were made in order to utilize the information available to the new traits and make it more …

serialization: implement new serialization traits for the currently supported types

---

scylla-cql/src/frame/value_tests.rs
scylla-cql/src/types/serialize/row.rs

Currently ongoing serialization refactor requires to only perform queries with values using prepared statements. Session interface still allows to pass values in query* methods, so we need a way to know if we can perform unprepared query or not.
One way is to always perform prepared queries, but that is not optimal. Before ongoing refactor we could serialize values and check if they are empty. This will no longer be possible soon, because serializing will require knowing column types, which in this case means having a prepared statement.
This commit implements third way - additional method on SerializeRow trait that allows us to check if values are empty (in which case we can skip the prepare).

SerializeRow: Add is_empty method

---

.github/workflows/book.yml
test/cluster/docker-compose.yml

As a workaround for scylladb/scylladb#16329, pass the hostname of the container when checking for its health with `cqlsh`. We need to do this in order to unblock the CI.

CI: use container hostname in healthcheck

---

scylla-cql/src/frame/value_tests.rs
scylla-cql/src/types/serialize/mod.rs
scylla-cql/src/types/serialize/row.rs
scylla-cql/src/types/serialize/value.rs
scylla-cql/src/types/serialize/writers.rs

As @Lorak-mmk stated in https://github.com/scylladb/scylla-rust-driver/pull/858#issuecomment-1841662378, the new serialization traits are incompatible with dynamic dispatch - `dyn SerializeCql`/`dyn SerializeRow` just isn't usable, while this was supported for `Value`/`ValueList`.
This is due to the fact that Rust disallows using traits via `dyn` unless they meet some conditions - and our new traits don't meet them:
1. Both traits have two methods: `preliminary_type_check` and `serialize`. Having a separate type checking phase helps reduce the amount of actual type checking that needs to be performed when serializing (e.g. in case of collections). However, `preliminary_type_check` is an associated function instead of a method by design (i.e. it doesn't take a `self` parameter), and that …

serialize: make new serialization traits object-safe

---

Makefile

In the current makefile benchmarks are not built or checked with `cargo check` / `cargo clippy` so any errors appearing in them will not be caught locally by a dev running `make ci` to perform checks / tests.
This PR adds benchmark building / checking to all relevant makefile targets.

Makefile: build and check benches

---

docs/source/data-types/udt.md
docs/source/queries/values.md
examples/compare-tokens.rs
examples/user-defined-type.rs
examples/value_list.rs
scylla-cql/benches/benchmark.rs
scylla-cql/src/errors.rs
scylla-cql/src/frame/frame_errors.rs
scylla-cql/src/frame/request/batch.rs
scylla-cql/src/frame/request/mod.rs
scylla-cql/src/frame/request/query.rs
scylla-cql/src/frame/value.rs
scylla-cql/src/frame/value_tests.rs
scylla-cql/src/lib.rs
scylla-cql/src/types/serialize/row.rs
scylla-macros/src/value_list.rs
scylla/benches/benchmark.rs
scylla/src/lib.rs
scylla/src/statement/prepared_statement.rs
scylla/src/transport/caching_session.rs
scylla/src/transport/cluster.rs
scylla/src/transport/connection.rs
scylla/src/transport/cql_collections_test.rs
scylla/src/transport/cql_types_test.rs
scylla/src/transport/iterator.rs
scylla/src/transport/partitioner.rs
scylla/src/transport/session.rs
scylla/src/transport/session_test.rs
scylla/src/transport/topology.rs

This PR is based on https://github.com/scylladb/scylla-rust-driver/pull/855 and is the main part of serialization refactor - switching public API to new trait.
The last commit makes the actual change. Previous ones are different changes that were necessary (or helpful) to make the switch.
There are still some things to do:
But the code changes are pretty much ready for review.

Switch Session to new serialization traits

---

scylla-cql/src/macros.rs
scylla-cql/src/types/serialize/row.rs
scylla-cql/src/types/serialize/value.rs
scylla-macros/src/serialize/cql.rs
scylla-macros/src/serialize/mod.rs
scylla-macros/src/serialize/row.rs

The PR introduces two attributes related to matching Rust struct fields by name in the new `SerializeRow`/`SerializeCql` macros:
- `#[scylla(rename = "xyz")]` - instead of using the name of the field verbatim, the name provided in the attribute is used when matching to a column/bind marker/UDT field. This can be useful e.g. if the user has different naming convention in Rust code and in the schema definitions.
- `#[scylla(skip_name_checks)`] - in `enforce_order` flavor, skips checking the names of the fields as they are being serialized. With this attribute, the names of the corresponding fields in Rust struct and UDT/columns/bind markers don't have to match at all, but their _types_ still need to. This attribute is supposed to help migrate from the old `IntoUserType`/`ValueList` macros. …

scylla-macros: attributes for better control over name checks

---

docs/source/data-types/udt.md
docs/source/queries/paged.md
docs/source/queries/simple.md
docs/source/queries/values.md
scylla/src/transport/session.rs

This PR adds warnings about changes introduced in #806 and #812 and updates documentation about new serialization API.

Serialization documentation

---

scylla-cql/src/frame/request/auth_response.rs
scylla-cql/src/frame/request/batch.rs
scylla-cql/src/frame/request/execute.rs
scylla-cql/src/frame/request/mod.rs
scylla-cql/src/frame/request/options.rs
scylla-cql/src/frame/request/prepare.rs
scylla-cql/src/frame/request/query.rs
scylla-cql/src/frame/request/register.rs
scylla-cql/src/frame/request/startup.rs
scylla-cql/src/frame/value.rs
scylla-cql/src/frame/value_tests.rs
scylla-cql/src/types/serialize/batch.rs
scylla-cql/src/types/serialize/mod.rs
scylla-cql/src/types/serialize/raw_batch.rs
scylla-cql/src/types/serialize/row.rs
scylla-cql/src/types/serialize/writers.rs
scylla/src/statement/batch.rs
scylla/src/statement/prepared_statement.rs
scylla/src/transport/caching_session.rs
scylla/src/transport/connection.rs
scylla/src/transport/session.rs

This PR replaces the existing BatchValues API with one that leverages the recently introduced `SerializeCql`/`SerializeRow` infrastructure and is type-safe.
Refs: #801

serialization: implement new, type-safe variants of BatchValues

---

docs/source/queries/batch.md

Add warnings about the fact that Session::batch now automatically prepares simple statements with non-empty value lists. Update the first example not to use such statements in order not to promote suboptimal usage of the API.

docs: update batch.md to warn about automatic preparation

---

Cargo.lock.msrv
docs/pyproject.toml
docs/source/conf.py
docs/source/quickstart/create-project.md
scylla-cql/Cargo.toml
scylla-macros/Cargo.toml
scylla-proxy/Cargo.toml
scylla/Cargo.toml

This PR is to review the changes required to release new version. It should NOT be merged, so I opened it as a draft.
After the approve, I will perform following steps (correct me if I'm wrong @piodul):
- `git checkout branch-0.11.x`
- `git tag -a v0.11.0`
- `git push origin v0.11.0`
- `git checkout main`
- `git merge --ff-only branch-0.11.x`
- `git push origin main`
- Check that documentation was built and published successfully
- Create a github release with previously approved release notes
- Push new version to crates.io:
- Create post on the forum about release

Release 0.11.0

---

examples/compare-tokens.rs
scylla-cql/src/frame/value.rs
scylla-cql/src/types/serialize/value.rs

With the new rust toolchain version comes a new clippy version, and therefore new complaints of the linter to address. This PR fixes the newly reported issues.

scylla-cql, examples: fix clippy 1.75 issues

---

.github/workflows/rust.yml
scylla-cql/src/types/serialize/value.rs

Fixes: #897, see the issue for details.
Additionally I went ahead and checked that `--no-default-features -F time` also works.

scylla-cql: Use `#[cfg(feature = "time")]` for `time` related `impl SerializeCql`'s

---

scylla-cql/src/macros.rs
scylla-cql/src/types/serialize/row.rs
scylla-cql/src/types/serialize/value.rs
scylla-macros/src/serialize/cql.rs
scylla-macros/src/serialize/row.rs

As requested in https://github.com/scylladb/scylla-rust-driver/issues/899, this PR adds a field attribute to `SerializeCql` and `SerializeRow` macros that allow to skip given field during serialization.
This can be useful for fields unrelated to database.
Fixes: #899

Add `skip` attribute to serialization proc macros

---

examples/allocations.rs
examples/auth.rs
examples/basic.rs
examples/cloud.rs
examples/compare-tokens.rs
examples/cql-time-types.rs
examples/custom_deserialization.rs
examples/execution_profile.rs
examples/get_by_name.rs
examples/logging.rs
examples/parallel-prepared.rs
examples/parallel.rs
examples/query_history.rs
examples/schema_agreement.rs
examples/select-paging.rs
examples/speculative-execution.rs
examples/tls.rs
examples/tracing.rs
examples/user-defined-type.rs
examples/value_list.rs

The following examples use/reuse the following table name and schema:
`"CREATE TABLE IF NOT EXISTS ks.t (a int, b int, c text, primary key (a, b))",`
`basic`
`execution_profile`
`query_history`
`schema-agreement`
`select-paging`
`speculative-execution`
`tls`
The following examples currently use/reuse the `ks.t` table, with a different schema:
`custom_deserializion` uses `"CREATE TABLE IF NOT EXISTS ks.t (pk int primary key, v text)"`
`compare-tokens` uses `"CREATE TABLE IF NOT EXISTS ks.compare_tokens_example (pk bigint primary key)"`
Depending on what order the examples are run/rerun locally, the examples can create inconsistent table schemas for `ks.t` that cause errors in the examples. 
This PR changes the keyspace name in all examples to `examples_ks` and uses the example file name as …

Explicit table naming in examples to prevent errors from shared tables across examples

---

CONTRIBUTING.md
docs/pyproject.toml
docs/source/conf.py
docs/source/connecting/connecting.md
docs/source/data-types/data-types.md
docs/source/execution-profiles/execution-profiles.md
docs/source/load-balancing/default-policy.md
docs/source/load-balancing/load-balancing.md
docs/source/migration-guides/migration-guides.md
docs/source/queries/queries.md
docs/source/quickstart/quickstart.md
docs/source/retry-policy/retry-policy.md
docs/source/speculative-execution/speculative.md
docs/source/tracing/tracing.md
docs/sphinx_preprocessor.py

Related PR: https://github.com/scylladb/sphinx-scylladb-theme/pull/803
This PR replaces Sphinx's deprecated extension recommonmark with myst-parser, as per https://sphinx-theme.scylladb.com/stable/configuration/markdown.html#recommonmark-parser.
Check the docs build and display without errors.

docs: add myst parser

---

CONTRIBUTING.md

This is so that contributors (external or internal) are able to find information about how to deal with failures in min_rust CI job.
Fixes: #912

Add info about Cargo.lock.msrv to Contributing.md

---

scylla/src/transport/cql_types_test.rs

This PR changes `test_naive_date` so that it doesn't rely on current values of `NaiveDate::MIN`. This is necessary because CI broke after update of chrono changed those values.
Fixes: #917

cql_types_test: Don't rely on MIN/MAX values of NaiveDate

---

docs/source/connecting/connecting.md
docs/sphinx_preprocessor.py

#216 showed that best practices of `Session` usage are not obvious and should be stated in documentation.
This PR adds the relevant section that explains how to use it in order to not decrease performance.
Fixes: #216

Docs: Add recommendations about Session usage.

---

.github/workflows/rust.yml
Cargo.lock.msrv
docs/source/data-types/data-types.md
docs/source/data-types/decimal.md
docs/source/quickstart/create-project.md
examples/Cargo.toml
scylla-cql/Cargo.toml
scylla-cql/src/frame/response/cql_to_rust.rs
scylla-cql/src/frame/response/result.rs
scylla-cql/src/frame/value.rs
scylla-cql/src/frame/value_tests.rs
scylla-cql/src/types/serialize/value.rs
scylla-proxy/Cargo.toml
scylla/Cargo.toml
scylla/src/transport/cql_types_test.rs
scylla/src/utils/pretty.rs

Refs: https://github.com/scylladb/scylla-rust-driver/issues/771
- introduced `value::CqlDecimal` type
- hidden public usages of `bigdecimal::Bigdecimal` behind crate feature.
- wrapped `CqlDecimal` with `CqlValue::Decimal`
- updated docs
- updated tests
- added docstrings
- how to implement `PartialEq` for `CqlDecimal`? Note that `CqlDecimal` makes use of `CqlVarint`, so the bytes normalization part can be delegated to `CqlVarint`. However, there is an additional issue, because there are multiple pairs (integer, scale) which can represent the same number. Take for example: `1e3` and `100e1`. I don't think it's trivial to implement the comparison without converting bytes (hexadecimal representation) to decimal number.
- Should I create some macros for code repetitions? There are some parts …

Hide public usages of bigdecimal::BigDecimal behind a crate feature

---

docs/sphinx_preprocessor.py

Preprocessor script was using syntax that works with Python 3.12 but not with older version.
Namely, string in format string using the same delimiter as outer string. Example: f'abc{'def'}xyz'
This commit changes delimiters of inner string to make script compatible with older versions of Python.

Docs: Preprocessor for Python < 3.12

---

.github/workflows/semver_checks.yml
CONTRIBUTING.md
Makefile
scripts/semver-checks.sh

This PR introduces cargo-semver-checks to our CI.
The behavior is very similar to what I described in the issue: https://github.com/scylladb/scylla-rust-driver/issues/906
- On a PR, it sets `semver-checks-breaking` label if the PR breaks API (compared to PR base). Report from the tool, containing info about incompatibilities, is posted as a comment.
- When a tag is pushed, the job will fail if update type (major / minor / patch) was incorrect. This requires new version to NOT be published to crates.io. So we should wait for the workflow to finish before publishing.
Apart from CI integration this PR also modifies `Makefile` and `CONTRIBUTING.MD` to make it easier for contributors to run checks locally.
cargo-semver-checks has some false-negatives and false-positives, so it is NOT a …

Semver checks

---

.github/workflows/rust.yml

Recently, a new issue with CI have arisen. During the `Run tests` step in `build` job, the CI fails due to lack of space on the GH runner machine.
Here is the output of `du -sh target/debug/* && df -h` executed right before the tests on the runner machine:
```
133M	target/debug/build
2.2G	target/debug/deps
3.1G	target/debug/examples
4.6G	target/debug/incremental
8.0K	target/debug/libscylla.d
4.0K	target/debug/libscylla_cql.d
4.0K	target/debug/libscylla_macros.d
8.0K	target/debug/libscylla_proxy.d
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        73G   66G  7.0G  91% /
tmpfs           7.9G  172K  7.9G   1% /dev/shm
tmpfs           3.2G  1.4M  3.2G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sda15      105M  6.1M   99M   6% /boot/efi
/dev/sdb1        74G …
```

CI: cargo clean before tests

---

Cargo.lock.msrv
scylla-cql/Cargo.toml
scylla-cql/src/frame/frame_errors.rs
scylla-cql/src/frame/mod.rs
scylla-cql/src/frame/request/mod.rs
scylla-cql/src/frame/response/mod.rs
scylla-cql/src/frame/types.rs
scylla-proxy/Cargo.toml
scylla/Cargo.toml

Ref: https://github.com/scylladb/scylla-rust-driver/issues/771
I believe this PR closes https://github.com/scylladb/scylla-rust-driver/pull/857.
To stabilize our API, we need to get rid of pre-1.0 crates. One of them is [num_enum](https://docs.rs/num_enum/latest/num_enum/).
This crate allows us to automatically generate conversions from primitive types to enum values - however, its usages needs to be removed from the library.
To get rid of the dependency, we needed to implement converters ourselves.
This is why, we introduce a `TryFromPrimitiveError` struct which holds the information about the enum name and the actual value that we tried to parse.
Apart from that, we implement `TryFrom` for the types that used the `num_enum` crate:
- `impl TryFrom<u16> for Consistency`
- `impl …

Remove num_enum dependency

---

scylla-cql/benches/benchmark.rs
scylla-cql/src/frame/request/mod.rs
scylla-cql/src/frame/request/query.rs
scylla-cql/src/frame/response/mod.rs
scylla-cql/src/frame/response/result.rs
scylla/src/statement/mod.rs
scylla/src/statement/prepared_statement.rs
scylla/src/transport/caching_session.rs
scylla/src/transport/connection.rs
scylla/tests/integration/main.rs
scylla/tests/integration/skip_metadata_optimization.rs

Fixes: https://github.com/scylladb/scylla-rust-driver/issues/169
Currently, the driver does not make a use of an optimization that CQL protocol offers during exeuction of prepared statements. The client is allowed to provide `SKIP_METADATA` flag during `Session::execute`, so the server doesn't attach a result set metadata. The driver can use the cached metadata (received in response to `Session::prepare`) to deserialize the results.
As mentioned previously, the driver can cache the prepared statement's result metadata. This is why we extend the `PreparedStatementSharedData` by `result_metadata` field which holds the metadata. The metadata is obtained from the server during statement preparation (`Session::prepare`). This metadata is eventually passed to the function which deserializes the …

Use prepared statement result metadata to decode rows

---

scylla/src/transport/metrics.rs

Ref: https://github.com/scylladb/scylla-rust-driver/issues/771
`histogram` is an unstable crate and the types introduced by this crate need to be removed from our public API. The only type being used is `histogram::Histogram`.
It's exposed publicly via `MetricsError::Poison`. However, the `MetricsError::Poison` value is never constructed since we always unwrap the `PoisonError` when trying to acquire the lock.
Removed `MetricsError::Poison` and refactored `MetricsError` to be a struct holding an error cause (`&'static str` returned from the `histogram::Histogram` API).

Remove `histogram::Histogram` from public API

---

Cargo.lock.msrv
scylla/Cargo.toml
scylla/src/transport/topology.rs

Ref: https://github.com/scylladb/scylla-rust-driver/issues/771
`strum` and `strum_macros` are unstable crates and their usages need to be removed from the public API to stabilize it.
These crates are responsible for generating `FromStr` implementations for the types.
Replaced `strum` usages for `NativeType` and `ColumnKind` types with our own implementations of `FromStr`.

Remove `strum` and `strum_macros` dependencies

---

.github/workflows/rust.yml
Makefile

This reverts commit 4964b4471c3d14bfea75e532b2e7c24cbd48cd65.
The main reason that `uninlined_format_args` lint was disabled in Rust Driver's CI/Makefile was that inlined variables in format strings had spotty support in rust-analyzer: rust-analyzer did not support renaming variables inside format strings.
Fortunately, rust-analyzer recently gained support for renaming  variables in format strings: rust-lang/rust-analyzer#16027, therefore 4964b4471 can now be reverted. 
Moreover, Rust 1.67.1 downgraded `uninlined_format_args` to pedantic,  meaning that it's disabled by default and we don't have to disable it manually. If it's ever promoted back to an enforced rule by default, we'll be ready to deal with it again (with a proper rust-analyzer  support) - not addressing it now to avoid merge …

Revert "CI/Makefile: disable `uninlined_format_args` clippy lint"

---

.github/workflows/semver_checks.yml

Previously semver checks CI used `/dev/tty` which seems unavailable in Github Actions.
Changed it to `/proc/self/fd/2` which I expect to be available pretty much anywhere.
Changed this CI step so that the job fails on errors. It wouldn't prevent #936 , because this command is part of pipeline, so it won't be affected by `set -e`, but I think it's a good change anyway.
Fixes: https://github.com/scylladb/scylla-rust-driver/issues/936

Fix semver checks

---

.github/workflows/semver_checks.yml

Up until now semver_checks CI posted a new comment after each push to a PR if such push resulted in PR (still) having breaking changes.
This was quite spammy for PRs that intentionally made breaking changes, because each and every push resulted in a new comment.
This commit changes the CI so that it edits already posted comment, and only posts a new one when there was none before.
If there are multiple comments already (as is the case with already open PRs) then the oldest one will be chosen for edit.
The aim is to always have semver status immediately below PR description.
Fixes: https://github.com/scylladb/scylla-rust-driver/issues/938

semver_checks: Edit comment instead of posting new one

---

Cargo.lock.msrv
docs/source/load-balancing/load-balancing.md
examples/Cargo.toml
examples/compare-tokens.rs
examples/custom_load_balancing_policy.rs
scylla/src/transport/cluster.rs
scylla/src/transport/connection_pool.rs
scylla/src/transport/iterator.rs
scylla/src/transport/load_balancing/default.rs
scylla/src/transport/load_balancing/mod.rs
scylla/src/transport/load_balancing/plan.rs
scylla/src/transport/locator/mod.rs
scylla/src/transport/locator/test.rs
scylla/src/transport/node.rs
scylla/src/transport/session.rs
scylla/tests/integration/consistency.rs
scylla/tests/integration/execution_profiles.rs
scylla/tests/integration/utils.rs

This is a more polished version of https://github.com/scylladb/scylla-rust-driver/pull/791
The changes from #791 are:
- Totally reworked commit structure, so that each commit actually compiles and passes all tests and checks. Doing this took quite a lot of time. Original commit structure was... a bit chaotic.
- Fixed all the warnings
- Removed some functions that were no longer used.
- Updated a comment that became incorrect
Posting the original description, slightly modified, as it is still relevant:
Most of our drivers, being inherited from Cassandra, load balance only over nodes, not specific shards. Multiple ideas have arised that could benefit from having a shard-selecting load balancing. Among them:
- **shard-aware batching** (#738);
- **tablets support**:
with tablets enabled (ATM …

Shard selecting load balancing

---

scylla-cql/Cargo.toml
scylla-macros/Cargo.toml
scylla-macros/src/from_row.rs
scylla-macros/src/from_user_type.rs
scylla-macros/src/into_user_type.rs
scylla-macros/src/serialize/cql.rs
scylla-macros/src/serialize/row.rs
scylla-macros/src/value_list.rs
scylla-proxy/Cargo.toml
scylla-proxy/src/actions.rs
scylla-proxy/src/frame.rs
scylla-proxy/src/lib.rs
scylla/Cargo.toml
scylla/src/transport/connection.rs
scylla/src/transport/cql_types_test.rs
scylla/src/transport/execution_profile.rs
scylla/tests/integration/consistency.rs
scylla/tests/integration/hygiene.rs
scylla/tests/integration/utils.rs

Up until now some structs / fields etc were marked as pub despite not being a part of public API.
This is confusing when reading code: in order to know if something is truly public you need to check all the modules up to lib.rs to verify that each appears in some `pub use`.
This PR removes all such occurrences - now something is public if and only if it is marked as pub.
It also enables rustc lint `unreachable-pub` to prevent such occurences in the future.

Remove unreachable pubs

---

scylla/src/transport/session.rs
scylla/src/transport/session_builder.rs
scylla/src/transport/session_test.rs
scylla/src/utils/test_utils.rs

Default values for fetching tracing info are quite strict in the driver: it will make 5 attempts to fetch the data, waiting 3ms between attempts.
For Scylla this is enough, but for Cassandra it is not. For this reason our tests sometimes fail.
This was partially (for one test) fixed previously: https://github.com/scylladb/scylla-rust-driver/commit/61ad8781f1a01c9ec5ff087296229c2245c429b3
This PR fixes other test case that might be affected.
Previous fix used 50 attempts with 200ms wait, I changed it to 200 attempts with 50ms wait in order to not slow down Scylla tests unnecessarily.
Increased default retry attempts in Session from 5 to 10 to make tracing fetching more reliable for Scylla users without increasing latency.
I didn't touch default sleep between attempts - for Scylla new …

session_test: Increase tracing info timeout

---

examples/compare-tokens.rs
scylla/src/routing.rs
scylla/src/transport/load_balancing/default.rs
scylla/src/transport/locator/mod.rs
scylla/src/transport/locator/precomputed_replicas.rs
scylla/src/transport/locator/replication_info.rs
scylla/src/transport/locator/test.rs
scylla/src/transport/locator/token_ring.rs
scylla/src/transport/partitioner.rs
scylla/src/transport/session.rs
scylla/src/transport/session_test.rs
scylla/src/transport/topology.rs

`i64::MIN` turns out to be an invalid value for a token: https://github.com/scylladb/scylladb/blob/4be70bfc2bc7f133cab492b4aac7bab9c790a48c/dht/token.hh#L32
Hashing algorithm should change `i64::MIN` result to `i64::MAX`.
In order to have this check in one place and make sure we always perform it I made `value` field of `Token` non-public and created constructor and getter for it.
Fixes: https://github.com/scylladb/scylla-rust-driver/issues/947

Token: add constructor and normalization

---

scylla/benches/benchmark.rs
scylla/src/lib.rs
scylla/tests/integration/lwt_optimisation.rs

Some definitions in `scylla-cql` crate need to be public, so the `scylla` crate can make use of them. However, currently all of the definitions are implicitly re-exported outside and can be seen by the driver users. The idea is to explicitly re-export the types/functions that should be visible outside (and leave the rest of the public definitions for the internal usage of `scylla` crate).
The main difficulty was to decide on what types should be re-exported publicly. The types that got re-exported can be seen in the documentation (`cargo doc --open`).
I wasn't sure whether error types such as `scylla_cql::frame::frame_errors::FrameError` should be public. As of now, they are left public but this can be further discussed.

Decrease pub visibility of `scylla-cql` definitions

---

examples/custom_load_balancing_policy.rs
scylla/src/transport/load_balancing/default.rs
scylla/src/transport/load_balancing/mod.rs
scylla/src/transport/load_balancing/plan.rs
scylla/tests/integration/consistency.rs
scylla/tests/integration/execution_profiles.rs
scylla/tests/integration/utils.rs

This was already documented as such, but due to an oversight the code was in disagreement with documentation. Approach from the documentation is better, because the currently implemented approach prevented deduplication in Plan from working correctly.
I didn't change deduplication in DefaultPolicy, so currently for unprepared statements everything is deduplicated, and for prepared statements:
- First in plan all are replicas (nodes + shards), properly deduplicated
- Then nodes, also deduplicated
- There is however no deduplication between replicas and nodes, so it's possible for prepared statement plan to first contain replica (node X, Some(n)) and then node (node X, None).
This makes sense to me: if none of the replicas responded, then something is very wrong. We can try different nodes, …

LBP: Return Option<Shard> instead of Shard

---

scylla-cql/src/frame/response/cql_to_rust.rs
scylla-macros/src/from_row.rs
scylla-macros/src/parser.rs
scylla/src/macros.rs

Fixes: https://github.com/scylladb/scylla-rust-driver/issues/852
For some reason, users were not able to derive `FromRow` trait for structs with unnamed fields.
This PR fixes that.
Adjusted `from_row_derive` function from `scylla-macros` so that it supports structs with unnamed fields as well.

derive `FromRow` for structs with unnamed fields

---

Cargo.lock.msrv
docs/pyproject.toml
docs/source/conf.py
docs/source/quickstart/create-project.md
scylla-cql/Cargo.toml
scylla-macros/Cargo.toml
scylla-proxy/Cargo.toml
scylla/Cargo.toml

This is a draft for 0.13 release. 
Steps I'll perform after approval:
```
git checkout main
git merge --ff-only branch-0.13.x
git tag -a v0.13.0
git push origin v0.13.0
git push origin main
cargo publish -p scylla-macros
cargo publish -p scylla-cql
cargo publish -p scylla
```
Proposed release notes:
---
The ScyllaDB team is pleased to announce ScyllaDB Rust Driver 0.13.0,
- over 1,615k downloads on crates!
- over 520 GitHub stars!
**API cleanups / breaking changes:**
- Implemented support for Tablets, a new major architectural feature of Scylla that will be a part of upcoming 6.0 release. This support is required for token (and shard) awareness to work with …

Release 0.13

---

Cargo.lock.msrv
docs/source/data-types/timeuuid.md
examples/Cargo.toml

I decided to give more context for newcomers that want to try Timeuuid in the Rust Driver. Since I didn't had that much experience in the beginning and struggled for a while until understand how to use it.
Also I still didn't understand when and how I should generate the the node_id on `uuid::new_v1([])` parameters and IMHO it would be a great addition to the docs.

docs: adding context to timeuuid using v1 feature

---

docs/source/queries/prepared.md
scylla/src/statement/prepared_statement.rs
scylla/src/transport/session.rs

In response to https://github.com/scylladb/scylla-rust-driver/pull/970#discussion_r1570902278.
Added docstring for `PreparedStatement`, which mentions:
- how to prepare a statement
- benefits of using prepared statements
- statement repreparation that is handled by the driver
- prepared statement cloning
- correlation between prepared statements and schema altering

prepared: docs for `PreparedStatement`

---

scylla-cql/src/types/serialize/row.rs
scylla-cql/src/types/serialize/value.rs
scylla/tests/integration/hygiene.rs

With a new version of Rust toolchain (stable 1.78.0), our never constructed structs used for testing macros began to trigger rustc warnings. Now, they are silenced explicitly using `#[allow(unused)]`.

treewide: silence mock structs unused warning

---

Cargo.lock.msrv
docs/source/logging/logging.md
examples/Cargo.toml
examples/logging_log.rs
scylla-proxy/examples/cmdline.rs
scylla-proxy/examples/identity_proxy.rs
scylla-proxy/examples/identity_shard_aware_proxy.rs
scylla/src/transport/cluster.rs
scylla/src/transport/connection.rs
scylla/src/transport/connection_pool.rs
scylla/src/transport/iterator.rs
scylla/src/transport/load_balancing/default.rs
scylla/tests/integration/utils.rs

Those calls were introduced in e5570956758503a8f0a7ed0ad1c649909f370a73,
with message:
```
Now, when the driver spawns a task to run a new future on it, that
future will use the same subscriber as the code that spawned the task in
the first place.
```
There is unfortunately no explanation about when it is necessary.
I don't see any problems after removing those - logs are still collected correctly using a tracing subscriber.
Those calls however have a harmful side-effect: they prevent usage of `log` loggers to listen to driver logs using `log` feature in `tracing` crate, which was reported in https://github.com/scylladb/scylla-rust-driver/issues/860 .
After reporting the problem to `tracing` crate (https://github.com/tokio-rs/tracing/issues/2913) one of maintainers said that using …

Remove `.with_current_subscriber()` calls

---

scylla-cql/src/frame/mod.rs
scylla-cql/src/frame/value.rs
scylla/src/transport/connection_pool.rs
scylla/src/utils/parse.rs

Clippy started to complain again:
- direct impl of ToString instead of taking advantage of blanked impl over Display,
- no Default impl for LegacySerializedValues,
- assigning result of clone() instead of using clone_from().
The suggestions were applied.

codewide: appease Clippy

---

Cargo.lock.msrv
scylla-cql/Cargo.toml
scylla-cql/src/frame/types.rs
scylla-cql/src/frame/value_tests.rs
scylla-cql/src/types/serialize/row.rs
scylla-cql/src/types/serialize/value.rs
scylla-macros/Cargo.toml
scylla-proxy/Cargo.toml
scylla/Cargo.toml
scylla/src/history.rs
scylla/src/transport/query_result.rs

This is a bunch of preparatory changes to come before the proper deserialization refactor.
To avoid the PR with the first deserialization refactor portion being so big, I extracted them here to be merged sooner.
- `types::write_bytes_opt()` becomes more generic;
- types: return `std::io::Error` instead of `ParseError` where possible - don't unnecessarily broaden the codomain of those functions (not to have to unnecessarily pattern match on their returned error type);
- scylla-cql: add `assert_matches` as dev-dep. It will be helpful in testing deserialization framework, and will also be used in serialization instead of `assert!(matches!(...))`;
- codewide: ditch assert!(matches!(...)) - as assert_matches!(...) provide superior experience (providing helpful debugging messages with how the …

Pre-deserialization-refactor preparatory changes

---

.github/workflows/rust.yml
Cargo.lock.msrv
examples/Cargo.toml
scylla-cql/Cargo.toml
scylla-cql/src/frame/response/cql_to_rust.rs
scylla-cql/src/frame/response/result.rs
scylla-cql/src/frame/value.rs
scylla-cql/src/frame/value_tests.rs
scylla-cql/src/types/deserialize/value.rs
scylla-cql/src/types/serialize/value.rs
scylla/Cargo.toml
scylla/src/transport/cql_types_test.rs

Ref: https://github.com/scylladb/scylla-rust-driver/issues/771
To follow the same naming conventions as for other features, we want to add a crate version numbers to the remaining dependencies hidden behind crate features: `chrono`, `time` and `secrecy`.
I bumped `secrecy` crate version from `0.7.0` to `0.8.0` which is the most recent version.
Renamed following features (and dependencies):
- feature `chrono` => feature `chrono-04`, dependency `chrono` => dependency `chrono_04` (scylla-cql)
- feature `time` => feature `time-03`, dependency `time` => dependency `time_03` (scylla-cql)
- feature `secret` => feature `secrecy-08`, dependency `secrecy` => dependency `secrecy_08`

Rename `chrono`, `time` and `secret` features

---

.github/workflows/authenticate_test.yml
.github/workflows/book.yml
.github/workflows/cassandra.yml
.github/workflows/rust.yml
.github/workflows/semver_checks.yml
.github/workflows/serverless.yaml
.github/workflows/tls.yml
scylla-macros/src/serialize/row.rs
scylla-macros/src/serialize/value.rs
scylla/src/transport/connection.rs

There were two clippy checks that were failing:
- not using `unwrap_or_default` in the code generated by `darling` crate. See the corresponding issue: https://github.com/TedDriggs/darling/issues/293
- usage of legacy numeric constant - `std::i16::MAX`, instead of `i16::MAX`
This PR fixes the issues and makes CI pass.

CI: fix clippy issues

---

docs/Makefile

Related issues: https://github.com/scylladb/sphinx-scylladb-theme/issues/862
This PR addresses an error encountered while building the docs on Mac OS:
> cp -TLr source _source
cp: illegal option -- T
The PR build runs without errors.

docs: support for Mac

---

Cargo.lock.msrv
examples/Cargo.toml
scylla-cql/Cargo.toml
scylla-proxy/Cargo.toml
scylla/Cargo.toml

This is fine now since https://github.com/tokio-rs/tokio/issues/6610 is resolved via https://github.com/becheran/ntest/pull/28 which has now been released in ntest 0.9.3
This PR also bumps the itertools + base64 versions, since they are trivial upgrades
The latest git main branch of scylla-rust-driver fails to build in my project due to the version restriction, these kinds of version restrictions often cause problems like this, so it would be bad for such a version restriction to end up in a release.

Remove tokio version bounds

---

Cargo.lock.msrv
scylla-macros/Cargo.toml
scylla-macros/src/serialize/row.rs
scylla-macros/src/serialize/value.rs

Fix: https://github.com/scylladb/scylla-rust-driver/issues/1015
Bumped darling to v0.20.10. This version of darling appeases the clippy lints - we don't need to disable them anymore.

macros: enable clippy lints after darling fix

---

scylla-cql/src/frame/frame_errors.rs
scylla-cql/src/frame/mod.rs
scylla-cql/src/frame/request/auth_response.rs
scylla-cql/src/frame/response/result.rs
scylla-cql/src/frame/types.rs
scylla-cql/src/types/deserialize/frame_slice.rs
scylla-cql/src/types/deserialize/row.rs
scylla-cql/src/types/deserialize/value.rs
scylla-proxy/src/proxy.rs
scylla/src/transport/locator/tablets.rs

This commit is a small step forward to resolving the issues related to errors in rust driver. The main goal of this PR is to get rid of `ParseError` from `frame::types` module.
As a bonus, the newly introduced deserialization module is adjusted as well. Thanks to that, we remove the cycle in error types (`DeserializationError <-> ParseError`).
- introduced new enum error type returned from types module: `LowLevelDeserializationError`
- changed the return error type of `types::read_*` functions to `LowLevelDeserializationError`
-  replaced `value::BuiltinDeserializationErrorKind::GenericParseError` with new variants
- changed the return error type of `deser_cql_value` to DeserializationError
- replaced …

errors: Low level (de)ser errors

---

scylla/Cargo.toml

With rust 1.80, cfg parameters are checked by the compiler, so that warnings are emitted when unexpected cfg parameter is encountered. As we are using `cfg(scylla_cloud_tests)` to conditionally compile tests applicable for Scylla Serverless Cloud, that parameter is listed in Cargo.toml to prevent warnings.
- ~~[ ] I added relevant tests for new features and bug fixes.

scylla: add scylla_cloud_tests to cfg allowlist

---

.github/workflows/semver_checks.yml

It appears that the update of tame-index from 0.12.1 to 0.12.2 contains API-breaking changes, which result in cargo-semver-checks compilation error. To work around this, a custom setup of cargo-semver-checks is done that pins tame-index to 0.12.1 version.
This should be reverted once tame-index issues 0.12.3 that reverts back the breaking changes, or once cargo-semver-checks issues a new release that works around the problem.

ci: fix semver checks by pinning working dep version

---

scylla/src/transport/topology.rs

It appears that in some clusters there sometimes emerges a transient state that there are some incomplete/invalid peer entries in system tables. Under such circumstances, the driver would throw an error and fail the metadata refresh altogether, eventually leading to critical conditions such as no hosts to query.
To fix this in line with how other drivers approach this, a warning is emitted upon invalid peer entry read, and the entry is skipped with no error returned.
Fixes: #1023
Fixes: #235

topology: skip invalid peers instead of failing

---

.github/workflows/semver_checks.yml

The change in semver-checks turned out to be intentional and `cargo install cargo-semver-checks --no-default-features` is no longer expected to work. 
The replacement command is `cargo install cargo-semver-checks --no-default-features --features gix-reqwest`.
See the release notes for v0.33.0: https://github.com/obi1kenobi/cargo-semver-checks/releases/tag/v0.33.0

semver_checks: Revert previous workaround

---

scylla-cql/src/frame/mod.rs
scylla-cql/src/frame/protocol_features.rs
scylla-cql/src/frame/request/options.rs
scylla-cql/src/frame/request/startup.rs
scylla-cql/src/frame/types.rs
scylla/src/transport/connection.rs
scylla/src/transport/mod.rs
scylla/src/transport/session.rs
scylla/src/transport/session_builder.rs
scylla/tests/integration/main.rs
scylla/tests/integration/self_identity.rs

Resolves: #1028
See #1028.
- `types::write_string_map` was genericised to accept `HashMap`s with keys and values being any form of strings, including `Cow<str>`.
- as majority of keys and significant number of values of STARTUP options are known at compile time and thus statically allocated, `Startup` request now holds `HashMap<Cow<str>, Cow<str>`  instead of `HashMap<String, String>` to reduce needless allocations.
- `setup_tcp_keepalive()` was extracted from `Connection::new()` to reduce clutter.
- keys of SUPPORTED/STARTUP options were extracted as constants to `options` module to have them in one place and avoid using plain string literals in code.
- resolved a dated TODO about whether logic in `open_named_connection` should be part of `Connection::new` - answered the question, …

connection: expose setters for STARTUP options

---

scylla-macros/src/from_row.rs
scylla-macros/src/from_user_type.rs

Using unwraps in macros means the code is compiled as part of the end users build.
This therefore means any lints a user uses will check the macro code as well.
These unwraps therefore the [clippy lint](https://rust-lang.github.io/rust-clippy/master/index.html#/unwrap_used)  `unwrap_used` will throw a warning/error if the user has enabled it.
I wanted to enable this in a project that uses scylla, so i've created this merge request to try and fix this in the least invasive way possible.
I have returned error states where the unwraps were used, but if this feels more in the realm of a `panic` state, then it can simply be swapped for `panic`

Remove Problematic Unwraps In Macros

---

scylla/src/transport/cql_types_test.rs
scylla/src/transport/session_test.rs

As tablets don't support counters yet, they need to be disabled in Counter type tests.
See https://github.com/scylladb/scylladb/commit/c70f321c6f581357afdf3fd8b4fe8e5c5bb9736e.

tests: disable tablets in CQL Counter's tests

---

scylla-cql/src/frame/response/result.rs
scylla/tests/integration/skip_metadata_optimization.rs

A bug is fixed that when `set_use_cached_result_metadata` flag is set, then the `ResultMetadata` would be taken from `PreparedStatement` including `paging_state`, effectively yielding empty paging state for every request with the flag set.
A related regression test is added.

result: fix bug: paging state taken from PREPARED response instead of RESULT

---

scylla-cql/src/errors.rs
scylla-cql/src/frame/frame_errors.rs
scylla-cql/src/frame/response/authenticate.rs
scylla-cql/src/frame/response/error.rs
scylla-cql/src/frame/response/event.rs
scylla-cql/src/frame/response/mod.rs
scylla-cql/src/frame/response/result.rs
scylla-cql/src/frame/response/supported.rs
scylla-cql/src/frame/server_event_type.rs
scylla/src/transport/load_balancing/default.rs

Depends on: https://github.com/scylladb/scylla-rust-driver/pull/1017
We ultimately want to get rid of the `ParseError`. This error type is overloaded with a lot of variants which do not provide much context to the users. In addition, a lot of errors are stringified.
This PR gets rid of `ParseError` from the `frame::response` module which is responsible for CQL response deserialization. This is the place where the usage of `ParseError` is abused the most.
There are multiple types of responses. We introduce a new error type for each of them, e.g. `CqlResultParseError` or `CqlSupportedParseError`. I follow a bottom-to-top approach, starting from implementing an error types for CQL column type deserialization.
Each commit …

errors: Replace `ParseError` with `CqlResponseParseError` in `frame::response` module

---

scylla/src/transport/load_balancing/default.rs
scylla/src/transport/locator/mod.rs

The DefaultPolicy is a complex machinery. In order to grasp it fully, extensive comments are essential.
Some internal functions' names were changed, to make them more better reflect the functions' semantics.

default_lb: Enrich comments & docstrings

---

.github/workflows/semver_checks.yml
Cargo.lock.msrv
scylla-cql/Cargo.toml
scylla-cql/src/frame/response/result.rs
scylla-macros/Cargo.toml
scylla/Cargo.toml
scylla/src/macros.rs
scylla/src/transport/cql_types_test.rs
scylla/src/transport/load_balancing/default.rs
scylla/src/transport/locator/mod.rs
scylla/src/transport/session.rs
scylla/src/transport/session_test.rs
scylla/src/transport/topology.rs
scylla/tests/integration/skip_metadata_optimization.rs

The ScyllaDB team is pleased to announce ScyllaDB Rust Driver 0.13.2,
- over 2,080k downloads on crates!
- over 554 GitHub stars!
**Bug fixes:**
- Made driver issue a warning and continue instead of failing if an invalid peer is encountered in system tables ([#1045](https://github.com/scylladb/scylla-rust-driver/pull/1045))
- Fixed bug that **paged queries would be broken when the recently introduced `use_cached_metadata` flag was set** on a `PreparedStatement`([#1063](https://github.com/scylladb/scylla-rust-driver/pull/1063))
**Documentation:**
- Documented `DefaultPolicy` (Load Balancing) with a lot of comments intended for developers to understand its logic …

Release 0.13.2

---

examples/basic.rs
examples/cql-time-types.rs
examples/schema_agreement.rs
examples/tls.rs
examples/user-defined-type.rs
examples/value_list.rs

Follow-up of https://github.com/scylladb/scylla-rust-driver/pull/1068
In this PR we replace `query_unpaged` occurrences for SELECTs with either `query_iter`.

examples: replace `query_unpaged` for SELECT queries

---

scylla-cql/src/errors.rs
scylla-cql/src/frame/frame_errors.rs
scylla-cql/src/frame/request/query.rs
scylla-cql/src/frame/response/mod.rs
scylla-cql/src/frame/response/result.rs
scylla-cql/src/types/deserialize/result.rs
scylla-cql/src/types/deserialize/value.rs
scylla-cql/src/types/deserialize/value_tests.rs
scylla/src/lib.rs
scylla/src/statement/prepared_statement.rs
scylla/src/transport/caching_session.rs
scylla/src/transport/connection.rs
scylla/src/transport/iterator.rs
scylla/src/transport/query_result.rs
scylla/src/transport/session_test.rs

This PR consists the first bunch of minor preparatory steps for the main leap of the deserialization refactor, extracted from #1057 as @Lorak-mmk requested.
For explanation and broader context see #1057.
Ref: #462

New deserialization API - preparations

---

README.md
docs/source/data-types/blob.md
docs/source/data-types/collections.md
docs/source/data-types/counter.md
docs/source/data-types/date.md
docs/source/data-types/decimal.md
docs/source/data-types/duration.md
docs/source/data-types/inet.md
docs/source/data-types/primitive.md
docs/source/data-types/text.md
docs/source/data-types/time.md
docs/source/data-types/timestamp.md
docs/source/data-types/timeuuid.md
docs/source/data-types/tuple.md
docs/source/data-types/udt.md
docs/source/data-types/uuid.md
docs/source/data-types/varint.md
docs/source/queries/paged.md
docs/source/queries/queries.md
docs/source/queries/result.md
docs/source/queries/simple.md
docs/source/quickstart/example.md

Follow-up of #1061.
Unpaged SELECTs should be discouraged due to the following drawbacks:
> However, `query_unpaged` will return all results in one, possibly giant, piece
> (unless a timeout occurs due to high load incurred by the cluster).
> This:
> - increases latency,
> - has large memory footprint,
> - puts high load on the cluster,
> - is more likely to time out (because big work takes more time than little work,
>   and returning one large piece of data is more work than returning one chunk of data).
- the above caveat is added in the documentation book,
- existing examples are modified to use `query_iter` instead,
- giant bonus: a broad overview over CQL statement kinds is added, together with best practices wrt preparing, batching and paging.
Please make sure (by reading both …

docs: Eradicate unpaged SELECTs and warn about their drawbacks

---

Cargo.lock.msrv
docs/pyproject.toml
docs/source/conf.py
docs/source/quickstart/create-project.md
scylla-cql/Cargo.toml
scylla-macros/Cargo.toml
scylla-proxy/Cargo.toml
scylla/Cargo.toml

Proposed release notes:
```
The ScyllaDB team is pleased to announce ScyllaDB Rust Driver 0.14.0,
- over 2.103k downloads on crates!
- over 556 GitHub stars!
**API cleanups / breaking changes:**
- Our session & paging API was revamped so that it is more intuitive and robust. Now the type of the query (paged / unpaged) is tied to the method used to execute it (`execute_unpaged` / `execute_single_page` / `execute_iter`) rather than the page size associated with the statement object. Other changes include ([#1061](https://github.com/scylladb/scylla-rust-driver/pull/1061)):
- Introduced strongly typed paging state instead of using `Bytes`.
- Paging state is …
```

Release 0.14

---

scylla-cql/src/errors.rs
scylla-cql/src/frame/frame_errors.rs
scylla-cql/src/frame/response/mod.rs
scylla/src/transport/connection.rs
scylla/src/transport/connection_pool.rs
scylla/src/transport/iterator.rs
scylla/src/transport/load_balancing/default.rs
scylla/src/transport/node.rs
scylla/src/transport/session.rs

My main motivation for this PR, was the @Lorak-mmk comment, that currently the `QueryError` contains a `CqlResponseParseError`. `CqlResponseParseError` contains variants which represent a parsing errors which SHOULD NOT appear when executing requests via user API e.g. `CqlAuthChallengeParseError`, which can only happen during connection setup (unless a protocol error appeared, and server sent us an incorrect response, with an incorrect type).
Since `QueryError` is abused everywhere, a lot of changes needed to be introduced before getting rid of the variants mentioned above. However, there are some positives, since we could address some other issues as well.
One of the main entry points for a connection is a …

errors: refactor error types on a connection level

---

scylla/src/transport/cluster.rs
scylla/src/transport/connection_pool.rs
scylla/src/transport/downgrading_consistency_retry_policy.rs
scylla/src/transport/errors.rs
scylla/src/transport/load_balancing/default.rs
scylla/src/transport/retry_policy.rs
scylla/src/transport/speculative_execution.rs

The error refactor that I'm currently working on, surprisingly changed driver's logic in some cases where the decision is made based on the error returned from query execution. There are three places where driver's logic was silently altered:
- retry_policy -> driver should retry execution in case of IoError
- use_keyspace -> if query execution returned IoErrors for some (not all) nodes/connections, these errors should be ignored
- speculative_exeuction -> driver should ignore IoErrors in this context
During error refactor I changed all places where `QueryError::IoError` was constructed. Now all of these IoErrors are represented as `BrokenConnectionError` and `ConnectionPoolError` types (and their variants). These types …

errors: fix driver's logic that bases on error variants returned from query execution

---

scylla-cql/src/frame/frame_errors.rs
scylla-cql/src/frame/mod.rs
scylla-cql/src/frame/request/auth_response.rs
scylla-cql/src/frame/request/batch.rs
scylla-cql/src/frame/request/execute.rs
scylla-cql/src/frame/request/mod.rs
scylla-cql/src/frame/request/options.rs
scylla-cql/src/frame/request/prepare.rs
scylla-cql/src/frame/request/query.rs
scylla-cql/src/frame/request/register.rs
scylla-cql/src/frame/request/startup.rs
scylla-cql/src/frame/response/cql_to_rust.rs
scylla-cql/src/frame/types.rs
scylla-cql/src/frame/value.rs
scylla-cql/src/types/deserialize/mod.rs
scylla-cql/src/types/serialize/row.rs
scylla-proxy/src/errors.rs
scylla-proxy/src/frame.rs
scylla-proxy/src/proxy.rs
scylla/src/transport/connection.rs
scylla/src/transport/errors.rs
scylla/src/transport/load_balancing/default.rs

This PR solves multiple issues:
I introduced a `CqlRequestSerializationError`, with the corresponding variants for each request type. Previously, the request serialization module would return `ParseError`, which did not provide much context.
Decoupled `FrameError` (which originally was overloaded with variants corresponding to serialization and deserialization) into:
- `CqlRequestSerializationError` - in fact, I only moved the variant regarding frame body compression from `FrameError` to `CqlRequestSerializationError`
- `FrameHeaderParseError` - it corresponds to the errors that appear when `Connection::reader()` async task receives a frame, and tries to deserialize its header. It happens before the actual response handler is …

errors: remove ParseError

---

scylla-cql/src/frame/response/cql_to_rust.rs
scylla-macros/src/from_row.rs

Disables `clippy::expect_used` clippy rule for the `derive(FromRow)` macro.
As right now inside `derive(FromRow)` definition, as a part of the produced by this macro code `expect()` is used,
so it also violates and affects the clients code.
For that cases when the consumer of this library enabled `clippy::expect_used` for their project,
it requires to somehow fix it and disable it for the `derive(FromRow)` produced code.
https://github.com/input-output-hk/catalyst-voices/issues/828

Fix clippy `expect_used` complains for `derive(FromRow)` macro

---

scylla/src/statement/prepared_statement.rs
scylla/src/transport/connection.rs
scylla/src/transport/downgrading_consistency_retry_policy.rs
scylla/src/transport/errors.rs
scylla/src/transport/iterator.rs
scylla/src/transport/load_balancing/default.rs
scylla/src/transport/retry_policy.rs
scylla/src/transport/session.rs
scylla/src/transport/speculative_execution.rs
scylla/src/transport/topology.rs

ref: https://github.com/scylladb/scylla-rust-driver/issues/519
In this PR we do a refactor of the `QueryError::ProtocolError` variant, which was represented simply as `&'static str`. In this PR, we create a new type `ProtocolError` which will represent all posible kinds of protocol errors. We simply replace all occurrences of `QueryError::ProtocolError` with a corresponding `ProtocolError` variant.
This variant is no longer use after the fixes. Previously, this variant was constructed for some protocol errors due to limitations of the `QueryError::ProtocolError` variant type (`&'static str`, when `String` was needed). After introducing `ProtocolError` type, this is no longer an issue. This variant can be safely removed.
- ~[ ] …

errors: protocol error refactor

---

scylla/src/transport/connection.rs

The unpaged API should never be called with a paging state different than `PagingState::start()`, so it makes no sense to accept paging state as an argument in `{query,execute}_raw_unpaged`. Therefore, the parameter is removed.
Credits to @Lorak-mmk for noticing this.

connection: remove paging state parameter from unpaged raw API

---

scylla-cql/src/frame/frame_errors.rs
scylla-cql/src/frame/response/mod.rs
scylla-cql/src/frame/response/result.rs
scylla-cql/src/frame/value_tests.rs
scylla-cql/src/types/deserialize/mod.rs
scylla-cql/src/types/deserialize/result.rs
scylla-cql/src/types/deserialize/row.rs
scylla-cql/src/types/deserialize/row_tests.rs
scylla-cql/src/types/deserialize/value.rs
scylla-cql/src/types/deserialize/value_tests.rs
scylla-cql/src/types/serialize/row.rs
scylla-cql/src/types/serialize/value.rs
scylla-macros/src/deserialize/row.rs
scylla-macros/src/deserialize/value.rs
scylla-macros/src/serialize/row.rs
scylla-macros/src/serialize/value.rs
scylla/src/statement/prepared_statement.rs
scylla/src/transport/caching_session.rs
scylla/src/transport/connection.rs
scylla/src/transport/iterator.rs
scylla/src/transport/locator/tablets.rs
scylla/src/transport/query_result.rs
scylla/src/transport/session.rs
scylla/src/transport/session_test.rs

Ref: #462 
This is a necessary step towards non-allocating (in fact less-allocating) result metadata deserialization.
- `ColumnType` is made ownership-generic; there will be two distinct functions to deserialize owned and borrowed `ColumnType`;
- `ColumnSpec` is made ownership-generic; in a follow-up PR, there will be a distinct function to deserialize borrowed `Vec<ColumnSpec<'frame>>`.
- `ResultMetadata` is made ownership-generic;
- `deser_table_spec` no longer allocates; it's up to `deser_col_specs` to allocate or not, depending on desired ownership of deserialized metadata;
- `deser_col_specs` verifies that table specs are the same for all columns. We assume it's true, but the CQL protocol does not enforce it. With that check, we will be able to hold only one table spec per query, not …

make `ResultMetadata` lifetime-generic

---

scylla/src/transport/speculative_execution.rs
scylla/tests/integration/retries.rs

This PR fixes linked bug by simplifying the logic inside the function.
The new logic always checks if the resolved task is the last one, and if so it returns, so it's not possible for the tasks to be exhausted without finishing the `select!`.
This PR also adds regression test for the issue. I verified that the test actually panics without the fix.
Fixes: https://github.com/scylladb/scylla-rust-driver/issues/1085

Fix panic in speculative execution

---

scylla-cql/src/lib.rs
scylla/src/macros.rs

Those macros were accidentally not exported due to different scoping and exporting rules between macros and normal items.

Export serialization migration macros

---

scylla-cql/src/types/deserialize/mod.rs
scylla-cql/src/types/serialize/mod.rs
scylla/src/transport/connection.rs
scylla/src/transport/errors.rs

Sometimes, user might want to downcast `Arc<dyn Error>` to specific error type.
Actually, there is a use case for this in cpp-rust-driver, where we need to define custom `SerializeRow` implementation. It returns a custom error type. We would like to match against it during rust-to-C error conversion - downcasting is thus required.
See: https://github.com/scylladb/cpp-rust-driver/pull/187

errors: expose pub getters for type-erased errors

---

scylla-cql/src/types/serialize/batch.rs
scylla-cql/src/types/serialize/raw_batch.rs
scylla-cql/src/types/serialize/row.rs
scylla-cql/src/types/serialize/value.rs
scylla-cql/src/types/serialize/writers.rs
scylla/src/lib.rs

It is easier to see what is imported, and decide if it should be, if one can see what exactly is imported. This is hard to do with stars, so, as part of API stabilization effort, those are removed here.
This PR also removes raw_batch re-export. This module should not be needed by users.
I verified using semver-checks that the first commit doesn't introduce any breaking changes.

scylla/lib.rs: Remove stars in serialization frameworks imports

---

scylla/src/transport/connection.rs

cpp-rust-driver tests sometimes depend on logs emitted by the driver. HeartbeatTests are on of them. Tests look for a following log: `logger_.add_critera("Heartbeat completed on host " + ccm_->get_ip_prefix());`.
Before this commit, rust-driver was not emitting any logs in case of keepalive request success. I think it's not a bad idea to add a trace log here, considering that keepalive intervals are rather long (default is 30s).
Obviously, the logger criteria will need to
be adjusted in `cpp-rust-driver` tests as well.
- ~[ ] I added appropriate `Fixes:` annotations to PR …

keepalive: trace in case of success

---

scylla/src/transport/locator/tablets.rs

With recent update of rust toolchain, new clippy lints were introduced - `result_large_err` being one of them.
See: https://rust-lang.github.io/rust-clippy/master/index.html#result_large_err
I decided to ignore the lint in `Tablet::from_raw_tablet`.
I justified this decision in the code:
```
// Ignore clippy lints here. Clippy suggests to
// Box<> `Err`` variant, because it's too large. It does not
// make much sense to do so, looking at the caller of this function.
// Tablet returned in `Err` variant is used as if no error appeared.
// The only difference is that we use node ids to emit some debug logs.
```
- ~[ ] I have adjusted the …

clippy: ignore result_large_err clippy lint for Tablet::from_raw_tablet

---

.github/workflows/rust.yml
README.md
scylla-cql/Cargo.toml
scylla-macros/Cargo.toml
scylla-proxy/Cargo.toml
scylla/Cargo.toml

Checking MSRV locally is frustrating, because it requires switching toolchain and renaming files, but it is even more frustrating because updating cargo index before 1.70 is so sloooooow.
1.70 switched to sparse cargo index protocol by default, which makes checking the crate much faster. Let's bump MSRV to improve developer experience.
I also added "rust-version" field to Cargo.toml files, because this is the official place to specify MSRV and in the future will be used by Cargo during dependency resolving.
1.70 is over a year old (released on 1st June 2023), so I doubt this bump will cause any problems.
Related: we will need to decide on MSRV policy past 1.0. I propose to settle on 6 month policy (= our MSRV must always be at least 6 months old). 
Rust ecosystem seems to not be very …

Bump msrv to 1.70

---

scylla-cql/Cargo.toml
scylla-macros/Cargo.toml
scylla/Cargo.toml
scylla/src/cloud/mod.rs
scylla/src/lib.rs
scylla/src/transport/cluster.rs
scylla/src/transport/node.rs
scylla/src/transport/session.rs
scylla/src/transport/session_builder.rs
scylla/src/transport/session_test.rs
scylla/src/transport/topology.rs

This PR enables the `unnameable_types` lint. This lint catches types that are
- `pub`
- Used in some public API
- Not exported - and thus unusable by the user of the driver.
The only situation when this is desired that I know of is creating a sealed trait.
This PR fixes all occurrences of unnameable types and enables the lint so that
we don't introduce more in the future.

Fix unnamable types

---

docs/source/data-types/counter.md

Counter was the only data type that didn't have at least two examples: one for reading and one for writing.
This PR adds the missing example.
Fixes: https://github.com/scylladb/scylla-rust-driver/issues/1099

docs: Add Counter UPDATE example

---

docs/source/execution-profiles/maximal-example.md
docs/source/retry-policy/default.md
docs/source/retry-policy/downgrading-consistency.md
docs/source/retry-policy/fallthrough.md
examples/execution_profile.rs
scylla/src/transport/downgrading_consistency_retry_policy.rs
scylla/src/transport/execution_profile.rs
scylla/src/transport/retry_policy.rs
scylla/src/transport/session_test.rs
scylla/tests/integration/consistency.rs
scylla/tests/integration/execution_profiles.rs
scylla/tests/integration/lwt_optimisation.rs
scylla/tests/integration/retries.rs

This way, when user wants to reuse a retry policy in multiple places, there is no need for an additional allocation for Box (`RetryPolicy::clone_boxed`).

retry_policy: replace all usages of `Box<dyn RetryPolicy>` with `Arc<...>`

---

scylla-cql/src/types/deserialize/row_tests.rs
scylla-cql/src/types/deserialize/value.rs
scylla-cql/src/types/deserialize/value_tests.rs

We have a dedicated type for that and such deserialization decreases type safety.
Ref: https://github.com/scylladb/scylla-rust-driver/issues/1099

Deserialize: don't use i64 for Counter column

---

scylla/src/transport/connection_pool.rs
scylla/src/transport/node.rs

While reading, and trying to understand the hostname resolution and pool refiller logic, I found some places where things could be slightly adjusted. These changes are mostly tiny optimizations and things that aid code readability.

node: tiny optimizations and code refactors

---

scylla-cql/src/frame/response/result.rs
scylla-cql/src/types/deserialize/mod.rs
scylla-cql/src/types/deserialize/result.rs
scylla-cql/src/types/deserialize/row.rs
scylla-cql/src/types/deserialize/row_tests.rs
scylla-cql/src/types/deserialize/value.rs
scylla-cql/src/types/deserialize/value_tests.rs
scylla-macros/src/deserialize/mod.rs
scylla-macros/src/deserialize/row.rs
scylla-macros/src/deserialize/value.rs

Refs: #462
A second lifetime parameter is introduced to entities comprising the bottom part of the new deserialization framework: `'metadata`.
`DeserializeValue` requires two types of data in order to perform deserialization:
1) a reference to the CQL frame (a `FrameSlice`),
2) the type of the column being deserialized, being part of the result metadata.
Similarly, `DeserializeRow` requires two types of data in order to perform deserialization:
1) a reference to the CQL frame (a `FrameSlice`),
2) a slice of specifications of all columns in the row, being part of the result metadata.
When deserializing owned types, both the frame and the metadata can have any lifetime and it's not important. When deserializing borrowed types, however, they borrow from the frame, so their lifetime must …

Parametrize `Deserialize{Value,Row}` with two lifetimes: `'frame` and `'metadata` separately

---

scylla-cql/src/types/serialize/row.rs

Fixes #1043 
This PR implements `SerializeRow` for `Box<T: SerializeRow>`, as suggested by `@piodul` in [Missing SerializeRow impl for Box<dyn SerializeRow> #1043](https://github.com/scylladb/scylla-rust-driver/issues/1043). The aim is to address the user-reported use case where they need to perform batch queries with different length tuples (e.g., one insert into Table A and N inserts into Table B).
I have also added a corresponding unit test (`test_row_serialization_with_boxed_tuple`) to verify the behavior, comparing the serialization of a boxed tuple with that of a regular tuple.
If there are any issues with this implementation, if I misunderstood the assignment, or if this feature would be better placed elsewhere, please let me know, and I'd be happy to make the necessary …

feat(serialize): add `SerializeRow` impl for `Box<T: SerializeRow>`

---

scylla-cql/src/frame/response/result.rs

`generate_deser_type` and `generate_deser_col_specs` are not necessary: generic function is enough.
To ease future development this PR removes those macros.

Remove redundant macros in response/result.rs

---

scylla/src/transport/execution_profile.rs

Depends on: https://github.com/scylladb/scylla-rust-driver/pull/1103
There is a use case for this in cpp-rust-driver.
- ~[] I added relevant tests for new features and bug fixes.~

exec_profile: expose public getters for profile configuration

---

scylla-cql/src/frame/response/result.rs
scylla/src/statement/prepared_statement.rs
scylla/src/transport/iterator.rs
scylla/src/transport/query_result.rs

As `ColumnSpec` is now parametrised by a lifetime, methods that return it implicitly bound its lifetime with lifetime of `&self`. This bug would lead to inefficiencies.
As a fix, an explicit lifetime is added in every method returning `ColumnSpec`.
Ref: https://github.com/scylladb/cpp-rust-driver/pull/200#discussion_r1819118480

result: fix wrong implied lifetime in `col_specs()`

---

scylla-cql/src/frame/mod.rs
scylla-cql/src/frame/types.rs
scylla/src/transport/connection.rs
scylla/src/transport/locator/tablets.rs

Tablets were omitted during migration in #1057.

Migrate tablets to new deserialization framework

---

README.md
docs/source/data-types/blob.md
docs/source/data-types/collections.md
docs/source/data-types/counter.md
docs/source/data-types/date.md
docs/source/data-types/decimal.md
docs/source/data-types/duration.md
docs/source/data-types/inet.md
docs/source/data-types/primitive.md
docs/source/data-types/text.md
docs/source/data-types/time.md
docs/source/data-types/timestamp.md
docs/source/data-types/timeuuid.md
docs/source/data-types/tuple.md
docs/source/data-types/udt.md
docs/source/data-types/uuid.md
docs/source/data-types/varint.md
docs/source/queries/paged.md
docs/source/queries/result.md
docs/source/queries/simple.md
docs/source/quickstart/example.md
docs/source/tracing/basic.md
docs/source/tracing/paged.md

This PR adjusts examples in the Book to the new API, so that the tests compile and pass. This should be merged quickly to bring back the passing Book check to the CI.
Further adjustments of the Book to the new API, including more descriptive tips and a migration guide, are left as a follow-up.
Refs: #462
Depends on: #1057 

Adjust Book examples to the new deserialization API

---

scylla/src/transport/iterator.rs

We failed to find a way to make `TypedRowLendingStream` usable. The borrow checker keeps forbidding making more than one call to `next()` method.
In the close future, we'll investigate alternatives to bring borrowed types deserialization capabilities to `QueryPager`.

iterator: delete `TypedRowLendingStream` as unusable

---

scylla/src/transport/speculative_execution.rs

ref: https://github.com/scylladb/scylla-rust-driver/pull/1083
This is a first iteration of fixing https://github.com/scylladb/scylla-rust-driver/pull/1083 - one we can merge before 0.15. I think this is crucial for speculative execution's performance - current implementation does not ignore any of the DbErrors. If any DbError is returned from database, we return prematurely without further investigation.
Previous implementation did not make much sense. We would prematurely return from speculative execution for some errors which could be ignored.
I adjusted the function, so we use `#[deny(clippy::wildcard_enum_match_arm)]` lint. It will force the developer to think before adjusting this function if new QueryError variant is introduced.
I categorized the errors (see the comments in the …

spec_exec: fix can_be_ignored function

---

docs/source/SUMMARY.md
docs/source/migration-guides/0.15-deserialization.md
docs/source/migration-guides/migration-guides.md
scylla-cql/src/frame/response/cql_to_rust.rs
scylla-cql/src/frame/response/result.rs
scylla-cql/src/lib.rs
scylla/src/lib.rs
scylla/src/macros.rs
scylla/src/transport/caching_session.rs
scylla/src/transport/cluster.rs
scylla/src/transport/iterator.rs
scylla/src/transport/legacy_query_result.rs
scylla/src/transport/query_result.rs
scylla/src/transport/session.rs
scylla/src/transport/session_builder.rs
scylla/src/transport/session_test.rs
scylla/tests/integration/hygiene.rs

Let's reduce friction when migrating to the new deserialization API.
Entities (traits and structs) belonging to the old deserialization API, which we plan to remove soon, are labeled with `#[deprecated]` attribute. This way they will trigger warnings when used, urging users to consider migration.
There already are `Session` and `LegacySession`. However, a viable migration strategy involves incremental migration from the old API to the new API. In such case, it makes sense to have cheap conversions between Session APIs, using the same data underneath. This is done: `LegacySession` is convertible to `Session` and vice versa (and they share the same `Cluster` through an `Arc`).
A migration guide is added. It briefly describes the old and the new deserialization traits and compares them. …

Aid in migration to the new deserialization API

---

docs/source/data-types/udt.md
docs/source/migration-guides/0.11-serialization.md
scylla-cql/src/types/deserialize/mod.rs
scylla-cql/src/types/deserialize/row.rs
scylla-cql/src/types/deserialize/row_tests.rs
scylla-cql/src/types/deserialize/value.rs
scylla-cql/src/types/deserialize/value_tests.rs
scylla-cql/src/types/mod.rs
scylla-cql/src/types/serialize/row.rs
scylla-cql/src/types/serialize/value.rs
scylla-cql/src/types/types_tests.rs
scylla-macros/src/deserialize/row.rs
scylla-macros/src/deserialize/value.rs
scylla-macros/src/lib.rs
scylla-macros/src/serialize/mod.rs
scylla-macros/src/serialize/row.rs
scylla-macros/src/serialize/value.rs
scylla/src/macros.rs

When deserialization macros were introduced in #1024, their attributes differed in naming and usage from those introduced in #851 for serialization derive macros.
This PR aims to unify attributes between `SerializeValue` and `DeserializeValue`, and between `SerializeRow` and `DeserializeRow`, so that both traits can be derived for a struct without a clash in attribute parsing.
Fixes: #462
FINALLY!
1. In `SerializeValue`: `force_exact_match` -> `forbid_excess_udt_fields` (attribute renamed for consistency with `DeserializeValue`);
2. `Flavor` is shared between serialization and deserialization derive macros, and both have the same syntax for choosing the flavor: `flavor = "enforce_order"`;
3. `allow_missing` is supported for `SerializeValue`, as it is in `DeserializeValue`;
4. …

Unify macro attributes between serialization and deserialization derive macros

---

Cargo.lock.msrv
docs/pyproject.toml
docs/source/conf.py
docs/source/quickstart/create-project.md
scylla-cql/Cargo.toml
scylla-macros/Cargo.toml
scylla-proxy/Cargo.toml
scylla/Cargo.toml

The ScyllaDB team is pleased to announce ScyllaDB Rust Driver 0.15.0,
- over 2.516k downloads on crates!
- over 583 GitHub stars!
Beginning with this release, instead of putting all API-breaking changes into one group, now they are in the proper categories, but labeled as ⚠️ **[API-breaking]**.
The main change in this release is the deserialization API refactor. Its primary goal was to reduce overhead caused by all rows being eagerly deserialized to type-erased `CqlValue` type, only then being converted to end user types.
Old traits and structs (`FromCqlVal`, `FromRow`, `QueryResult` - renamed to `LegacyQueryResult`, `RowIterator` - renamed to …

Release 0.15

---

.github/workflows/cassandra.yml
scylla/Cargo.toml
scylla/src/transport/session_test.rs
scylla/src/transport/topology.rs
scylla/src/utils/parse.rs

makes progress towards: https://github.com/scylladb/scylla-rust-driver/issues/1014
The vector type is introduced by the currently in beta cassandra 5.
See: https://cassandra.apache.org/doc/latest/cassandra/reference/vector-data-type.html
Scylla does not support vector types and so the tests are setup to only compile/run with a new cassandra_tests config.
This commit does not add support for retrieving the data via a SELECT.
That was omitted to reduce scope and will be implemented in follow up work.
I have split off support for CREATE/INSERT since I value the early feedback of small PRs.
I didnt realize that @pkolaczk had shown interest in implementing this until after I'd went to submit my PR.
Hopefully I've not stepped on any toes.
The cassandra docker-compose.yaml is changed to 5.0 beta …

cassandra 5.0 vector type CREATE/INSERT support

---

docs/source/data-types/date.md
docs/source/data-types/time.md
docs/source/data-types/timestamp.md

Changes `chrono` -> `chrono-04` to reflect the new name for the feature flag. This was confusing when I was trying to find the feature flag.

Update time docs to reflect new chrono feature flag name

---

scylla/src/history.rs
scylla/src/lib.rs
scylla/src/transport/load_balancing/default.rs
scylla/src/transport/mod.rs
scylla/src/utils/mod.rs
scylla/src/utils/test_utils.rs
scylla/tests/integration/authenticate.rs
scylla/tests/integration/consistency.rs
scylla/tests/integration/cql_collections.rs
scylla/tests/integration/cql_types.rs
scylla/tests/integration/cql_value.rs
scylla/tests/integration/default_policy.rs
scylla/tests/integration/execution_profiles.rs
scylla/tests/integration/history.rs
scylla/tests/integration/large_batch_statements.rs
scylla/tests/integration/lwt_optimisation.rs
scylla/tests/integration/main.rs
scylla/tests/integration/retries.rs
scylla/tests/integration/shards.rs
scylla/tests/integration/silent_prepare_batch.rs
scylla/tests/integration/silent_prepare_query.rs
scylla/tests/integration/skip_metadata_optimization.rs
scylla/tests/integration/tablets.rs
scylla/tests/integration/utils.rs

This is the first step towards improved integration tests.
Tests that require a running cluster should be in integration tests.
This PR moves some of such tests. Not all - for that there are a few other changes needed, but I wanted to merge what I already have.
Ref: https://github.com/scylladb/scylla-rust-driver/issues/1097
Fixes: https://github.com/scylladb/scylla-rust-driver/issues/1048

Move some tests to integration

---

examples/cqlsh-rs.rs
scylla-cql/src/frame/request/batch.rs
scylla-cql/src/frame/request/execute.rs
scylla-cql/src/frame/request/mod.rs
scylla-cql/src/frame/request/prepare.rs
scylla-cql/src/frame/request/query.rs
scylla-cql/src/frame/response/result.rs
scylla-cql/src/frame/value.rs
scylla-cql/src/types/deserialize/result.rs
scylla-cql/src/types/serialize/batch.rs
scylla-cql/src/types/serialize/raw_batch.rs
scylla-cql/src/types/serialize/row.rs
scylla-cql/src/types/serialize/writers.rs
scylla-macros/src/deserialize/row.rs
scylla-macros/src/deserialize/value.rs
scylla-macros/src/serialize/row.rs
scylla-macros/src/serialize/value.rs
scylla/src/statement/batch.rs
scylla/src/statement/prepared_statement.rs
scylla/src/transport/cluster.rs
scylla/src/transport/connection.rs
scylla/src/transport/legacy_query_result.rs
scylla/src/transport/load_balancing/default.rs
scylla/src/transport/load_balancing/plan.rs
scylla/src/transport/locator/mod.rs
scylla/src/transport/locator/replicas.rs
scylla/src/transport/locator/tablets.rs
scylla/src/transport/session.rs
scylla/src/utils/pretty.rs

This PR fixes CI, by fixing the:
- formatting errors - some changes to `cargo fmt` were introduced in 1.83
- compiler warnings - these are regarding elision of lifetimes that are already declared
- clippy lints

rust: appease compiler, formatter and linter from toolchain 1.83

---

.github/workflows/rust.yml
scylla/Cargo.toml
scylla/src/lib.rs
scylla/src/transport/query_result.rs

This is convenience introduced only for cpp-rust-driver purposes.
We will use DeserializedMetadataAndRawRows directly to implement lazy deserialization in cpp-rust-driver

rows_result: implement into_inner behind `cpp_rust_unstable` cfg

---

scylla-cql/src/types/serialize/row.rs
scylla-cql/src/types/serialize/value.rs
scylla-macros/src/serialize/row.rs
scylla-macros/src/serialize/value.rs
scylla/src/macros.rs

When trying to serialize a row that isn't a valid rust identifier, the macro fails to expand due to the invalid rust identifier being used when creating variables for the derived implementation. This PR fixes that such that those variables are driven by the field identifier rather than the column name. 
In particular, this occurs when trying to serialize a dynamic TTL that would be using in a query such as:
```cql
INSERT INTO my_table (/* snip cols */) VALUES((/* snip cols */) USING TTL ?
```
The struct desired for serialization is:
```rust
struct InsertRow {
#[scylla(rename = "[ttl]"]
ttl: i32,
/* snip cols */
}
```
However, in the current version of the driver this fails because it tries to create a variable called `visited_flag_[ttl]` which is not a valid rust identifier. As far as I …

Allow serialization of "columns" that are not valid rust identifiers

---

scylla/src/transport/connection_pool.rs

PoolRefiller::use_keyspace took keyspace_name by ref even though it actually needs the ownership, so it had to clone it. Taking by value removes this clone.

refiller: Remove unnecessary clone

---

scylla-cql/src/types/serialize/raw_batch.rs
scylla/tests/integration/batch.rs
scylla/tests/integration/main.rs

When executing batch statement, the amount of statements should be equal to amount of batch values.
This is checked in `scylla-cql/src/frame/request/batch.rs` in impl of `Batch`, specifically it's `do_serialize` method.
This method iterates over statements, serializes the statement and serializes the values for the statement.
If the value iterator returns `None`, then  there were not enough values, so it returns an error.
After serialization it verifies that the iterator is finished - if it is not, then there are too many values.
The problem is that the length of `RawBatchValuesIteratorAdapter` is limited to the amount
of statements, because all of it's methods first try to get next serialization context, and if it is not present, return `None`.
This limits the length of this iterator to …

Make RawBatchValuesIteratorAdapter length equal to its internal BatchValuesIter length

---

scylla-macros/src/deserialize/mod.rs
scylla-macros/src/serialize/row.rs
scylla-macros/src/serialize/value.rs

It is customary that auto-generated trait impls have that attribute. Also, this disables dead code analysis for derived impls.
Fixes: #1140 

macros: generate automatically_derived attribute

---

scylla/src/transport/errors.rs

This seems like an accidental omission. Without these fields being public it is impossible to match on the error type.

Make fields of ConnectionSetupRequestError public

---

scylla-cql/src/frame/value.rs
scylla-cql/src/types/serialize/mod.rs
scylla-cql/src/types/serialize/row.rs
scylla/src/transport/errors.rs

`SerializeValuesError` is part of the legacy serialization API, so it should be deprecated as well.
Refs: #1139

Remove uses of `SerializeValuesError` and deprecate it

---

docs/source/data-types/decimal.md
docs/source/data-types/varint.md
scylla-cql/src/frame/value.rs
scylla-cql/src/types/deserialize/value.rs
scylla-cql/src/types/deserialize/value_tests.rs
scylla-cql/src/types/serialize/value.rs

This PR introduces borrowed versions of CqlDecimal and CqlVarint. It implements SerializeValue and DeserializeValue for new types.
There is a use case for this in cpp-rust-driver - we need to set the pointer user provided, so it points to the underlying data. After lazy-deserialization refactor in cpp-rust-driver, CqlDecimal is not useful anymore. If we deserialize to CqlDecimal, it owns the bytes and is a stack variable - thus, we cannot set the pointer to its underlying data (it will be freed after function call).
Questions for reviewers:
- Should I put it under #[cfg(cpp_rust_unstable]? I think it may be useful for other users as well.
- I only implemente `From<Cql[Varint/Decimal]Borrowed> for Big[Int/Decimal]`. I didn't implement conversions in other direction, since new types borrow …

value: `Cql[Varint/Decimal]Borrowed`

---

README.md

crates.io doesn't handle relative links well, so currently our logo is not visible on crates.io :(
Relevant crates.io issue: https://github.com/rust-lang/crates.io/issues/9939
This PR changes the link to be absolute so that we are not bitten by this again.
It is a bit sad to do this, because now you need internet to render the README locally, and it just feels a bit wrong
to refer to the outside file instead of the file in the same filetree, but I don't see any better option for now.
OTOH if we ever decide to change the logo, the new one will be automatically visible in any place that uses absolute link, which is a plus.

README: Use absolute link for image

---

scylla/src/transport/caching_session.rs

The previous derived implementation was not actually usable because it had `Debug` bounds on the type parameters. The `RandomState` default value for the `S` argument does not impl `Debug`, so this didn't work.
This commit switches to a manual `Debug` impl that doesn't have these unnecessary bounds.

Add working `Debug` impl for caching session

---

scylla/src/transport/session.rs

During error refactor, I found it hard to understand what which function does on a request execution path. Three different names were used:
- `run_query`
- `execute_query`
- `do_query`
I renamed them (and all internal structures/traits related to these functions). The `_query`  part is very misleading. It would suggest that we want to execute a CQL QUERY request, which is not true - these functions/closures are generic and allow to execute QUERY, EXECUTE and BATCH CQL requests.
Kind of related to https://github.com/scylladb/scylla-rust-driver/issues/713

session: adjust naming in internal session functions

---

scylla/src/errors.rs
scylla/src/network/connection.rs

Current `RequestError` is a low-level (connection layer) error that represents a failure of ANY CQL request. Before this PR it was public. Why? There was only one place it was used in public API - namely `BrokenConnectionErrorKind::KeepaliveQueryError`. This is a very rare error.
I decided to make this error type `pub(crate)` for multiple reasons:
- As mentioned previously - this is a very rare low-level error kind. I don't think there is a point in exposing it to the user
- Thanks to that, we can rename it to `InternalRequestError` (since it becomes an error used only in driver's internals)
- `RequestError` name is now available :). It can be used for some more meaningful error returned from user-facing API. For example, an …

errors: rename RequestError and make it private

---

scylla/src/client/pager.rs
scylla/src/client/session.rs
scylla/src/client/session_test.rs
scylla/src/cluster/metadata.rs
scylla/src/errors.rs
scylla/src/network/connection.rs
scylla/src/policies/load_balancing/default.rs
scylla/src/policies/load_balancing/mod.rs
scylla/src/policies/retry/default.rs
scylla/src/policies/retry/downgrading_consistency.rs
scylla/src/policies/retry/fallthrough.rs
scylla/src/policies/retry/mod.rs
scylla/src/policies/retry/retry_policy.rs
scylla/src/response/request_response.rs
scylla/tests/integration/execution_profiles.rs

To narrow the error return types of some important API functions (e.g. `RS::decide_should_retry` and `LBP::on_query_failure`), the error type of `execute_request_once` (previously known as `do_query`) needs to be adjusted as well. A couple of commits at the beginning of this PR do just that. What we achieve, is that we narrow the return error type of the closure from `QueryError` to `UserRequestError`.
This error is renamed to `RequestAttemptError` - as the name suggests, it represents a failure of a single attempt of execution.
Both of these traits accept some error and do something based on the error. Before this PR, they would accept a `QueryError`, resulting in matches against variants that could never even be constructed …

session: internal request execution API error types refactor

---

scylla/src/client/pager.rs
scylla/src/client/session.rs
scylla/src/cluster/metadata.rs
scylla/src/cluster/state.rs
scylla/src/network/connection_pool.rs
scylla/src/observability/driver_tracing.rs
scylla/src/routing/locator/mod.rs
scylla/src/routing/locator/replicas.rs
scylla/src/routing/locator/replication_info.rs
scylla/src/utils/pretty.rs

This is a bunch of tiny optimisations around reducing number of allocations.

codewide: small performance optimisations

---

.github/workflows/authenticate_test.yml
.github/workflows/tls.yml
test/tls/scylla.yaml

Stop using custom images.
We used to use `scylladb/scylla-passauth` and `scylladb/scylla-tls` in our pipeline.
They were based on old scylla and has minimal config changes on them.
This PR removes them, to eleviate burdain to keep them updated.
Instead it makes them build on fly or just patch config via docker image cli.

Get rid of custom scylla images

---

scylla/src/client/pager.rs
scylla/src/client/session.rs
scylla/src/errors.rs
scylla/src/observability/history.rs
scylla/src/policies/speculative_execution.rs
scylla/tests/integration/history.rs

Error type returned by `run_request_speculative_fiber`. It represents either a definite request failure - last attempt error, connection pool error, or an empty plan error.
This error variant was not good for 2 reasons:
1. it contains stringified error message
2. it was used for both user requests timeouts, and schema agreement timeouts
I decoupled this variant into two separate variants that provide more context.
After refactoring the timeout errors in `QueryError`, I added the corresponding variant to `RequestError` (one introduced in this PR) as well.
`log_query_error` (or rather `log_request_error` after rename) now accepts `RequestError`. `log_attempt_error` now accepts `RequestAttemptError` (representing an error of a …

errors: narrow error types accepted by `HistoryListener`

---

scylla/src/client/pager.rs
scylla/src/client/session.rs
scylla/src/cluster/metadata.rs
scylla/src/network/connection.rs
scylla/src/statement/batch.rs
scylla/src/statement/prepared_statement.rs

There are three main objectives:
It's yet another module where usage of `QueryError` was abused. It's taken care of in this PR
They now return a self-contained `NextRow` error. It's independent of `QueryError`.
Currently all top-level metadata related functions/methods (e.g. `Session::refresh_metadata`) return `QueryError`. This is because low-level methods use `QueryPager` API under the hood. Before this PR, the pager API would return `QueryError`. In the follow-up PR we will continue on purging the metadata methods of `QueryError`. It will be replaced with an error type designated for these operations - namely `MetadataError`.
- ~[ ] I have adjusted the …

errors: pager API errors refactor

---

scylla/src/network/connection.rs
scylla/src/routing/mod.rs
scylla/src/routing/sharding.rs

Ref: https://github.com/scylladb/scylla-rust-driver/pull/1170
The only breaking change in this PR is unpubbing `ShardingError`. Remaining commits adjust the internal usages of this error - for example logging in case parsing of sharding info fails.

errors: adjust ShardingError

---

scylla-cql/benches/benchmark.rs
scylla-cql/src/deserialize/mod.rs
scylla-cql/src/deserialize/result.rs
scylla-cql/src/deserialize/row_tests.rs
scylla-cql/src/deserialize/value.rs
scylla-cql/src/deserialize/value_tests.rs
scylla-cql/src/frame/frame_errors.rs
scylla-cql/src/frame/request/mod.rs
scylla-cql/src/frame/response/result.rs
scylla-cql/src/frame/value_tests.rs
scylla-cql/src/serialize/row.rs
scylla-cql/src/serialize/value.rs
scylla-cql/src/types_tests.rs
scylla-macros/src/deserialize/value.rs
scylla-macros/src/serialize/value.rs
scylla/benches/benchmark.rs
scylla/src/client/session_test.rs
scylla/src/cluster/metadata.rs
scylla/src/lib.rs
scylla/src/response/legacy_query_result.rs
scylla/src/response/query_result.rs
scylla/src/routing/locator/tablets.rs
scylla/src/statement/prepared_statement.rs
scylla/src/utils/parse.rs
scylla/src/utils/pretty.rs
scylla/tests/integration/cql_value.rs
scylla/tests/integration/hygiene.rs

This PR removes `CqlType` (used in schema metadata) and replaces its usages with `ColumnType` (used in statement metadata).
Initially those two structures were quite different, so most of the commits are done to make them mostly identical, which made the unification possible.
CqlType was split into subtypes (native type, collection type, tuple, UDT) as defined by https://cassandra.apache.org/doc/stable/cassandra/cql/types.html
ColumnType was fully inlined - it had a variant for each possible type.
I decided to change ColumnType in this regard to follow CqlType, because CqlType's approach seems to be much more elegant.
CqlType contained frozen flag, because the schema contains information about whether the collection/UDT is frozen or not.
ColumnType did not contain such flag, because this …

Remove CqlType in favor of ColumnType

---

.github/workflows/authenticate_test.yml
test/cluster/docker-compose-passauth.yml

Github actions do not have API to override entrypoint, we have to switch to `docker-compose` to start container for auth tests.

cicd: fix authenticate tests

---

scylla/src/client/session.rs
scylla/src/cluster/metadata.rs
scylla/src/cluster/worker.rs
scylla/src/errors.rs

The goal of this PR is to purge `metadata.rs` of `QueryError`, and replace it with `MetadataError`. Thanks to that metadata related functions are now independent of `QueryError`.
I tried to split this PR into commits, so each commit handles one function/method from metadata module. New error variants are introduced where necessary.
When it comes to public API - after this PR `Session::refresh_metadata()` will now return `MetadataError`.

errors: metadata errors refactor

---

scylla/src/client/session.rs
scylla/src/client/session_test.rs
scylla/src/cluster/node.rs
scylla/src/cluster/worker.rs
scylla/src/errors.rs
scylla/src/network/connection.rs
scylla/src/network/connection_pool.rs

`NewSessionError` has a lot of variants that can't even be constructed. This is all because of `From<QueryError> for NewSessionError` implementation. The only remaining execution path where we make use of this conversion is USE KEYSPACE request execution. (Previously, there was also `MetadataReader::read_metadata` that returned `QueryError`, but this was addressed in previous PR).
This is why we narrow the return error types in USE KEYSPACE execution path - from `QueryError` to new `UseKeyspaceError`.

errors: refactor errors on USE KEYSPACE execution path and clean up NewSessionError

---

docs/source/queries/schema-agreement.md
docs/source/queries/timeouts.md
examples/schema_agreement.rs
examples/tower.rs
scylla/src/client/caching_session.rs
scylla/src/client/session.rs
scylla/src/client/session_test.rs
scylla/src/cluster/state.rs
scylla/src/errors.rs
scylla/src/network/connection.rs
scylla/src/response/request_response.rs
scylla/src/statement/batch.rs
scylla/src/statement/prepared_statement.rs
scylla/src/utils/test_utils.rs
scylla/tests/integration/batch.rs
scylla/tests/integration/large_batch_statements.rs
scylla/tests/integration/tablets.rs
scylla/tests/integration/utils.rs

Step forward: https://github.com/scylladb/scylla-rust-driver/issues/713
As the PR titles says, this PR renames the `QueryError` to `ExecutionError`. I also checked the mentions of the QueryError in the docs - last commit adjusts the docs regarding the error returned in case of schema agreement timeout. 

errors: rename `QueryError` to `ExecutionError`

---

scylla/src/errors.rs

errors: remove BadQuery::Other variant

---

docs/source/schema/schema.md
examples/compare-tokens.rs
scylla/src/client/pager.rs
scylla/src/client/session.rs
scylla/src/client/session_test.rs
scylla/src/cluster/state.rs
scylla/src/cluster/worker.rs
scylla/src/policies/load_balancing/default.rs
scylla/src/policies/load_balancing/plan.rs
scylla/src/utils/test_utils.rs
scylla/tests/integration/tablets.rs
scylla/tests/integration/utils.rs

There were multiple places where `ClusterState` was still referred to as `ClusterData`:
- `Session::get_cluster_data()`,
- `Cluster::get_data()`,
- variable names,
- comments and docstrings.
All were renamed.
Supplements #1163.

codewide: rename remnants of cluster data to state

---

scylla/src/client/caching_session.rs
scylla/src/client/session.rs
scylla/src/cluster/state.rs
scylla/src/errors.rs

As noticed by @wprzytula , after renaming `QueryError` to `ExecutionError` it is clear that `Session::prepare` should not return such error. This is why we introduce a `PrepareError` - an error that occurred during statement preparation. It's returned by `Session::prepare` method.

errors: introduce PrepareError

---

scylla/src/utils/test_utils.rs

Despite previous measures (sending all DDL queries to a single node) this error is still haunting our CI. I see no better way of patching this on our side than retrying.

Retry DLL queries upon group 0 concurrent modification error

---

.github/workflows/tls.yml
test/tls/docker-compose-tls.yml

Commit https://github.com/scylladb/scylla-rust-driver/commit/188964e0be36e035ada0b1d12e6af70a832230c6 assumed that `build` is supported by `github actions services`.
Which is not, so, move to `docker-compose` instead of `services`.

cicd: fix tls tests

---

scylla/src/client/session.rs
scylla/src/errors.rs

It was previously called `TracingProtocolError` and was contained in ExecutionError::ProtocolError.
Since we now have a big picture of errors hierarchy, it's much clearer that `TracingError` should be a separate error type returned by tracing methods. ExecutionError should NOT depend on it.
This PR renames TracingProtocolError to TracingError, and changes the return type of Session::get_tracing_info(). New variant is introduced to `TracingError` - it contains an `ExecutionError`, which makes sense since we try to execute queries to system tracing tables.

errors: rename and extract TracingError

---

scylla/src/client/caching_session.rs
scylla/src/client/pager.rs
scylla/src/client/session.rs
scylla/src/errors.rs
scylla/src/network/connection.rs

`NextPageError` and `NextRowError` were introduced specifically for `QueryPager` API. Currently (before this PR), the top-level Session methods `[execute/query]_iter()` return a `ExecutionError`. This is why `NextRowError` variant is present in `ExecutionError`. To remove that, we can narrow the return error type of these methods.
There is one subtle thing to pay attention to (and potentially discuss). `query_iter` method potentially prepares the statement (if values are not empty). `Session::prepare` currently returns a `ExecutionError`. This is why newly introduced `PagerExecutionError` now depends on `ExecutionError.` The question is whether we should narrow the return error type of `Session::prepare` to some new error type …

errors: Narrow return error type of Session::[query/execute]_iter

---

scylla-cql/src/frame/frame_errors.rs

In #1135 we removed a check for the table spec across different column specs. Since we wanted to release it in a patch release, the corresponding error variant was not removed (not to introduce API breaking changes).
This commit removes the unused variant.

f_errors: remove unused variant from ColumnSpecParseErrorKind

---

examples/schema_agreement.rs
scylla-cql/src/frame/response/error.rs
scylla/src/client/session.rs
scylla/src/client/session_test.rs
scylla/src/cluster/state.rs
scylla/src/errors.rs
scylla/src/network/connection.rs
scylla/src/policies/load_balancing/default.rs
scylla/src/policies/speculative_execution.rs
scylla/src/response/request_response.rs
scylla/src/statement/prepared_statement.rs
scylla/src/utils/test_utils.rs
scylla/tests/integration/batch.rs

Fixes: https://github.com/scylladb/scylla-rust-driver/issues/519
This PR originated from our offline discussion with @Lorak-mmk .
We remove this type altogether. We noticed that this error type was a catch-all for sub-errors/variants we did not know where to put otherwise.
Before this PR, it would contain a lot of top-level variants without providing some meaningful context for them. Most of the variants came from the `RequestAttemptError::into_execution_error` method.
We decided  that it's best to inline `RequestAttemptError`, so users have additional context about how request execution looks like when they match the error. It allows us to remove a lot of variants from ExecutionError and ProtocolError (which is later removed).
New error type - returned by public API related to awaiting …

errors: final cleanups (restructure ExecutionError and introduce SchemaAgreementError)

---

scylla-cql/src/value.rs

In our project we have multiple structures that derive `SerializeRow` and we often want to print them, but as `MaybeUnset` doesn't implement `Debug` we are forced to manually implement it.

Implement (derive) Debug for MaybeUnset

---

scylla/benches/benchmark.rs
scylla/src/client/pager.rs
scylla/src/client/session_test.rs
scylla/src/routing/partitioner.rs
scylla/src/statement/prepared_statement.rs

We want to extract `session_test.rs` to integration tests directory - out of `scylla` crate.
Tests in `session_test.rs` call `get_partitioner_name()` to assert some things. We must therefore expose `get_partitioner_name().
1. `PartitionerName` and `PreparedStatement::get_partitioner_name()` are made `pub`.
2. `PartitionerName` gets missing `Eq` impl and `#[non_exhaustive]` attribute.
3. `calculate_token_for_partition_key()` now accepts `PartitionerName` instead of `impl Partitioner`.
4. `Partitioner(Hasher)` traits and their impls are un`pub`bed.
Implemented `Debug` for `QueryPager` and `TypedRowStream`.
- ~~[ ] I have adjusted the …

`partitioner`: Change visibility of  `Partitioner`-related items

---

scylla/tests/integration/main.rs
scylla/tests/integration/query_result.rs

Add tests for {query,execute}_iter API

---

scylla/tests/ccm_integration/ccm/ip_allocator.rs

When passing `NetPrefix` as an argument to `ccm populate` it is
formatted using `.to_string()` method. Result of this is then concatenated
with the node id, and the result is an "ip" that ccm tries to find in
Scylla logs to determine that the node is UP.
`.to_string()` implementation was displaying the whole ip, instead of
it's first 3 octets, resulting in CCM looking for ips like `127.0.1.02`.
Instead the `to_str()` method should be used, that produces ccm-compatible
form of the ip range.

Fix improper ip address formatting in CCM integration.

---

scylla/tests/ccm_integration/ccm/cluster.rs

It will allow to use the 'stop' method just providing "None" parameter:
```
... .stop(None).await;
```

ccm: Make 'opts' parameter of the 'stop' method be optional

---

scylla/src/cluster/metadata.rs
scylla/src/network/connection.rs
scylla/src/utils/test_utils.rs
scylla/tests/integration/history.rs
scylla/tests/integration/new_session.rs
scylla/tests/integration/utils.rs
test/cluster/docker-compose-passauth.yml
test/cluster/docker-compose.yml
test/tls/docker-compose-tls.yml

Full scan requests are slower even if there is only one record.
Fixes: https://github.com/scylladb/scylla-rust-driver/issues/1244

Make any query on system.local go with WHERE clause

---

scylla/src/client/pager.rs
scylla/src/response/query_result.rs
scylla/src/statement/prepared_statement.rs
scylla/tests/integration/main.rs
scylla/tests/integration/statement.rs

Fixes: https://github.com/scylladb/scylla-rust-driver/issues/1132
The motivation is described in the issue - TLDR, there is a return type discrepancy between `PreparedStatement` and `QueryRowsResult/QueryPager` methods.
- refactored `ColumnSpecs` wrapper - adjusted it to two lifetimes so it can be used in `PreparedStatement`'s API
- removed `ColumnSpecView` and `TableSpecView` - these are redundant
- adjusted `PreparedStatement` API to `ColumnSpecs`
- introduced a small integration test case for `PreparedStatement` metadata. The methods used to get col specs (bind markers and result set) were not tested anywhere.
Originally, I (others as well - based on the discussion in the issue) wanted to remove `ColumnSpecs` wrapper. But then, when I did that and started to adjust the test cases, I …

Refactor `ColumnSpecs` and adjust `PreparedStatement` API

---

scylla-cql/src/frame/response/result.rs

This will allow us to introduce support for new column types in the future without breaking the API.
I did not mark `UserDefinedType` as non_exhaustive. It probably won't ever be extended by additional fields.

result: mark ColumnType and related enums as non-exhaustive

---

Cargo.lock.msrv
examples/Cargo.toml
examples/custom_load_balancing_policy.rs
scylla-proxy/Cargo.toml
scylla-proxy/src/actions.rs
scylla-proxy/src/proxy.rs
scylla/Cargo.toml
scylla/src/cluster/metadata.rs
scylla/src/network/connection_pool.rs
scylla/src/policies/load_balancing/default.rs
scylla/src/policies/load_balancing/plan.rs
scylla/src/routing/locator/mod.rs
scylla/src/routing/partitioner.rs
scylla/src/routing/sharding.rs

Also updates the following to align versions and avoid duplicates in transitive dependencies
* `rand_pcg` 0.3.1 -> 0.9.0
* `rand_chacha` 0.3.1 -> 0.9.0
MSRV for all changes is 1.63, so should hopefully be good
I'm currently trying to reduce the number of duplicate dependencies to reduce some bloat in my projects, and `rand` is one of them.

Update `rand` crate 0.8.5 -> 0.9.0

---

scylla-cql/src/serialize/row.rs
scylla/Cargo.toml
scylla/benches/benchmark.rs
scylla/src/client/session_test.rs
scylla/src/cluster/metadata.rs
scylla/src/cluster/state.rs
scylla/src/errors.rs
scylla/src/lib.rs
scylla/src/routing/partitioner.rs

Some APIs on ClusterState still accept SerializedValues instead of `impl SerializeRow` / `&dyn SerializeRow`.
This is a leftover from the old serialization API, and should be changed. Why? Because there is no easy way for the user to create the SerializedValues.
That means that if a user wants to calculate the token / replicas, for some partition key of some table they need to:
- Get the `Table` struct from `ClusterState`
- Create new SerializedValues
- Iterate over `partition_key` field and retrieve relevant `ColumnSpec`s from `columns` field.
- For each column, call `add_value` on the SerializedValues and handle the error
- Pass the result to `compute_token` / `get_endpoints`
This is a lot of unnecessary work.
This PR changes those methods to accepts `&dyn SerializeRow`.
As a small side …

Remove SerializedValues from public API of `scylla` crate.

---

scylla/src/lib.rs
scylla/src/statement/batch.rs
scylla/src/statement/prepared.rs

- Marked some enums as non_exhaustive, because we may want to add variants to them.
- Marked internal_testing module as doc(hidden), otherwise it would show up at docs.rs

Minor API stabilization changes

---

scylla/src/cluster/metadata.rs

I decided to introduce getters for (and un-pub the fields of) `Keyspace` and `Table`. I think these are the structs whose current fields may be modified in the future.
Remaining types (`ColumnKind`, `Column`, `MaterializedView` and `Strategy`) are simple enough for me to believe we won't need to modify their current fields/variants in the future. OTOH, we want to be able to introduce new fields/variants in the future - thus I marked them as `non_exhaustive`.

mark metadata public structs as `non_exhaustive`

---

docs/source/schema/schema.md
scylla/src/client/session_test.rs
scylla/src/cluster/state.rs
scylla/src/policies/load_balancing/default.rs
scylla/tests/integration/utils.rs

We don't want to expose the underlying structure of how we store keyspace info. This is because, we may want to change this structure in the future.
One possible idea for the future is to wrap `Keyspace` in an `Arc`. This would allow us to do following:
- share keyspace info in multiple places
- cheap cloning of keyspace info (e.g. currently we do the clone of whole `Keyspace` structure here: https://github.com/scylladb/scylla-rust-driver/blob/main/scylla/src/cluster/state.rs#L118-L121)

state: Adjust ClusterState keyspace info getters

---

.github/workflows/rust.yml
Cargo.lock.msrv
docs/source/metrics/metrics.md
docs/source/speculative-execution/percentile.md
examples/Cargo.toml
examples/basic.rs
scylla/Cargo.toml
scylla/src/client/pager.rs
scylla/src/client/session.rs
scylla/src/cluster/metadata.rs
scylla/src/cluster/node.rs
scylla/src/cluster/state.rs
scylla/src/cluster/worker.rs
scylla/src/network/connection_pool.rs
scylla/src/observability/metrics.rs
scylla/src/observability/mod.rs
scylla/src/policies/load_balancing/default.rs
scylla/src/policies/speculative_execution.rs
scylla/src/routing/locator/test.rs

This is a touch-up of #1147. Pasting the original cover letter below.
-------
This patch contains:
- Implementation of lock-free histogram with hot and cold bucket pools
- Introduction of crate feature "metrics" to make using them optional
- Functionality to gather latency statistics via histogram snapshots
- Implementation of [rates of queries per second](https://github.com/scylladb/cpp-driver/blob/9d6b05c9d4ebd0a6d7006af4df3e33fcdf956eeb/src/metrics.hpp#L39C1-L252C5) based on cpp-driver implementation.
- Initial implementation of connection metrics (changes required after review)
Fixes: #330

Make metrics collection optional/faster

---

scylla/src/policies/load_balancing/mod.rs
scylla/src/policies/retry/retry_policy.rs
scylla/src/policies/speculative_execution.rs
scylla/tests/integration/consistency.rs

We missed some structs when adding non_exhaustive.
This PR fixes that - we may want to add more stuff to them.
One example is RequestInfo, we will definitely want to add at least one field to it, see https://github.com/scylladb/scylla-rust-driver/issues/1155

Mark some policies-related structs as non_exhaustive

---

Cargo.lock.msrv
README.md
docs/pyproject.toml
docs/source/conf.py
docs/source/quickstart/create-project.md
scylla-cql/Cargo.toml
scylla-macros/Cargo.toml
scylla-proxy/Cargo.toml
scylla/Cargo.toml

This is a PR with changes for release 1.0.0. Its purpose is to make it possible to review the release notes, and changes to README.md.
Fixes: https://github.com/scylladb/scylla-rust-driver/issues/968
Fixes: https://github.com/scylladb/scylla-rust-driver/issues/552
The ScyllaDB team is pleased to announce ScyllaDB Rust Driver 1.0.0,
- over 3.162k downloads on crates!
- over 612 GitHub stars!
1.0 has a special meaning for Rust crates - it means that the crate is considered "API-stable" - however there is no specific definition of what it means to be "API-stable".
So what does it mean to us, and why did we release this version?
Up until now, we introduced …

Release 1.0.0

---

.github/workflows/authenticate_test.yml
.github/workflows/book.yml
.github/workflows/cassandra.yml
.github/workflows/rust.yml
.github/workflows/semver_checks.yml
.github/workflows/serverless.yaml
.github/workflows/tls.yml
Makefile

This PR performs some CI improvements. The most important one is utilizing caching, with the help of https://github.com/actions-rust-lang/setup-rust-toolchain action.
This should speed up CI, but its unclear how much exactly. I'll try to check that and post some results.
Apart from caching, this PR:
- fixes a bug, where clippy warnings were not rejected during cpp-rust-driver cfg check.
- makes some minor adjustments, like replacing "--manifest-path" with "--package".
- removes redundant build step.
- replaces scylla-cql build with clippy check.
- removes old workaround for a rust bug
Replaces https://github.com/scylladb/scylla-rust-driver/pull/901

Use cache in CI

---

docs/source/connecting/connecting.md
scylla/src/client/session_builder.rs
scylla/src/cloud/config.rs

In many cases, it may be desirable to store the contents of the cloud configuration YAML outside of the local filesystem. In order to support this, all that should be necessary is to allow for `CloudConfig` to be deserialized from a `Read`, rather than a file located at some path, and to allow for the `CloudSessionBuilder` to be constructed from an existing `CloudConfig`. 
I considered a `CloudSessionBuilder` constructor which accepted a `Read`, but settled on accepting `CloudConfig` instead as this seemed more logical by a small margin. I would ultimately be comfortable with either implementation, depending on maintainer preference.
Draft because I need to address some of the checklist items.

Introduce function to deserialize CloudConfig from Read

---

scylla/src/errors.rs

When we renamed `Query` to `Statement`, we omitted some occurrences. Unfortunately, the error types can no longer be renamed after we released 1.0, so only docstrings are adjusted.

errors: fix leftover mentions of _query_

---

scylla/src/client/mod.rs
scylla/src/client/session_test.rs
scylla/src/lib.rs
scylla/tests/integration/main.rs
scylla/tests/integration/session.rs
scylla/tests/integration/utils.rs

This is the first backport of hackathon stuff to main. It backports PR made by @sylwiaszunejko that moves (part of) session_test.rs to integration tests.
Ref: https://github.com/scylladb/scylla-rust-driver/issues/1271
I edited the original PR a bit, because now it is possible to actually move all the tests, which I did.
I also extracted commits that changed the code, so that the actual move only changes the imports in the moved file.
- First commit moves to using `.get_keyspace()` instead of keyspaces field. This is a new change, not present in the original PR.
- Second uses setters for consistency and tracing. It was already done by Sylwia, I just extracted it to a separate commit
- Third commit removes uses of recently un-pubed partitioner API from test_prepared_statement. This is a new …

Backport #1224 to main

---

scylla/src/client/mod.rs
scylla/src/client/session.rs
scylla/src/client/session_builder.rs
scylla/src/network/connection.rs
scylla/src/network/mod.rs

Fixes: https://github.com/scylladb/scylla-rust-driver/issues/1282
This PR introduces `WriteCoalescingDelay` enum and exposes delay configuration options in `SessionConfig` and `SessionBuilder`. I adjusted the delay implementation details, as well as `test_coalescing` to new variant (`WriteCoalescingDelay::Milliseconds` - represents a non-zero milliseconds delay implemented using tokio::sleep).
- Is `scylla::client::session::WriteCoalescingDelay` a reasonable place to put new enum? I did this, because we already defined `TlsContext` enum here. OTOH, I see that some other configuration types are defined somewhere else and re-exported under `scylla::client::*`. For example, `PoolSize` is defined in `scylla::network::connection_pool`, and re-exported in `scylla::client`.
- Ideally, …

Implement coalescing delay configuration

---

scylla/src/client/session.rs

The `Debug` implementation for `Session` omitted new fields - This patch includes all current `Session` fields
Fixes: #954

session: add missing fields in Debug output for Session

---

scylla/src/client/session.rs
scylla/src/client/session_builder.rs
scylla/src/network/connection.rs
scylla/tests/integration/new_session.rs
scylla/tests/integration/utils.rs

Ref: https://github.com/scylladb/scylla-rust-driver/issues/1027
This PR solves the first part of the issue: implementing local ip address binding logic.
I implemented the tests for this feature as well. 
~Actually, I have a question regarding these:
I defined a test `valid_local_ip_address` which binds the socket to `172.42.0.1`, which should be the address associated with the interface assigned to docker subnet defined in the docker-compose file (for both Scylla and Cassandra). This means that the test will obviously fail if the cluster is accessible via some other interface. For this reason, I introduced `docker_cluster_tests` cfg option and enable it for scylla (non-cloud) and cassandra tests. I wonder if this is a good solution. Maybe introducing the `cfg` option is an overkill, and …

Implement local bind address configuration option

---

scylla/src/client/session.rs
scylla/src/client/session_builder.rs
scylla/src/network/connection.rs
scylla/src/routing/mod.rs
scylla/src/routing/sharding.rs

Fixes: https://github.com/scylladb/scylla-rust-driver/issues/1027
This PR introduces configuration option for shard-aware local port range.
Since not all ranges are valid (e.g. empty one, or one including reserved ports i.e. ports < 1024), I introduced a simple wrapper called `ShardAwarePortRange` which validates provided range in constructor.
Currently, `Sharder` is `pub`, so are its fields, and its methods responsible for computing local ports. This is why, I couldn't modify the sharder in any of the following ways:
- adding `ShardAwarePortRange` field to the `Sharder`
- providing `ShardAwarePortRange` parameter to `Sharder` methods
This is why, I introduced separate set of methods which additionally accept the port range. Current public methods are using new methods by providing a …

Shard aware port range

---

scylla/src/cluster/state.rs
scylla/src/cluster/worker.rs
scylla/src/policies/load_balancing/plan.rs

Ref: #1053
When manually testing the driver against a cluster containing some zero-token nodes, I uncovered a bug: zero-token nodes are missing from `ClusterState::get_nodes_info()` slice, because the slice is borrowed from `ReplicaLocator`, which only contains nodes that have some tokens assigned.
All nodes reside in `ClusterState::known_peers` `HashMap`. Therefore, my preferred solution would be to change the signature of `ClusterState::get_nodes_info()` to return `Iterator` over `Arc<Node>` instead of `&[Arc<Node>]`. This is, unfortunately, not an option for time now - this must wait until 2.0.
For now, to fix the bug, `all_nodes` field is added to `ClusterState`. It's just a `Vec<Arc<Node>>` with the same nodes that are present in `ClusterState::known_peers`.
Some leftover references …

cluster/state: Fix missing zero-token nodes in nodes info

---

scylla-cql/src/value.rs

This patch adds a nil() method for CqlTimeuuid
To directly generate nil values and recude boilerplate code
Fixes https://github.com/scylladb/scylla-rust-driver/issues/930

feat: add nil() method for CqlTimeuuid

---

scylla/src/network/connection.rs
scylla/src/network/connection_pool.rs
scylla/src/utils/test_utils.rs
scylla/tests/integration/consistency.rs
scylla/tests/integration/execution_profiles.rs
scylla/tests/integration/lwt_optimisation.rs
scylla/tests/integration/metadata_custom_timeouts.rs
scylla/tests/integration/new_session.rs
scylla/tests/integration/retries.rs
scylla/tests/integration/self_identity.rs
scylla/tests/integration/shards.rs
scylla/tests/integration/silent_prepare_query.rs
scylla/tests/integration/skip_metadata_optimization.rs
scylla/tests/integration/tablets.rs
scylla/tests/integration/utils.rs

When serverless tests are executed, some test that are not compatible with serverless are skipped. Skipping was done by cfg-ing them out. This caused some imports to be unused which of course resulted in warnings. Github, in coordination with `setup-rust-toolchain` action, "helpfully" attached info about those warnings in EVERY COMMIT OF EVERY PR in a section "Unchanged files with check annotations" which despite being a "preview" feature has no good way of being disabled.
This commit fixes that by changing `#[cfg(not(scylla_cloud_tests))]` to `#[cfg_attr(scylla_cloud_tests, ignore)]`. This causes those tests to still be compiled, just not executed.
The above uncovered two real warnings about unused imports, which I also fixed.

CI: Fix warnings in serverless tests

---

scylla-cql/src/serialize/value_tests.rs
scylla-cql/src/value.rs

This patch adds from_option() method for MaybeUnset enum
It enables easy conversion from Option<T> into MaybeUnset<T>
Fixes: #1003

feat: add MaybeUnset::from_option() to reduce boilerplate

---

Cargo.lock.msrv
scylla-cql/src/deserialize/result.rs
scylla/Cargo.toml
scylla/src/client/session_builder.rs
scylla/src/network/tls.rs
scylla/src/routing/locator/tablets.rs
scylla/src/routing/partitioner.rs

After we bumped MSRV to 1.80 in #1144, some code became obsolete. Also, it unlocked using `LazyLock` (forgive me the pun) instead of `lazy_static`. This PR takes advantage of the MSRV bump and adjusts the codebase.

Adjust to MSRV 1.80

---

scylla/src/client/session.rs
scylla/src/network/connection.rs
scylla/src/response/mod.rs
scylla/src/response/request_response.rs

Constructing `PreparedStatement` involves allocations:
1. `ResultMetadata` must be put onto heap, behind an `Arc`;
2. `StatementConfig` must be cloned along with all `Arc`s inside;
3. Statement string must be cloned.
I noticed that in a number of places we materialise `PreparedStatement` even though it's not used afterwards.
`RawPreparedStatement` contains everything that is needed to construct the `PreparedStatement`, but avoid all 3 allocations that I listed above. Those allocations are delayed until one calls `into_prepared_statement()`, if materialised `PreparedStatement` is really needed.
`Connection::prepare_raw()` extracts most of the logic that was put in `Connection::prepare()` before; yet, it returns `RawPreparedStatement`. `Connection::prepare()` is reimplemented as a wrapper …

Construct `PreparedStatement` only where needed

---

docs/source/load-balancing/load-balancing.md
examples/Cargo.toml
examples/enforce_coordinator.rs
scylla/src/client/pager.rs
scylla/src/client/session.rs
scylla/src/policies/load_balancing/mod.rs
scylla/src/policies/load_balancing/single_target.rs
scylla/src/statement/batch.rs
scylla/src/statement/mod.rs
scylla/src/statement/prepared.rs
scylla/src/statement/unprepared.rs
scylla/tests/integration/statement.rs
scylla/tests/integration/tablets.rs

Fixes: https://github.com/scylladb/scylla-rust-driver/issues/1031
This load balancing policy returns a single target in `pick`.  The fallback
always returns empty iterator.
The node is picked based on the `NodeIdentifier` that user can provide
when constructing the policy.
- NodeIdentifier::Node -> just `Arc<Node>` - it's returned unconditionally from pick()
- NodeIdentifier::Address -> lbp does the lookup in the cluster metadata
and returns a node with the given address  (if found)
- NodeIdentifier::HostId -> same as for the address, but the lookup is
done by the host id
In addition, we expose a utility method on all statements, that allow to overwrite current LBP, and enforce the specific target for the request.
- ~~[ ] I have adjusted the documentation in `./docs/source/`.~

Enforce request coordinator

---

docs/source/conf.py

Related issue & explanation https://github.com/scylladb/scylladb/pull/23957
This should allow navigation between versions without being redirected to the main index page:
**Note:** This fix will only apply to future versions unless backported. While backporting may not be worth the effort, it's important to be aware that the issue will remain in older versions.

docs: fix md redirections for multiversion support

---

scylla/src/client/pager.rs
scylla/src/client/session.rs

The name was obsolete; it was overlooked when renaming `RowIterator` to `QueryPager` upon deserialization refactor.

pager: rename `Prepared(Iterator->Pager)Config`

---

scylla-macros/src/lib.rs

somehow it was commited in the docs for SerializeValue instead

docs: move flatten attribute docs to SerializeRow

---

scylla-cql/src/frame/mod.rs
scylla-cql/src/frame/request/startup.rs
scylla-proxy/src/errors.rs
scylla-proxy/src/frame.rs
scylla-proxy/src/proxy.rs

During hackathon, there emerged a need to test compressed communication through proxy. However, proxy did not yet support compression.
These are now used by the proxy.
- `impl FromStr for Compression`
- `impl DeserializableRequest for Startup`
The impls are used by the proxy to read the negotiated compression from STARTUP frame.
It's convenient to be able to compare the whole frame at once.
Before, they printed the shard number next to the driver, not the node, which was confusing.
Some tests just set random CQL flags and assert that they are simply passed through the proxy. It used to work, but as now we make the proxy clever enough to interpret at least one of them, namely the compression flag, we needed to stop abusing it blindly.
The test `proxy_processes_requests_concurrently` showed …

Proxy: compresssion support

---

scylla/src/client/session.rs
scylla/src/cluster/node.rs
scylla/src/cluster/state.rs

This PR comes with two main enhancements / optimisations:
1. **Prepare on every node, not on every shard.** This corresponds to #1290.
2. ~~**Wait only for one prepare attempt to succeed, not for all prepare attempts.** This is inspired by cpp-driver's logic.~~ (dropped)
Below, I describe both changes in detail.
Just as other drivers do, now the Rust driver also prepares statements on a single connection to every node, not on a single connection to every shard. This brings performance benefits for both driver and cluster, as it lowers the overhead of handling duplicated prepare requests on both sides.
As mentioned in https://github.com/scylladb/scylla-rust-driver/issues/1290#issuecomment-2740175939, we might be unlucky enough to end up with all randomly chosen connections being …

session: Prepare on one shard per node only

---

scylla/src/client/session.rs
scylla/src/cluster/state.rs

Bases on: #1320
Start review from `session: document schema agreement API`.
Before, `Session` needlessly fetched schema version from all connections to given node, even that all shards of the same node share the same schema version.
`Session::check_schema_agreement()` is modified to only fetch schema version from every node once, instead of on all connections to the same node. To this end, it iterates over connections to given node and tries
to fetch schema version. Once it succeeds on any connection to given node, it does not continue on remaining connections.
Notice that this not only decreases load on the cluster that schema agreement checks involve (a performance optimisation), but it also possibly leads to fewer errors returned from `check_schema_agreement()`. This is because now we …

Schema agreement: Fetch schema version from one connection per node only

---

Cargo.lock.msrv
docs/source/data-types/data-types.md
docs/source/data-types/vector.md
scylla-cql/src/deserialize/frame_slice.rs
scylla-cql/src/deserialize/value.rs
scylla-cql/src/deserialize/value_tests.rs
scylla-cql/src/frame/frame_errors.rs
scylla-cql/src/frame/response/custom_type_parser.rs
scylla-cql/src/frame/response/mod.rs
scylla-cql/src/frame/response/result.rs
scylla-cql/src/frame/types.rs
scylla-cql/src/lib.rs
scylla-cql/src/serialize/value.rs
scylla-cql/src/serialize/writers.rs
scylla-cql/src/utils/mod.rs
scylla-cql/src/utils/parse.rs
scylla-cql/src/value.rs
scylla/src/cluster/metadata.rs
scylla/src/utils/mod.rs
scylla/tests/integration/session.rs

This PR adds serialization and deserialization of CQL Vector (as implemented in Cassandra) therefore achieving compatibility with Cassandra's Vector type. It's important to note that Cassandra implements Vector serialization and deserialization in a way that
contradicts the CQL protocol, using [unsigned vint] instead of [int] as the element size encoding for variable type length vectors.
Fixes #1014

CQL Vector support

---

Cargo.lock.msrv
Makefile
scylla-cql/Cargo.toml
scylla-proxy/Cargo.toml
scylla/Cargo.toml
scylla/src/client/pager.rs
scylla/src/client/session.rs
scylla/src/network/connection.rs
scylla/src/network/connection_pool.rs
scylla/src/policies/speculative_execution.rs
scylla/src/response/coordinator.rs
scylla/src/response/mod.rs
scylla/src/response/query_result.rs
scylla/src/response/request_response.rs

This is the second approach to #1030.
`Coordinator` is defined as follows:
```rust
/// The coordinator of a CQL request, i.e., the node+shard that receives
/// and processes the request, and hopefully eventually sends a response.
#[derive(Debug, Clone)]
pub struct Coordinator {
/// Translated address, i.e., one that the connection is opened against.
connection_address: SocketAddr,
/// The node that served as coordinator.
node: Arc<Node>,
/// Number of the shard, if applicable (present for ScyllaDB nodes, absent for Cassandra).
shard: Option<Shard>,
}
```
It has `pub` getters for all of its fields.
`Coordinator` is built from `NodeRef` (`untranslated_address` and `host_id`), `Shard` (`shard`), and `Connection` (`connection_address`).
`Coordinator` is stored in `QueryResult` (as well as …

Expose request coordinator

---

scylla/src/client/caching_session.rs

We can see that CachingSession requires more config options than there are currently. Not to cause exponential growth of number of constructors, a builder is introduced.
A unit test using proxy comes together, too.
Fixes: #1342

caching_session: introduce CachingSessionBuilder

---

.gitignore
scylla/src/client/caching_session.rs
scylla/tests/integration/session/caching_session.rs
scylla/tests/integration/session/mod.rs

As `CachingSession` manages preparation internally, it does not expose its `PreparedStatement`s in any way. Therefore, it's not possible for a user of `CachingSession` to call
`PreparedStatement::set_use_cached_result_metadata` in order to take advantage of that optimisation.
There are use cases when not having possibility to turn the optimisation on may result in significant inefficiency. As an example, the experimental NodeJS-over-Rust driver's API suits `CachingSession`'s API best, but lack of the mentioned optimisation makes the experimental driver fall short compared to the original NodeJS driver (which, most likely, has the optimisation turned on).
New method is added to recently introduced CachingSessionBuilder, allowing user to enable caching result metadata.
Additionally, I added …

CachingSession: Allow skipping result metadata

---

examples/cqlsh-rs.rs
scylla-proxy/src/frame.rs
scylla/src/cluster/node.rs
scylla/src/network/connection.rs
scylla/src/network/tls.rs
scylla/src/response/query_result.rs
scylla/src/statement/batch.rs
scylla/src/utils/test_utils.rs

New Rust version, new Clippy lints enabled by default. I decided to silence the lints about too large errors. Those are our standard error types, it would not be ergonomical to Box them. In some cases the Ok variant is larger, so it would make no sense to Box errors. If it ever becomes an issue, we can reconsider.

Address Clippy's lints introduced in Rust 1.87

---

scylla/src/cluster/node.rs
scylla/src/cluster/worker.rs
scylla/src/policies/load_balancing/default.rs

Events-related node status is not used for anything, and I don't see any possible uses for it in the future. For that reason I don't think we need this code for anything.

Remove is_down and all related code

---

Cargo.lock.msrv
docs/pyproject.toml
docs/source/conf.py
docs/source/quickstart/create-project.md
scylla-cql/Cargo.toml
scylla-macros/Cargo.toml
scylla-proxy/Cargo.toml
scylla/Cargo.toml

The ScyllaDB team is pleased to announce ScyllaDB Rust Driver 1.2.0,
- over 3.877k downloads on crates!
- over 633 GitHub stars!
**New features / enhancements:**
- Added `flatten` attribute to `SerializeRow` derive macro. The attribute is inspired and analogous to the one found in `serde` [#1144](https://github.com/scylladb/scylla-rust-driver/pull/1144)
- Introduced CQL Vector type full support [#1165](https://github.com/scylladb/scylla-rust-driver/pull/1165).
- Added `nil()` method for `CqlTimeuuid` [#1314](https://github.com/scylladb/scylla-rust-driver/pull/1314).
- Added `MaybeUnset::from_option()` convenience constructor to reduce boilerplate …

Release 1.2.0

---

scylla-proxy/src/actions.rs
scylla/src/client/caching_session.rs
scylla/tests/integration/statements/prepared.rs

- Preparation is expected to succeed iff at least one shard sends  a successful PREPARED response.
- If preparation succeeds, the statement is executed on all nodes and this way repreparation logic is additionally checked.
1. All nodes enabled -> preparation succeeds.
2. One or two nodes fully disabled -> preparation succeeds.
3. All three nodes fully disabled -> preparation fails, and we assert that all shards were attempted.
4. All three nodes disabled once (simulation of only part of shards broken) -> preparation succeeds, and we assert that all shards were attempted.
I implemented convenience constructors for `Condition` in proxy: `Condition::any()` and `Condition::all()`.
Fixes: #1348

Preparation logic integration test

---

scylla/src/cluster/state.rs
scylla/tests/integration/load_balancing/tablets.rs
scylla/tests/integration/session/cluster_reachability.rs
scylla/tests/integration/session/mod.rs
scylla/tests/integration/utils.rs

I noticed that we lacked a test that requires direct connectivity to all nodes in the cluster in order to pass. Other tests would often succeed even if only one node (the initial contact point) was directly reachable.
The issue has manifested in testing serverless cloud why working on rustls support: tests would pass even with address translation disabled...
An example of a test which has exercised direct connectivity to all nodes is `tablets.rs`, yet it could be enabled only for non-cloud case, as it uses the proxy.
I wrote a test that iterates though all targets (pairs `(node, shard)`) and sends a request directly to them (using a load balancing policy that produces singleton query plans).
I extracted and refactored some utils from `tablets.rs` to `utils.rs`, so that they can be used by …

integration: direct node connectivity test

---

scylla/src/client/session.rs

In the past, those functions needed to be generic over the result type `ResT`, because they actually were instantiated with different result types. Now, they are always instantiated with the same type: `NonErrorQueryResponse`. This means we can de-genericise both those functions for better readability and maintainability.
As a bonus, we can remove the trait `AllowedRunRequestResTType`.
Two special kinds of responses:
- SetKeyspace,
- SchemaChanged,
used to be separately handled in both `query()` and `execute()`. This not only duplicated code, but also made it bug-prone.
This commit moves the handling of these responses to a common place, `Session::run_request()`, which is a meeting point for all* requests.
*not true. `{query,execute}_iter()` are not using it. We however hope that no one …

session: Degenericise `run_request` & unify autohandling of specific responses

---

scylla/src/cluster/control_connection.rs
scylla/src/statement/batch.rs
scylla/src/statement/prepared.rs
scylla/src/statement/unprepared.rs

This is required by the CPP Rust Driver, and also useful for Rust Driver direct users. See #1384 for details.
Bonus: fixed codewide typo "overriden" -> "overridden".
Fixes: #1384

statements: expose API to unset (serial) consistency

---

.github/workflows/rust.yml
CONTRIBUTING.md
MAINTENANCE.md
README.md
docs/book.toml
docs/source/SUMMARY.md
docs/source/conf.py
docs/source/connecting/connecting.md
docs/source/data-types/udt.md
docs/source/index.md
docs/source/load-balancing/default-policy.md
docs/source/quickstart/quickstart.md
docs/source/quickstart/scylla-docker.md
docs/source/retry-policy/downgrading-consistency.md
docs/source/statements/lwt.md
docs/source/tracing/tracing.md
scylla/src/client/self_identity.rs
scylla/src/client/session.rs
scylla/src/client/session_builder.rs
scylla/src/cloud/config.rs
scylla/src/cluster/node.rs
scylla/src/network/connection_pool.rs
scylla/src/network/mod.rs
scylla/src/routing/locator/tablets.rs
scylla/src/routing/locator/token_ring.rs
scylla/src/routing/mod.rs
scylla/src/routing/partitioner.rs
scylla/src/routing/sharding.rs
scylla/src/utils/test_utils.rs
scylla/tests/integration/ccm/lib/cluster.rs

This name change has been widely adopted in the company's products, documentation, and marketing materials. However, the Rust Driver retained much of the legacy naming, which is now updated.

codewide: rename Scylla -> ScyllaDB

---

docs/source/data-types/blob.md
docs/source/data-types/data-types.md
scylla-cql/src/serialize/value.rs
scylla-cql/src/serialize/value_tests.rs

Fixes: #1394
As noted in the issue, deserialization of `blob` to `Bytes` was supported, yet serialization in the opposite way was not possible, bringing major inconvenience to work with slices in UDT instead.
Such serialization has been thus added. Docs on `blob` has been updated.

serialize: support `Bytes` -> CQL `blob` conversion

---

scylla/src/policies/speculative_execution.rs

Up until now if execution plan was exhausted, we would still wait until we spawned and finished all SE fibers (unless one succeeds or finishes with non-ignorable error).
This is wasteful - if plan was exhausted by one fiber, then any new fiber will also see exhausted plan and fail, since plan is shared.
This PR fixes this behavior. I also introduced tests for it, using clock simulation facilities from Tokio. Thanks to that, those tests run instantly despite `sleep`s in tested code.
As a bonus. I wrote a regression test for an issue we fixed quite some time ago: #1085 
This issue was considered theoretical - we never tried to write a test / reproducer, because it would execute too long (thanks to sleeps), and could be flaky.
Using clock simulation removes those obstacles, and makes writing …

Fix plan exhaustion handling in SE and introduce SE unit tests.

---

scylla/tests/integration/load_balancing/tablets.rs

This is an attempt to fix test_default_policy_is_tablet_aware.
I did 2 things that should help:
- Introduced retries in case tablet migration happened
- Changed the way tablet info is populated, which can possibly decrease the chance of migration happening.
I executed the test 100 times locally, and it passed each time.
Fixes: https://github.com/scylladb/scylla-rust-driver/issues/1380 (hopefully).

Try to fix test_default_policy_is_tablet_aware

---

scylla-cql/Cargo.toml
scylla-cql/src/deserialize/result.rs
scylla-cql/src/deserialize/row_tests.rs
scylla-cql/src/deserialize/value_tests.rs
scylla-cql/src/serialize/row.rs
scylla-proxy/src/frame.rs
scylla/src/client/pager.rs
scylla/src/cluster/metadata.rs
scylla/src/response/coordinator.rs
scylla/src/statement/prepared.rs
scylla/tests/integration/macros/hygiene.rs

As usual, clippy started to fail because of newly stabilized lints.
This PR fixes that.

Fix clippy 1.89

---

scylla/src/client/caching_session.rs

A race can happen when multiple calls with different statements (none of which are in cache) are executed at the same time, with cache full.
It is possible that all of them will remove the same entry from the cache, and then add their own entries. Then size of the cache will exceed self.max_capacity, so we will never remove from cache again.
First fix that I thought of is to change "==" to "<=". With that fix, we would still be able to remove elements from the map after race happens. Note that we only remove an element when inserting a new element, so this would still never decrease the cache overflow unless 2 cache misses with the same query happen at the same time. So the memory leak would still happen, but much slower.
So in addition to that I changed  "if cache full: remove" to "while …

CachingSession: Mostly fix a race condition

---

scylla/src/client/pager.rs

As far as I can tell these bounds are unnecessary.
I ran the static checks and they "failed" but they're also failing on main for me so I don't think I introduced the errors. CI is also failing but I see the same failures on other branches so again, I don't think my changes caused them.

Remove unnecessary `'static` bounds

---

examples/Cargo.toml
scylla-cql/src/serialize/row_tests.rs
scylla-macros/src/deserialize/row.rs
scylla-proxy/src/proxy.rs
scylla/src/network/connection.rs
scylla/tests/integration/macros/hygiene.rs

Two things were caught by new version of Clippy:
- Unnecessary parentheses.
- Unused structs, that should have been caught before. It wasn't, most likely because of Clippy bug.
Fixes: https://github.com/scylladb/scylla-rust-driver/issues/1429

Fix Clippy 1.90 lints

---

.github/workflows/book.yml
scylla/src/statement/prepared.rs

Small possible improvement that I noticed when working on metadata id extension.
PreparedStatementSharedData was initially introduced for performance reasons, specifically to make cloning PreparedStatement cheaper. Now that we have it, I think we should put all shared state there. If we don't:
- It is confusing. If I see shared state, and I see that e.g. `id` is not a part of it, then I automatically begin to wonder if its not shared, of if its somehow mutable.
- (Minor) More stuff in shared -> cheaper cloning. Difference, if any, should be tiny.
prepare_tracing_ids unfortunately can't be moved because it is pub.

PreparedStatement: put id and lwt in shared state
