- scylla/Cargo.toml
- scylla/src/routing.rs
- scylla/src/transport/connection.rs
- scylla/src/transport/session.rs
- scylla/src/transport/topology.rs
After long fighting together with @piodul to make the murmur3 hash work (or not work, depending on how you look at it)...
IT WORKS!
Fixes https://github.com/psarna/scylla-rust-driver/issues/18.
> Shard awareness

- scylla/Cargo.toml
- scylla/src/frame/frame_errors.rs
- scylla/src/frame/mod.rs
- scylla/src/frame/request/batch.rs
- scylla/src/frame/request/execute.rs
- scylla/src/frame/request/mod.rs
- scylla/src/frame/request/options.rs
- scylla/src/frame/request/prepare.rs
- scylla/src/frame/request/query.rs
- scylla/src/frame/request/startup.rs
- scylla/src/frame/response/cql_to_rust.rs
- scylla/src/frame/response/error.rs
- scylla/src/frame/response/mod.rs
- scylla/src/frame/response/result.rs
- scylla/src/frame/response/supported.rs
- scylla/src/frame/types.rs
- scylla/src/lib.rs
- scylla/src/routing.rs
- scylla/src/transport/connection.rs
- scylla/src/transport/iterator.rs
- scylla/src/transport/mod.rs
- scylla/src/transport/session.rs
- scylla/src/transport/topology.rs
- scylla/src/transport/transport_errors.rs
Added new typed errors using thiserror.
Deleted anyhow errors.
Fixes #68
> Added new errors. (Issue #68)

- scylla/src/frame/request/batch.rs
- scylla/src/frame/request/query.rs
- scylla/src/frame/types.rs
- scylla/src/statement/batch.rs
- scylla/src/statement/mod.rs
- scylla/src/statement/prepared_statement.rs
- scylla/src/statement/query.rs
- scylla/src/transport/connection.rs
> Allow setting consistency level in statements and batches

- scylla-macros/src/from_row.rs
- scylla-macros/src/from_user_type.rs
- scylla-macros/src/into_user_type.rs
- scylla-macros/src/lib.rs
- scylla-macros/src/parser.rs
PR from https://github.com/scylladb/scylla-rust-driver/pull/131, but that branch had commits on it I was unable to remove
> Removed duplicate code in proc macro

- scylla/Cargo.toml
- scylla/src/routing.rs
- scylla/src/transport/iterator.rs
Was annoying to build with an outdated tokio, so I just updated the rest of the deps while I was at it...
> Update all outdated deps (tokio, bytes, rand)

- README.md
- scylla/src/frame/response/result.rs
Some of the items were already cleared from the backlog,
so the list is updated.
> README.md: update achieved goals

- .github/workflows/rust.yml
- CONTRIBUTING.md
- scylla/src/frame/cql_collections_test.rs
- scylla/src/transport/session_test.rs
This PR ensures the CI spins up a ScyllaDB instance in Docker and executes database tests
> Added database CI tests

- scylla/src/frame/cql_types_test.rs
- scylla/src/frame/mod.rs
- scylla/src/frame/response/cql_to_rust.rs
- scylla/src/frame/response/result.rs
- scylla/src/frame/value.rs
PR adds CQL types. 
Add time and dates, floating point numbers, booleans and blobs, serializers and deserializers.
Add test (and example of usage at the same time).
I moved the commits to the new branch and created new PR, the old one is here: PR #148 (decided to move because of the issues with merge).
Refs #104
> CQL types 

- scylla/src/transport/session.rs
> Checking if query starts with 'use ' is now more efficient

- scylla/src/frame/request/batch.rs
- scylla/src/frame/request/query.rs
- scylla/src/statement/batch.rs
- scylla/src/statement/prepared_statement.rs
- scylla/src/statement/query.rs
- scylla/src/transport/connection.rs
Adds support for setting serial_consistency for queries, prepared statements, and batch statements. This provides the basis for LWT support (#100)
> Add serial_consistency support for queries, prepared statements, and batch statements. (LWT Basis)

- .github/workflows/authenticate_test.yml
- scylla/src/frame/request/auth_response.rs
- scylla/src/frame/request/mod.rs
- scylla/src/frame/response/authenticate.rs
- scylla/src/frame/response/mod.rs
- scylla/src/transport/authenticate_test.rs
- scylla/src/transport/connection.rs
- scylla/src/transport/connection_keeper.rs
- scylla/src/transport/mod.rs
- scylla/src/transport/session.rs
- scylla/src/transport/session_builder.rs
Add Authenticate mechanism while creating new connection.
Add Authenticate request and possible responses to the frame.
Add serializers, deserializers.
Fixes: #13
> Authenticate

- README.md
Features from our roadmap were already implemented, so the list
is updated accordingly.
> README.md: update the roadmap

- scylla/src/frame/value.rs
> Preallocate space for SerializedValues

- .github/workflows/rust.yml
It will be better if shorter tests will run first so if a developer forgets to run `cargo fmt` before push, we'll get feedback faster.
> Run faster tests first - format before cargo test

- scylla/src/lib.rs
- scylla/src/transport/errors.rs
- scylla/src/transport/iterator.rs
- scylla/src/transport/load_balancing/mod.rs
- scylla/src/transport/mod.rs
- scylla/src/transport/retry_policy.rs
- scylla/src/transport/session.rs
- scylla/src/transport/session_builder.rs
This PR adds more API documentation.
This will make [https://docs.rs/scylla/0.1.0/scylla/](https://docs.rs/scylla/0.1.0/scylla/) better.
To view the changes run:
```shell
cargo doc
```
And open the file `target/doc/scylla/index.html` in a browser.
> Improve API docs

- scylla/src/transport/session.rs
- scylla/src/transport/topology.rs
The newest version of clippy added new lints, which detected some
problems in the code. This commit applies suggestions so that the CI
passes again.
> Apply suggestions from clippy 0.1.52

- scylla/src/frame/response/event.rs
- scylla/src/frame/response/result.rs
Add deserialization for schema change server event and for schema change response for schema altering query.
Important note: the way to make sure, if the schema is same for each node will be schema agreement query.
> Add schema_change event, schema_change response

- scylla/src/frame/mod.rs
- scylla/src/transport/connection.rs
Currently, request frame headers and bodies are written in separate `write_all` calls, which always causes at least two syscalls to be issued. This has the following problems:
1. With Nagle's algorithm disabled, requests smaller in size than MSS are always sent in two packets, even if they would fit into one, which adds to the overhead,
2. When Nagle's algorithm is enabled on the client and delayed ACK on Scylla, this causes small packets to have very large latency. This happens because of the following sequence of events:
- Header is sent in one packet; body is not immediately sent because Nagle's algorithm tells us to wait for an ACK,
- Scylla receives the header and waits for the rest of the body; because it has no data to send back, the ACK is not sent immediately (this is due to the …
> Write each frame with a single `write_all` call

- scylla/src/transport/connection.rs
- scylla/src/transport/session.rs
Fixes: https://github.com/scylladb/scylla-rust-driver/issues/248
Previous version had issues with data race when schema was checked before schema.peers table could be updated.
This solution checks every node connection for its local schema version. That ensures us that if schema is in disagreement
then we will detect it. Solution could be optimized to pick only one connection per node. Another opt could be calling
`Connection::check_schema_agreement` on two connections that are in disagreement and then await as long as they are not in agreement.
I pushed not optimized version because we needed to fix this bug quickly, and it won't affect our driver's performance during benchmarking due to the fact this method isn't called during timed part of our benchmarks.
> Data race proof await_schema_agreement

- scylla/src/transport/session.rs
This patch makes sessions automatically probe for shard-aware ports
via the CQL OPTIONS request, and if found, tries to use it.
With such a mechanism, users no longer need to remember to manually
set up port 19042 to enjoy shard awareness.
The new algorithm is as follows:
- connect to one of the nodes just to send an `OPTIONS` request and retrieve the shard-aware port
- if found, use the shard aware port to connect to the cluster
- if successful, continue enjoying the driver
- if failed, fall back to the original port (a custom port can fail e.g. due to firewall rules)
- if not found, use the original port
Currently marked as draft, because the change was only tested manually in a limited scope. Still, it's ready for preliminary review.
Fixes #255
> Add auto shard aware port

- scylla/src/transport/session.rs
If no port is explicitly configured for a session,
it will now use the default CQL port 9042 instead of returning
an error.
Tested with existing examples by passing various `SCYLLA_URI` values, both with and without specifying the port.
> Add a default port: 9042

- .github/workflows/cassandra.yml
- scylla/src/frame/request/query.rs
- scylla/src/frame/response/result.rs
- scylla/src/frame/value.rs
- scylla/src/transport/connection.rs
- scylla/src/transport/connection_keeper.rs
- scylla/src/transport/load_balancing/token_aware.rs
- scylla/src/transport/session.rs
- scylla/src/transport/topology.rs
... just to make the continuous integration machinery happy.
> treewide: apply clippy fixes and suppress useless warnings

- examples/basic.rs
- scylla-macros/src/from_row.rs
- scylla/src/lib.rs
- [] I added relevant tests for new features and bug fixes.
It is not ergonomic to import the FromRow trait everywhere you derive it from
> Inline from row trait

- docs/source/queries/usekeyspace.md
- scylla/src/transport/connection.rs
- scylla/src/transport/session.rs
This PR removes error prone CQL parsing in `session::query` method in a way described in #168
Fixes: #168
> Improve use keyspace queries detection

- scylla/src/frame/value.rs
- [-] I added relevant tests for new features and bug fixes.
> Add 'Debug' derive to Time and Timestamp

- scylla/src/frame/response/cql_to_rust.rs
👋 
Just a small PR to add the support of `CqlFromValue` for `HashSet`.
> frame/response: add impl CqlFromValue for HashSet

- docs/source/queries/prepared.md
> docs: mention that prepared statements will inherit from Query

- scylla/src/transport/topology.rs
When fetching topology, our previous reaction to a non-standard
token was to fail the driver, which is harsh - especially on
managed solutions like Amazon Keyspaces, which does not allow
changing the partitioning scheme.
Instead, a dummy token is used, a warning is printed and a FIXME
is added to address the problem more thoroughly in the future.
Fixes #350
Tested manually on Cassandra with RandomPartitioner - only two tests fail, but they explicitly check compatibility with Murmur3Partitioner, so it's expected.
> topology: ignore non-standard tokens

- README.md
- docs/source/index.md
I added two links to the Scylla U. lesson on the Rust driver, compiled and checked the book.
> added links to Scylla University lesson 

- scylla/src/frame/response/result.rs
Adds missing derive(Clone) directive for the CqlValue.
> impl Clone for CqlValue

- examples/Cargo.toml
- examples/cqlsh-rs.rs
The completion is still very crude as it does not check any context,
nor does it use schema information, etc. Its main purpose is to
serve as a starting point for a more complex implementation.
> examples: add rudimentary completion to cqlsh-rs

- examples/Cargo.toml
- examples/custom_load_balancing_policy.rs
- scylla/src/transport/cluster.rs
- scylla/src/transport/connection.rs
- scylla/src/transport/mod.rs
- scylla/src/transport/node.rs
This PR makes it possible to create custom load balancing policies. It does so by extending visibility of `Node` and providing needed getters to `ClusterData`. 
Fixes: #382
> Custom load balancing policy

- CONTRIBUTING.md
Since df41ab04 we have been supporting multithreaded tests, so an update
to testing info in CONTRIBUTING.md was needed.
Fixes: #390
> Update testing info in CONTRIBUTING.md

- scylla/src/transport/connection_pool.rs
- scylla/src/transport/iterator.rs
- scylla/src/transport/load_balancing/dc_aware_round_robin.rs
- scylla/src/transport/load_balancing/mod.rs
- scylla/src/transport/load_balancing/round_robin.rs
- scylla/src/transport/load_balancing/token_aware.rs
- scylla/src/transport/session.rs
- scylla/src/transport/speculative_execution.rs
In order to improve debugging experience, more traces are added.
Also, the error message informing that there are no connections in the pool has a little more context - it distinguishes between broken and initializing state.
> transport: sprinkle trace logs around the code

- scylla/src/transport/connection.rs
- scylla/src/transport/session.rs
> session,connection: fix clippy warnings

- scylla/src/frame/value.rs
It turns our that the implementation of SerializedValuesIterator was
needlessly complicated. This commit removes the next_offset field and
reimplements .next() in terms of the utility parsing functions in the
frame::types module.
Fixes #384
> frame/value: simplify SerializedValuesIterator

- scylla/src/transport/cluster.rs
- scylla/src/transport/connection.rs
- scylla/src/transport/connection_pool.rs
- scylla/src/transport/session.rs
- scylla/src/transport/session_builder.rs
- scylla/src/transport/topology.rs
New keepalive mechanism that sends a simple query, using all connections, every user-specified time interval.
Fixes: #132
> Keepalive queries

- scylla/src/frame/response/result.rs
The PR adds two functions to CqlValue: one to borrow the `UserDefinedType` fields is called `as_udt` and the other to take ownership of the values is called `into_udt_pair_vec`.
> Add possibility to borrow udt fields

- scylla/src/transport/connection_pool.rs
Our use_keyspace() utility may hang if any of the nodes are not
available. Since the default TCP timeout is rather long (10 minutes
on most systems), let's instead use the existing connection timeout
as the timeout value.
> transport: use connect_timeout for use_keyspace

- scylla/src/transport/iterator.rs
Both `Query` and `PreparedStatement` have page size set to `None` as
default, which means unlimited page size. This is a problem for
`query_iter` and `execute_iter` because using them with such queries
causes everything to be fetched in one page, despite them being meant
to fetch data page-by-page.
We can't really change the default page size for `Query`
and `PreparedStatement` because it also affects
`Session::{query,execute}` and this could break existing code.
In order to work around the problem we just set the page size to
a default value at the beginning of `query_iter` and `execute_iter`.
The default is 5000 rows, just like the default page size in gocql and
the Java driver.
Fixes #424
> iterator: provide default page size when querying with _iter

- examples/compare-tokens.rs
- scylla/src/routing.rs
- scylla/src/statement/prepared_statement.rs
- scylla/src/transport/mod.rs
- scylla/src/transport/partitioner.rs
- scylla/src/transport/session.rs
- scylla/src/transport/session_test.rs
Fixes: #194 
The following PR refactors partitioner logic and implements CDC Partitioner.
> Add CDC partitioner support

- scylla/src/transport/cluster.rs
- scylla/src/transport/topology.rs
Currently, the driver fetches topology and schema information (we call
it metadata) on Session creation and fails if an error occurs during
fetching/parsing of that data - despite the fact that the metadata is
not vital for the driver to work (although some information is needed
for better performance, e.g. topology info and keyspace replication
strategies).
While, in ideal world, we would like the metadata fetch to always
succeed, it can fail either due to our fault (e.g. bugs like #437) or
reasons beyond our control (connection errors, non-backwards compatible
changes in system tables). Therefore, we would like for the driver to
work even when no metadata is available.
This commit modifies the initial metadata fetch code so that, in case it
fails, a dummy metadata is used instead. …
> cluster: use dummy metadata when initial fetch fails

- CONTRIBUTING.md
- scripts/test_in_docker/.env
- scripts/test_in_docker/Dockerfile
- scripts/test_in_docker/Makefile
- scripts/test_in_docker/README
- scripts/test_in_docker/docker-compose.yml
- scripts/test_in_docker/test_in_docker.ps1
- scripts/test_in_docker/test_in_docker.sh
This way developers on platforms other than Linux will be able to test
their changes without hassle, and we can remove the workaround #173
that has served for this purpose. Fixes: #476
> Added scripts for running tests in docker.

- scylla/src/frame/value.rs
- scylla/src/transport/session_builder.rs
Added Clone and Copy trait implementations for MaybeUnset enum as it is
necessary in cpp-rust-driver to copy CassStatement values.
Added Clone trait implementation to SessionBuilder in order to clone
cluster configuration while creating a session object.
> Add Clone to MaybeUnset and SessionBuilder

- scylla-cql/src/frame/mod.rs
- scylla-cql/src/frame/value.rs
This was needed in order to appease new clippy demands.
> scylla-cql: implemented Eq along with PartialEq

- examples/parallel-prepared.rs
- scylla/src/statement/mod.rs
- scylla/src/statement/prepared_statement.rs
- scylla/src/transport/retry_policy.rs
- scylla/src/transport/speculative_execution.rs
> statement: implement Debug for PreparedStatement

- scylla/src/transport/retry_policy.rs
The meaning of `data_present` was understood as the opposite in the
code.
> Fixed bug: inverted bool in DefaultRetryPolicy

- docs/source/SUMMARY.md
- docs/source/contents.rst
- docs/source/index.md
- docs/source/schema/schema.md
Our docs missed information about how to fetch and browse
schema information, including keyspace and table info.
> docs: add an entry about inspecting schema

- scylla/src/transport/connection_pool.rs
- scylla/src/transport/node.rs
> connection_pool/node: expose node sharder

- docs/Makefile
- docs/_utils/multiversion.sh
This is a follow-up of #537
This PR introduces markdown preprocessing for `sphinx-multiversion`.
It's done by running the `prepare_sphinx_source.py`script using the `--pre-build` flag.
It requries #537 to be merged first, so for now it's a Draft.
Fixes: #521
> Remove lines starting with # from Sphinx docs 2/2

- scylla/src/transport/connection.rs
Our router machinery is already capable of coalescing outgoing requests if multiple requests can be found in the queue. However, empirical evidence shows that it's beneficial to wait a short period of time (1ms, the best granularity tokio::time::sleep can handle at the time of this writing, is too much, so a sleep is simulated with yielding back to Tokio), thus sacrificing a small fraction of latency, in order to allow the queue to fill if we see that the receiver is actually empty. That translates to coalescing many more requests, which in turn means reducing the number of write operations, ergo less syscalls and sending fewer, but larger network packets.
Below are rudimentary tests results, based on a modified parallel-prepared example and ran with `time ( RUST_LOG=warn cargo run …
> connection: add another attempt of request coalescing

- scylla/src/transport/connection.rs
Instead of having separate functions for spawning connection router that get compiled or not depending on whether SSL support is enabled, now there is only one function which has a code block that gets conditionally compiled if SSL support is enabled. The resulting code is slightly shorter and simpler.
> connection: simplify router spawning logic

- RELEASE.md
Only useful for project maintainers, but nonetheless important enough to land in the repository.
> RELEASE.md: add a release procedure

- .github/workflows/rust.yml
- scylla-cql/src/errors.rs
- scylla/src/statement/prepared_statement.rs
- scylla/src/transport/downgrading_consistency_retry_policy.rs
> Fixes to remove warnings on docs build

- CONTRIBUTING.md
psarna doesn't work on this project anymore so I will be taking over his duties.
> Change maintainer from psarna to cvybhu

- scylla/src/transport/session_builder.rs
In `address_translator()`, fixed bad formatting and added port numbers to supplied addresses.
> session_builder: fixed doc example

- scylla-cql/src/frame/response/error.rs
- scylla-cql/src/frame/value.rs
- scylla-cql/src/frame/value_tests.rs
- scylla-proxy/src/frame.rs
- scylla/src/history.rs
- scylla/src/transport/session_test.rs
- ~~I added relevant tests for new features and bug fixes.~~
-  ~~I added appropriate `Fixes:` annotations to PR description.~~
> clippy new version's whims required some fixes

- scylla/src/transport/cluster.rs
- scylla/src/transport/session.rs
- scylla/src/transport/session_builder.rs
- scylla/src/transport/session_test.rs
- scylla/src/transport/topology.rs
This attribute allows filtering fetched keyspaces in metadata queries
Fixes #574
> session: add keyspaces_to_fetch configuration

- scylla-proxy/src/errors.rs
- scylla-proxy/src/proxy.rs
It has appeared to be useful to have a feature in the proxy to interact with the driver without having any Scylla nodes up. This is especially useful for unit testing.
> proxy: Enabled dry mode (run with simulated nodes)

- scylla/src/transport/iterator.rs
- scylla/src/transport/session_test.rs
Currently, the RowIterator expects that its background worker will always send at least one page (or an error) to the iterator. However, there is an edge case where it may not be true: if the first request executed via query_iter/execute_iter fails and the retry policy returns an IgnoreWriteError decision (currently returned only by downgrading consistency policy in case of WriteTimeout). In such case, those methods will trigger a panic.
This PR fixes this issue by sending a dummy, empty page to the iterator in the aforementioned case. Moreover, in order to make it less possible for such bugs to appear in this area of the code in the future, the RowIterator::work function is now forced to return an object which serves as a proof of the fact that it sent (or at least attempted to send) at …
> iterator: fix panic when retry policy returns IgnoreWriteError in iterator

- scylla-cql/src/frame/response/result.rs
- scylla-cql/src/frame/types.rs
- scylla/src/history.rs
- scylla/src/transport/load_balancing/latency_aware.rs
> appeasing clippy just another time

- scylla/src/transport/iterator.rs
- scylla/src/transport/session_test.rs
...instead of ProtocolError as before. This was requested by #631. Also, added a test for this behaviour.
Fixes: #631
> iterator: Return empty iterator on modification stmt

- scylla/src/statement/prepared_statement.rs
As cloning PreparedStatements may be convenient in some workloads, effort is done to make it possibly cheap. This commit put the heavy heap-allocated PreparedStatement metadata and its statement String behind an Arc, in a shared struct. In order to have cleaner inner API, usages of data referenced in the shared struct access them now through the getter.
Fixes: #635
> prepared_statement: Made cloning cheaper by use of Arcs

- examples/compare-tokens.rs
- scylla-cql/src/errors.rs
- scylla-proxy/src/proxy.rs
- scylla/src/transport/cluster.rs
- scylla/src/transport/connection.rs
- scylla/src/transport/connection_pool.rs
- scylla/src/transport/host_filter.rs
- scylla/src/transport/load_balancing/mod.rs
- scylla/src/transport/load_balancing/token_aware.rs
- scylla/src/transport/mod.rs
- scylla/src/transport/node.rs
- scylla/src/transport/session.rs
- scylla/src/transport/topology.rs
Motivations are described in the referenced issue.
Correctness of the changes is tested by the existing tests making use of address translation. 
Fixes: #640 
> Move address translation to opening new connection

- scylla/src/transport/connection.rs
> Minor typo fix in comment

- scylla/src/transport/session.rs
- scylla/src/transport/session_test.rs
Adds the `get_keyspace()` method which allows to get the keyspace name currently set for the session. Initially, it is set to the keyspace name specified in the session configuration as the keyspace to be USE-d, but it will be updated when calling `Session::use_keyspace()` later. Because of that possibility, `get_keyspace` returns a shared pointer to the keyspace name instead of a reference.
> session: add get_keyspace() method

- .github/pull_request_template.md
It's important to have documentation that is up-to-date, and the best time to update it is along with the changes introduced to the code. As not everybody remembers to do it every time (me, in particular), let's add a pre-review check about introducing docstrings and adjusting the documentation in the book.
> pull_request_template.md: add reminder to update docs

- scylla/src/transport/connection.rs
This allows users to see the errors that occurred during the handshake, previously the user just gets a generic `Wrong response to OPTIONS message was received`
> Handle errors that occur during handshake

- docs/source/connecting/connecting.md
> Docs: Add serverless cluster connect code example

- .github/workflows/serverless.yaml
- examples/cloud.rs
This PR adds a test workflow to CI for a serverless cluster. For now, only the `examples/cloud` example is added to test serverless support, but the existing tests will be adjusted to be run with a serverless cluster, see #688.
Fixes #687
> Serverless ci

- scylla/src/transport/load_balancing/default.rs
Described in #696.
Rust, unfortunately, makes lock guards taken on right side of `if let` expression live for else branch duration, too. This results in taking write lock while holding read lock.
In order to compile, I had to hint the `usize` type in one unrelated place, hence that change.
Added a regression test for the issue.
Fixes: #696
> default_policy: Fix deadlock on LatencyAwareness used

- scylla-proxy/src/frame.rs
This is a tiny feature addition to proxy, useful in tests. Currently needed for execution profiles testing in bindings.
> proxy: Add forged_ready()

- .github/workflows/serverless.yaml
- scylla/src/history.rs
- scylla/src/transport/caching_session.rs
- scylla/src/transport/connection.rs
- scylla/src/transport/connection_pool.rs
- scylla/src/transport/cql_collections_test.rs
- scylla/src/transport/cql_types_test.rs
- scylla/src/transport/cql_value_test.rs
- scylla/src/transport/load_balancing/default.rs
- scylla/src/transport/session_test.rs
- scylla/src/utils/test_utils.rs
- scylla/tests/execution_profiles.rs
- scylla/tests/lwt_optimisation.rs
- scylla/tests/retries.rs
This PR adjusts session tests to run with a serverless cluster in CI. As a serverless cluster requires a different Session setup, a generic way of session builder creation is added that creates a `CloudSessionBuilder` if the "cloud" feature is enabled for session tests.
Fixes #688 
EDIT:
Modified CI workflows to run cloud tests separately, as examples required the "cloud" feature to be enabled, `cargo test` run session tests for serverless mode.
> Serverless tests

- scylla/src/transport/session_test.rs
The driver's default configuration for fetching traces from the DB is quite unforgiving. After the query finishes, it tries 5 times to fetch tracing information, waiting 3ms between each attempt. This is too fast for Cassandra in CI and the `test_token_awareness` fails due to that.
This commit modifies the test so that it uses a much more relaxed configuration: 50 attempts with 200ms sleeps in between. As a long term solution, we should consider changing the default parameters.
> session_test: fix flakiness due to slow Cassandra tracing

- docs/source/quickstart/create-project.md
Fixes: #706
Fixes: #670 
- ~~[ ] I have split my patch into logically separate commits.~~
> docs: Updated scylla dep version

- examples/Cargo.toml
- scylla-cql/Cargo.toml
- scylla-proxy/Cargo.toml
- scylla/Cargo.toml
> Fixes chrono vulnerability caused by time dependency

- scylla-proxy/examples/cmdline.rs
- scylla-proxy/examples/identity_proxy.rs
- scylla-proxy/examples/identity_shard_aware_proxy.rs
The example is useful for manual testing of drivers with regard to address translation of DNS related functionalities, such as hostname mapping alterations combined with address changes.
> proxy: add an example configurable from cmdline

- docs/source/execution-profiles/priority.md
- docs/source/tracing/tracing.md
- scylla-cql/src/frame/value.rs
- scylla-cql/src/types/serialize/writers.rs
- scylla-proxy/src/proxy.rs
- scylla/src/cloud/config.rs
- scylla/src/history.rs
- scylla/src/routing.rs
- scylla/src/statement/prepared_statement.rs
- scylla/src/transport/caching_session.rs
- scylla/src/transport/connection.rs
- scylla/src/transport/load_balancing/default.rs
- scylla/src/transport/locator/precomputed_replicas.rs
- scylla/src/transport/locator/test.rs
- scylla/src/transport/locator/token_ring.rs
- scylla/src/transport/session.rs
- scylla/src/transport/session_builder.rs
- scylla/src/transport/session_test.rs
- scylla/src/transport/silent_prepare_batch_test.rs
- test/dockerized/run.sh
- test/tls/scylla.yaml
Mainly in comments.
Fixes: https://github.com/scylladb/scylla-rust-driver/issues/875
> Typos: fix minor typos in code

- scylla-cql/src/frame/value.rs
Simple `Default` trait for `MaybeUnset`
> impl Default for MaybeUnset

- CONTRIBUTING.md
The list got fully obsolete, so I updated it.
> CONTIBUTING.md: update maintainers list

- .github/workflows/book.yml
1.82 introduced a regression in book tests:
https://github.com/rust-lang/rust/issues/131893
> book.yml: Pin Rust version

- scylla/tests/integration/utils.rs
In the previous PR I forgot to also modify the utils in integration tests.
> Integration tests: Add DDL retry

- .github/workflows/authenticate_test.yml
- .github/workflows/book.yml
- .github/workflows/cassandra.yml
- .github/workflows/docs-pages.yaml
- .github/workflows/rust.yml
- .github/workflows/semver_checks.yml
- .github/workflows/serverless.yaml
- .github/workflows/tls.yml
- CONTRIBUTING.md
- MAINTENANCE.md
- Makefile
- README.md
When working on adjusting CI / README / MAINTENANCE for 1.0 I made some minor improvements that can easily be merged earlier.
To not clutter the main 1.0 PR, I'm opening this one.
> Minor CI / docs fixes

- .github/workflows/serverless.yaml
- scylla/tests/integration/statement.rs
> CI: Fix serverless job

- docs/source/statements/schema-agreement.md
We changed the return error type of this method, but forgot to update the docs.
> docs: fix error returned by Session::await_schema_agreement

- examples/compare-tokens.rs
> Fix example type annotations

- scylla/tests/integration/session.rs
Scylla 2025.1 does not support views + tablets combination. It's supposedly going to be supported in 2025.2.
What is weird, is that there was no such issue with most recent Scylla OS versions (6.2.x) which supported tablets as well.
> tests: disable tablets for views test

- scylla/src/client/session.rs
> session: remove needless clone of authenticator

- scylla/src/policies/load_balancing/default.rs
- scylla/src/routing/locator/tablets.rs
One thing: I disagree that the indentation in tablets.rs is bad. Therefore, I disabled the lint there.
> appease 1.86 toolchain's clippy

- MAINTENANCE.md
We decided not to include merge commits in the table with commits by author. Rationale: clicking "merge" should not count as a meaningful commit to the repo.
> MAINTENANCE.md: add `--no-merges` to git shortlog

- scylla-cql/src/types_tests.rs
This test checks that `DeserializeValue` macro behaves correctly in case of https://github.com/apache/cassandra/blob/4a80daf32eb4226d9870b914779a1fc007479da6/doc/native_protocol_v4.spec#L1003.
1. Serialize the UDT with a missing field value
2. Deserialize the serialized UDT, but include the missing field in metadata
3. Expect that the missing field value is treated as null
I don't know of any way to simulate this using the Scylla/C* cluster. CQL protocol mentions that such scenario is possible, but does not specify when it can appear.
Side note: cpp-driver throws an error in such case. After the discussion with @wprzytula, we concluded that such behaviour is not correct, since protocol specifications clearly states that this scenario (metadata present, serialized bytes missing) is …
> tests: udt deserialization with metadata present but value missing

- MAINTENANCE.md
Confusion would arise multiple times already around `scylla-cql` versioning requirements. In particular, it's not always clear to all that (and why) we **must not** release `scylla` with just minor bump if it bumps `scylla-cql`'s major.
I decided it deserves comprehensive explanation in `MAINTENANCE.md`.
> MAINTENANCE.md: describe `scylla-cql` API considerations

- scylla/src/observability/metrics.rs
Percentiles contained the number of observations in the corresponding bucket, instead of the mean value of the bucket.
I also added two simple test cases:
1. regression test for the bug
2. more general test case which checks whether the ordering between collected stats is correct.
> metrics: fix the bug where percentiles would return bucket count

- scylla/src/policies/timestamp_generator.rs
> timestamp: derive Debug for generator types
